### ISSUE TITLE
mod_wsgi for redhat & WEBPY (works locally, no response on internet)

### ISSUE THREAD

**Issue by PruthviKumarBK** [GrahamDumpleton/mod_wsgi#103]
Hi Graham,

Firstly, i cant thank you enough for detailing procedure for compiling mod_wsgi with webpy! All over internet, there was nothing but your blog that got me up and running!

Basically, i have my webpy application which works absolutely ok on windows machine (deployed on python's simple http server). Now i want to take this to Amazon's EC2 (running Linux RedHat) and host it on Apache (obviously to have my application prod ready). I have come a long way by solving zillion errors i got on this journey and now with the help of your blog, i have webpy and mod_wsgi working on my Ec2 instance since i can get the output when tested with both curl and links. (Oh! I cant be happier!)

Now, i have no clue for why this is not working on the internet. my mod_wsgi logs do not indicate any error but under apache logs, i have this logged: Directory index fofrbidden by Options directive: /var/www/html/

I tried changing Options -Indexes to Options +Indexes in my welcome.conf file but that did not help!

To paste my code, i have so much of it, i dont know what would help you understand the issue better. So, i will wait for your response and serve you with any files you would want to have a look at. 

Please help me through this. 

Thank you in advance, 
Best Regards,
Pruthvi

**Comment by GrahamDumpleton** [comment]
The issue tracker is not the right place for general problem solving. You are better off using a mailing list.

If this relates to Web2Py then use the Web2Py mailing list. If it specifically relates to mod_wsgi, then use the mod_wsgi mailing list. If it is a specific issue with Amazon and network access then maybe try StackOverflow as no idea where you get help on Amazon.

So if you still think is a mod_wsgi issue drop an email to the mod_wsgi mailing list along with the Apache/mod_wsgi configuration you are using. If external access doesn't work but access from the box itself does, then likely you have mucked up the VirtualHost/ServerName configuration.

**Comment by PruthviKumarBK** [comment]
Hi Graham,

Thank you, I got it working externally too! thanks for pointing me though. It was an issue with virtualHost config. 

However, i am having troubles with webPy picking up files under static folder. I get a 404 file not found for all of them. I have not bothered to make any changes to httpd's conf file since i have installed mod_wsgi through pip. Could you please guide me what is it that i am missing here? WEbPY is working and so is mod_wsgi. I have my site up and running but my css and JS files in static folder is not looked up. On the fly there is another httpd.conf created in the tmp directory (eg: /tmp/mod_wsgi-localhost:8181:500/httpd.conf). Do i have to make any changes there?

Your reply is much appreciated. I shall wait for your response. 

Thank you in advance, 
Best Regards,
Pruthvi

**Comment by GrahamDumpleton** [comment]
As I said, you should be using the mod_wsgi mailing list. The issue tracker is intended for reporting bugs in mod_wsgi, not as a support desk for your own setup issues.

As you are configuring Apache yourself, the pip installable mod_wsgi version (mod_wsgi-express) is totally irrelevant and you should ignore it. Just focus on your Apache configuration.

Please however take this to a more appropriate place for discussion.

Since at this point it looks more like an issue of how to setup Apache for handling Web2Py static files, I would suggest you ask on the Web2Py mailing list as I don't know/recollect what is required for Web2Py and no doubt it may well have changed.

if you still have no joy, then use the mod_wsgi mailing list and provide on that list the Apache/mod_wsgi configuration there. Please don't keep adding to this issue.
