### ISSUE TITLE
mod_wsgi-express exits when resizing terminal

### ISSUE THREAD

**Issue by sevens** [GrahamDumpleton/mod_wsgi#105]
Starting `mod_wsgi-express start-server` and resizing the terminal window in which it runs stops it with the following message:

```
[mpm_event:notice] [pid ...:tid ...] AH00492: caught SIGWINCH, shutting down gracefully
```

It looks like a known Apache httpd bug (https://bz.apache.org/bugzilla/show_bug.cgi?id=50669), which is resolved as WONTFIX.  But as, contrary to Apache httpd, mod_wsgi-express (usually) runs in the foreground it can be quite annoying (it already gets triggered when using search in at least some terminal emulators as it adds a search bar which takes some space away from the terminal-portion of the window).  No idea if a fix or workaround from mod_wsgi-express is even possible though.

Using mod_wsgi 4.4.21, Python 2.7.10 (64 bits), Konsole (terminal emulator), Apache HTTP 2.4.16 on Linux (4.1.6, 64 bits).

**Comment by GrahamDumpleton** [comment]
Yeah, this is quite a pain and no good solution. About all that could be done is to use a very lightweight C program which manages Apache as a child, passing on all signals except for ignoring SIGWINCH. I'd rather not use use a Python program to do it as even small Python programs use a lot of memory.

Either way, having an intermediate process like that may cause problems in some cases with process management solutions. One possibility is though to detect when is a foreground tty process and only use the wrapper process then.

**Comment by gitanupam** [comment]
Happy to know if folks have found any workaround for this issue yet.

**Comment by GrahamDumpleton** [comment]
Closing. Have implemented in https://github.com/GrahamDumpleton/mod_wsgi/commit/55d768eef5435a8228d7e61124a68c5f9be5b87c the ``--isatty`` option. If this option is used, Apache will be run as a sub process rather than replacing the script. When SIGINT, SIGTERM, SIGHUP and SIGUSR1 are received, then will be forwarded onto Apache, but if SIGWINCH is received it will be ignored. This will avoid Apache being shutdown when the terminal is resized.

Note that the ``--isatty`` option is currently required so that can evaluate whether the mechanism used to create the sub process, and the forwarding of signals, is reliable, before making it the default behaviour based on looking at wether the attach terminal is a tty or not. Will create an issue later to make default behaviour if deemed is safe to do so.
