### ISSUE TITLE
Nginx in front of apache with mod_wsgi?

### ISSUE THREAD

**Issue by okyere** [GrahamDumpleton/mod_wsgi#113]
This is more of a conceptual question. I'm reading about the benefits of nginx as a server. Most people recommend that you make nginx act as a reverse proxy that relays requests to apache. My question is if I'm using mod_wsgi to server my python application, will it be affected if I put an nginx server in front of apache? Would I need to change or configure anything? Thanks.

**Comment by GrahamDumpleton** [comment]
Please note that general question are better off directed to the mod_wsgi mailing list. The issues tracker is primarily intended for bug reports. Use the mailing list for future general questions.

As to the question, placing nginx in front of Apache may make absolutely no difference. It really depends on what your application is doing. If using daemon mode of mod_wsgi and you have configured things well, then even less of a need for nginx as a front end. So not knowing what your requirements are, is very hard to say.

If you did put nginx in front of Apache then for mod_wsgi then yes your configuration or WSGI application would likely need to change. This is because people will be connection on a different host or port to what the Apache back end is listening on. This means details of the host as they come through to your WSGI application will be wrong in the WSGI environment. You need to configure mod_wsgi or use WSGI middleware or framework support to fix up the WSGI environment based on proxy headers.

For some more discussion about this see:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
