### ISSUE TITLE
Using express with prebuilt mod_wsgi

### ISSUE THREAD

**Issue by bkabrda** [GrahamDumpleton/mod_wsgi#123]
Hi, I'm not sure if that's even possible, but I'd like to use all the goodness of `mod_wsgi-express` executable with a prebuilt version of mod_wsgi. IOW, I'd like to do in my Dockerfile:
```
RUN dnf install -y httpd mod_wsgi
RUN pip install mod_wsgi
```
The advantage of that approach would be not having to install gcc, httpd-devel and python-devel in my image and also using distro-supported version of mod_wsgi.
If you think this makes sense, I'd like to help with the implementation (given some pointers, since I don't know mod_wsgi code at all).

**Comment by GrahamDumpleton** [comment]
No, mod_wsgi-express will never be available as a binary package with distributions. If distributions try and do it, I will be telling them not to.

There are a few reasons for this including:

* Existing binary versions of mod_wsgi available from Linux distributions are in fact not supported. The Linux distributions (especially Debian/Ubuntu) do not support them (no matter what they may say) and neither do I support them. The mod_wsgi versions are always so far behind that they are well beyond their use by date and any reasonable version range that I might even consider supporting were people to build direct from source code. The only exception to the no support stance is RHEL, where I will assist if I can in relation to security issues.
* The mod_wsgi-express only components, that is the Python wrapper scripts and the Python module called mod_wsgi, are bound specifically to an Apache mod_wsgi module version as generally changes are being made in both at the same time to support features. As such, the mod_wsgi-express components could not be released separately and updated while the Apache mod_wsgi module itself remains as the outdated version that the Linux distributions ship.

Overall the Linux distributions are killing the ability to innovate because of the policies they use which means that systems get stuck with old versions which never get updated. I therefore ignore Linux distribution packages for mod_wsgi and I would recommend you do the same if you want anything that is truly supported.

As to Docker, I have my own Docker images and build/deployment environments to use with them, which especially with the next iteration of them, will going forward be a better option than anything one might construct themselves if wanting to use mod_wsgi. I have already demonstrated on my blog mechanisms I have developed for speeding up Docker image builds for Python web applications. The next thing I will be working on is a multi phase build process which utilises two Docker images. One a builder image which incorporates gcc and all the required development packages for libraries etc, and a runtime image which doesn't have all that stuff in them. Your application and all the packages you need would be compiled and installed via a builder image, with the result then being copied across into a much slimmer runtime image.

That said, the value of pursuing the slimmest possible images is somewhat overblown due to the layering mechanism in Docker. Although it may take a bit longer with a fatter image the first time it is deployed, subsequent deploys will benefit from the fact that base images are already present and so pushing out new images will be fast. This fact gets glossed over or ignored by those pushing for ultra slim images. In the worst case ultra slim images only serve to make your job harder, as the lack of basic tools in the image such as network diagnostic tools, performance monitoring tools, editors, etc, means you have no way to debug problems in a running container.

All I can suggest is you keep an eye on what I am doing via my blog posts. Right now I have been using Debian as a base image for what I am doing, but before too long I will be providing images for Debian, CentOS and Fedora.

**Comment by bkabrda** [comment]
Thanks a lot for the response, it makes perfect sense.
