### ISSUE TITLE
version check warning

### ISSUE THREAD

**Issue by propertone** [GrahamDumpleton/mod_wsgi#129]
mod_wsgi logs a warning at Apache startup if the compiled version of python does not exactly match the runtime version, but since minor releases are guaranteed to be binary-compatible, maybe it should assume that 2.A.X is compatible with 2.A.Y. Otherwise, this results in a warning message whenever python is upgraded without recompiling mod_wsgi.

**Comment by GrahamDumpleton** [comment]
There are cases where even the patch level version mismatch can be important and indicates a problem.

One is where you have a system Python version of the same major/minor version as another Python installation under ``/usr/local``. The latter may be a newer patch level revision and what you really want to use. If you didn't compile mod_wsgi with ``LD_RUN_PATH`` to force it to use the Python shared library from ``/usr/local/lib``, then it will pick up the system Python shared library. In this case you would get a warning because mod_wsgi was compiled against a newer patch level revision than the one it found the Python shared library for. This would indicate an actual problem to be fixed and couldn't be ignored.

Another instance which just happened in the last few days is where someone had done everything they needed to to use an installation in ``/usr/local``, but was still getting the warning. It turned out that someone had somehow screwed up the Python installation with header files being for latest patch level, but the shared library was somehow still an older patch revision. The warning highlighted the problem and so when we worked out what was wrong, they removed the Python installation and reinstalled it again.

One can have other strange cases, including where mod_python was being loaded as well and it was compiled against a different Python installation or version.

So it isn't necessarily the case that a patch level difference means there are no problems. I am not even sure that trying to add a check such that you only warn if using an older patch revision than was compiled for, which covers first two cases above. Part of the problem there is that some distributions screw around with the version string and add suffixes to it, which makes it harder to make sense of the patch revision part.

I am therefore not overly keen on dropping it as it has been useful many times and helped solve actual problems.

**Comment by propertone** [comment]
Ok, thanks for the explanation.
