### ISSUE TITLE
mod_wsgi mess

### ISSUE THREAD

**Issue by jcsantosx** [GrahamDumpleton/mod_wsgi#134]
Hello ;)
I'm trying to deploy my app for 2 days and really can't pass the mod_wsgi...
A little help would be nice, if you don't mind.

ubuntu server 14.04 / apache 2.4.7 / python 3.4.3 / mod_wsgi 4.5.2 / Flask / virtualenv

I've ./configure with --target=python3

in *.conf if I put " WSGIScripAlias /myApp /var/www..." show all the directories, but if remains as follow give 500 error:
`LoadModule wsgi_module /var/www/FlaskApps/myApp/venv/lib/python3.4/site-packages/mod_wsgi/server/mod_wsgi-py34.cpython-34m.so
WSGIScriptAlias / /var/www/FlaskApps/FlaskApps.wsgi
`

in myApp.wsgi:
```
#!/usr/bin/python3
activate_this = '/var/www/FlaskApps/myApp/venv/bin/activate_this.py'
exec(compile(open(activate_this).read(), activate_this, 'exec'))
```

in apache2 error.log:
```
[Tue May 17 21:34:44.038999 2016] [mpm_event:notice] [pid 6495:tid 139697017870208] AH00491: caught SIGTERM, shutting down
[Tue May 17 21:34:45.026727 2016] [mpm_event:notice] [pid 6614:tid 140270307772288] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/4.5.2 Python/3.4.3 confi$
[Tue May 17 21:34:45.026796 2016] [core:notice] [pid 6614:tid 140270307772288] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 17 21:34:53.605026 2016] [wsgi:error] [pid 6618:tid 140270203098880] [client 2.82.203.124:55944] mod_wsgi (pid=6618): Target WSGI script '/$
[Tue May 17 21:34:53.605095 2016] [wsgi:error] [pid 6618:tid 140270203098880] [client 2.82.203.124:55944] mod_wsgi (pid=6618): Exception occurred pr$
[Tue May 17 21:34:53.605140 2016] [wsgi:error] [pid 6618:tid 140270203098880] [client 2.82.203.124:55944] Traceback (most recent call last):
[Tue May 17 21:34:53.605436 2016] [wsgi:error] [pid 6618:tid 140270203098880] [client 2.82.203.124:55944]   File "/usr/lib/python3/dist-packages/url$
```

also if i do:
```
sudo locate mod_wsgi:
/usr/lib/apache2/modules/mod_wsgi.so
```

Thanks for your time.

**Comment by GrahamDumpleton** [comment]
You appear to have multiple conflicting installs. The ``configure`` command only relates to building manually from source code. The ``LoadModule`` line you have would be what you use if doing ``pip`` style install, yet you also have a non ``pip`` module installed. There is also no ``--target`` option to ``configure``. You also chopped off the end of the error log messages so it isn't possible to see what your problem is.

For a start you need to choose one installation method only, not both at the same time. Also need to see the full error traceback and messages.

There are other things you can do better as well, but start by choosing one install type only and provide those error messages.

**Comment by GrahamDumpleton** [comment]
Closing as assumed no further help required.
