### ISSUE TITLE
Download url has changed

### ISSUE THREAD

**Issue by joyrexus** [GrahamDumpleton/mod_wsgi#152]
Looks like the download urls for earlier versions (< 3.5) have changed.

See, for example, the [3.4 release notes](https://github.com/GrahamDumpleton/mod_wsgi/blob/e238c93ceff2694aec391194e23ab821c6f2cd8c/docs/release-notes/version-3.4.rst) which link to `http://modwsgi.googlecode.com/files/mod_wsgi-3.4.tar.gz` ... but that 404s.

The new url should be https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/modwsgi/mod_wsgi-3.4.tar.gz.

This is likely due to changes happening with the google code archive and it's pending shutdown.

**Comment by GrahamDumpleton** [comment]
You shouldn't be using mod_wsgi 3.4. It is something like 5+ years old and over 25+ versions behind, and is definitely not supported in any way.

Use current releases from:

* https://github.com/GrahamDumpleton/mod_wsgi/releases

If you really need an old version, you can use the version tag. Such as:

* https://github.com/GrahamDumpleton/mod_wsgi/releases/tag/3.4

Please though do not use such an old version.

Links in very old release notes files which have been broken because of the shutdown of Google Code site will not be updated.
