### ISSUE TITLE
"python-home" not in the docs

### ISSUE THREAD

**Issue by guettli** [GrahamDumpleton/mod_wsgi#163]
I think the "python-home" parameter is great, but I can't see it in the docs.

I am missing the docs here:

  * http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html
  * http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html

There is a hint in the release notes:

https://github.com/GrahamDumpleton/mod_wsgi/search?q=%22python-home%22

Is this a secret magic, or a dirty hack which should not be used?

**Comment by GrahamDumpleton** [comment]
It is the preferred way of setting up a virtual environment when using daemon mode. The docs are way out of date.

* http://blog.dscpl.com.au/2014/09/using-python-virtual-environments-with.html

**Comment by guettli** [comment]
I use mod_wsgi since years. Is there a reason why the docs are out of date? Is it difficult to add some infos about `python-home`?

I guess most people don't use apache these days. Up to now I am happy with it. Do you still suggest new comers to use mod_wsgi?

**Comment by GrahamDumpleton** [comment]
I have been too busy adding new features around mod_wsgi to make it work in awesome ways in Docker and containerised hosting environments. Updating documentation just hasn't been high priority as the majority of people don't read the documentation anyway and seem to think Stack Overflow is a better source of information. So I concentrate on doing stuff that makes me happy instead. :-)

There is absolutely no reason why you wouldn't use mod_wsgi. Of all the main WSGI servers it is still probably the one getting the most attention as far as improving on it to make it work better with the new containerised world we are finding ourselves in.

If you haven't seen it, you might have a look at ``mod_wsgi-express``.

* https://pypi.python.org/pypi/mod_wsgi

and if using Docker at all, I have lots happening in that space as well to make hosting Python web applications much easier.

**Comment by guettli** [comment]
Yes, you are right: Most people don't read docs. But some do. I team mate and I checked the docs an we were confused since there were docs. I created a pull request which explains `python-home`: 

https://github.com/GrahamDumpleton/mod_wsgi/pull/166

**Comment by guettli** [comment]
If you use python-home, do you still need the Baseline stuff, which gets explained here: http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#baseline-environment

I would like to improve the docs, but I don't know the details.

**Comment by GrahamDumpleton** [comment]
And that is where the can of worms gets opened up and why I am slow getting around to it. :-)

There are actually about a dozen or more options not documented for ``WSGIDaemonProcess`` and other directives, plus all the other pages that need to be updated to match new and better ways of doing things. So I tend to look at it and say to myself, that is going to take a while to do properly and things bog down.

I'll see if I can dedicate some time to it over the next week and finally do it. So keep pushing me.

**Comment by GrahamDumpleton** [comment]
You can see first docs page to be updated at:

* http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html

As you can see, many options which weren't documented before. :-)

**Comment by guettli** [comment]
Wow, you changed a lot. Thank you for updating the docs.

For me WSGIDaemonProcess.html looks good.

I guess this still needs some clean up action: http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by guettli** [comment]
@GrahamDumpleton Do you like docker? I am unsure. Up to now I like the virtualenv solution we use.

This has the benefit, that we can use ssh to enter the virtualenv and fix something, if there is something wrong in the production environment. I don't need this daily, but it gives me a good feeling, that it is available.

AFAIK this does not work with docker.

**Comment by GrahamDumpleton** [comment]
Using containers has various good points. The Docker implementation, even though easy to use, could be better. It gets a lot of criticism of having bugs. The state of layered file systems Docker relies on needs to improve as well due to bugs and other issues. Docker starts to have issues when you go beyond a single node. Docker swarm still isn't great and you need a better orchestration system such as Kubernetes to make it workable at scale.

Despite those warnings, yes I do like the concept of containers and what that can provide. Lots of my personal work over the last few years has been directed at making Python web application deployment in containers easier. Am so interested in it I got myself a job in Red Hat where I can work on all this sort of stuff. It can work well, but don't think Docker alone is enough, you need extra stuff on top like Kubernetes and OpenShift to make it work if need to deploy across multiple hosts.

FWIW, if curious about part of what have been working on this area watch my PyCon NZ talk about warpdrive.

* https://www.youtube.com/watch?v=y_vwvqgRZK0&t=2s

And finally. You can still get inside a running Docker container to see what is going on, but you have to remember that you are only changing stuff local to that one instance and you will loose changes on a restart of the container. So yes you do need to go back to modify the original image to make software changes permanent. Also, normally the Python web application is the only process and depending on what WSGI server you use, you can't restart it, as shutting it down will cause the container to exit. If using ``mod_wsgi-express`` that isn't an issue as it still uses Apache and so you can just tell Apache to reload and it doesn't actually shutdown.

**Comment by GrahamDumpleton** [comment]
Virtual environments doc updated:

* http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by guettli** [comment]
I watched your video about warpdrive. I hope it is ok, if I use this issue to provide some positive feedback. I left the comment on youtube.

**Comment by GrahamDumpleton** [comment]
I answered the comment on YouTube site.

**Comment by guettli** [comment]
@GrahamDumpleton thank you very much for updating the docs!

There is still a lot to talk about, but for today, this issue is solved according to my point of view.

I wish you a marry Christmas.
