### ISSUE TITLE
"media" returns a 404 error when mod_wsgi used with django

### ISSUE THREAD

**Issue by julienfastre** [GrahamDumpleton/mod_wsgi#185]
Hi,

Since a couple of days (the new version), the media present in `media` directory return a 404 error.

I could fix the problem by appending those line to the file `httpd.conf` created by the command `runmodwsgi` : 

```
Alias '/media' '/code/files/media/'                  
                                                     
<Directory '/code/files/media/'>                     
<IfVersion < 2.4>                                   
    Order allow,deny                                
    Allow from all                                  
</IfVersion>                                         
<IfVersion >= 2.4>                                   
    Require all granted                              
</IfVersion>                                         
</Directory>
```

Here is the full `Dockerfile` (we use mod_wsgi with docker): 

```
FROM python:3.6

WORKDIR /code

# Disable debug by default
ENV DEBUG="0" \
    ALLOWED_HOSTS=localhost \
    LOGGERS_HANDLERS=console

RUN apt-get update && apt-get install -y --no-install-recommends \
       apache2 \
       apache2-dev \
       gdal-bin \
       gettext \
    && rm -rf /var/lib/apt/lists/* 

ADD . /code

# creating a dir for media
RUN mkdir -p /code/files/media \
    && chown www-data:www-data /code/files/media

VOLUME /code/files/media/

RUN pip3 install -r /code/requirements.txt

RUN python manage.py collectstatic --no-input \
    && python manage.py runmodwsgi --setup-only --port=80 \
        --user www-data --group www-data \
        --locale C.UTF-8 \
        --server-root=/etc/mod_wsgi-express-80 \
        --log-to-terminal \
        --log-level "debug" \
        --access-log 

# without this, media returns a 404 error
RUN cat mod_wsgi.patch >> /etc/mod_wsgi-express-80/httpd.conf 

COPY rewrite.conf /etc/mod_wsgi-express-80/rewrite.conf

COPY bug_fix/serializers.py  /usr/local/lib/python3.6/site-packages/djgeojson/serializers.py

EXPOSE 80

CMD ["/etc/mod_wsgi-express-80/apachectl", "-D", "FOREGROUND"]
```

**Comment by GrahamDumpleton** [comment]
You can be more precise about which version of mod_wsgi you are using when you say latest? Are you talking about version 4.5.13, or ``develop`` branch of GitHub repo.

There is a problem with using ``--url-alias`` with ``runmodwsgi`` and Python 3.6 in 4.5.13.

**Comment by julienfastre** [comment]
Hi,

We are currently using version 4.5.13: 

```bash
$ pip freeze
Django==1.10.5
django-ckeditor==5.2.1
django-geojson==2.9.1
django-internationalflavor==0.3.0
django-leaflet==0.19.0
django-localflavor==1.3
django-registration==2.2
html2text==2016.9.19
humanize==0.5.1
jsonfield==1.0.3
mod-wsgi==4.5.13
olefile==0.44
Pillow==4.0.0
psycopg2==2.6.2
python-logstash==0.4.6
six==1.10.0
```

We do not use `--url-alias`, the command used for preparing the `httpd.conf` is 

```bash
python manage.py runmodwsgi --setup-only --port=80 \
        --user www-data --group www-data \
        --locale C.UTF-8 \
        --server-root=/etc/mod_wsgi-express-80 \
        --log-to-terminal \
        --log-level "debug" \
        --access-log
```

Thanks a lot for your efforts !

**Comment by GrahamDumpleton** [comment]
Unless you had been using ``--url-alias``, or had added explicit configuration using ``--include-file`` (or modifying the generated ``httpd.conf`` file, which you shouldn't do), the only way anything could have been served up under the ``/media`` URL is if you Django application was running a static file handler which handled that URL, or if you were using the ``--document-root`` option to specify a directory which had as a sub directory the ``media`` directory. This is because the ``mod_wsgi-express`` integration for Django doesn't by default do anything for the media directory.

Anyway, ensure you are using 4.5.14 (not 4.5.13 or earlier due to issue mentioned above) and use the option option:

```
--url-alias /media /code/files/media
```

Ensure that the directory ``/code/files/media`` exists first to be safe.

You should not modify the generated ``httpd.conf`` file. If you need to add more configuration, put it in a file and use the ``--include-file`` option. That file will then be included at the end of the generated ``httpd.conf`` file.

Instead of overwriting the ``rewrite.conf`` file, use the ``--rewrite-rules`` option to refer to the file which contains any rewrite rules.

BTW, you should not need to do the setup in the Docker build phase, you could just run 

```
python manage.py runmodwsgi --port=80 \
        --user www-data --group www-data \
        --locale C.UTF-8 \
        --server-root=/etc/mod_wsgi-express-80 \
        --log-to-terminal \
        --log-level "debug" \
        --access-log \
       --url-alias /media /code/files/media
```

as the ``CMD``.

**Comment by julienfastre** [comment]
Wow, a lot of improvements :-) 

Thanks for the tip about url-alias and include-file. I missed it when I dump the syntax using the  `--help` command.

`--url-alias` works fine !

I do agree about running apache using the `CMD`, but I wonder if having a huge `CMD` is or is not less readable. I am going to discuss with my colleague. But thank you again for the tip: it worth thinking about it.

I propose to close this issue: my problem is solved.

**Comment by GrahamDumpleton** [comment]
I could question why you are building Docker images from scratch yourself. :-)

I have been doing a lot of work the last couple of years on providing a best of bread Docker image for hosting Python web applications. You can get a small glimpse of some of the work by reading:

* http://blog.dscpl.com.au/2016/02/building-better-user-experience-for.html

That was from a year ago, so you can imagine that has seen various improvements since then.
