### ISSUE TITLE
[feature request] rpmbuild spec file

### ISSUE THREAD

**Issue by YouriAndropov** [GrahamDumpleton/mod_wsgi#220]
Hi,

It would be great for offline installation that we could rpmbuild from the sources and get a binaries rpm to deploy on target platform.
To do so, a spec file is needed with the source files.

Regards.

**Comment by GrahamDumpleton** [comment]
You are better off creating a binary Python wheel for the mod_wsgi package and then install that, or even go with a source tar ball. Either way, use ``pip`` to install it.

Details of using ``pip`` installation method can be found at:

* https://pypi.python.org/pypi/mod_wsgi

To see how to generate binary Python wheels see:

* https://wheel.readthedocs.io/en/latest/

**Comment by YouriAndropov** [comment]
It was intended for offline installation, pip install is not possible.

**Comment by GrahamDumpleton** [comment]
Read the link about Python wheels. One can use ``pip wheel`` command to build a directory of Python wheels for all Python packages you need. You can then do a disconnected install later by telling ``pip`` to use the directory of wheels and try and contact PyPi. No Internet connection is therefore required. This is regarded as best practice for doing offline installs of Python packages.

**Comment by GrahamDumpleton** [comment]
Since the preference is using Python wheels and running ``pip`` against local wheel files and with use of PyPi disabled, I am going to close this issue.

If you really wanted to still build an RPM file, I would suggest pulling down SRPM for mod_wsgi from CentOS and extracting any RPM spec file from that and adapting it to latest mod_wsgi versions. Eg:

* https://rpmfind.net/linux/RPM/fedora/27/aarch64/m/mod_wsgi-4.5.15-4.fc27.aarch64.html

I don't know anything about creating RPM, DEB or YUM packaging files myself nor do I have available systems to maintain them.
