### ISSUE TITLE
Apache LoadModule issue 

### ISSUE THREAD

**Issue by Nahel88** [GrahamDumpleton/mod_wsgi#234]
Hello,
my Apache24 cannot load the module Mod_wsgi on Windows , i tried to add the configuration using : 

> mod_wsgi-express module-config
 and I added the results to the config file: 

**LoadModule wsgi_module "C:/Python27/lib/site-packages/mod_wsgi-4.5.20-py2.7-win-amd64.egg/mod_wsgi/server/mod_wsgiNone"
WSGIPythonHome "C:/Python27"**

but i could not start the Apache Service after that . 
I have Apache2.4
Python 2.7.14
and on python the following packages: 
mod-wsgi==4.5.20
Django==1.11.6
setuptools 5.7

Although the file name is not mod_wsgiNone but mod_wsgi.pyd so I tried all the possible combinations but also did not work. Also I tried to rename the  mod_wsgi.pyd to mod_wsgi.so and copy it to apache24/modules and use

LoadModule wsgi_module modules/mod_wsgi.so

but did not work too.

**Comment by GrahamDumpleton** [comment]
The config isn't generated correctly for some Python 2.7 installations. Change the value of ``LoadModule`` such that ``None`` at end is replaced with ``.pyd``.

If that still doesn't work, double check you aren't mixing 32 and 64 bit versions of Python, Apache and Microsoft C compiler.

Even if using correct architecture for each, is a chance will still not work as there is Python 2.7 requires everything to be compiled with VC9 compiler, but Apache likely isn't as is hard to get Apache distro that still uses VC9.

The preferable thing is to use Python 3.6 instead of 2.7,  as 2.7 gives a lot of problems with being able to get correctly compiled version of Apache.
