### ISSUE TITLE
Target WSGI script cannot be loaded as Python module.

### ISSUE THREAD

**Issue by ankhbayarb** [GrahamDumpleton/mod_wsgi#239]
I've been spinning around for almost 3 days to configure my django app on apache mod_wsgi. 
I have a VPS with CentOS 6.9, EasyApache, Python3 installed. Virtualenv installed. Started django project on that virtualenv. 

```
`SyntaxError: invalid syntax
mod_wsgi (pid=25212): Target WSGI script '/home/user/Project/Project/wsgi.py' cannot be loaded as Python module.
mod_wsgi (pid=25212): Exception occurred processing WSGI script '/home/user/Project/Project/wsgi.py'.
Traceback (most recent call last):
   File "/home/user/Project/Project/wsgi.py", line 12, in <module>
   from django.core.wsgi import get_wsgi_application
File "/usr/lib/python2.6/site-packages/django/__init__.py", line 3, in <module>
  from django.utils.version import get_version
   File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
 File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
```
`

**Comment by GrahamDumpleton** [comment]
As can be see by paths in the messages, your mod_wsgi is compiled for Python 2.6. The code you are trying to run for Django requires a minimum Python version of Python 2.7 because of set syntax.

You need to reinstall mod_wsgi compiled against Python 3.X version you want to use.

Note also that you cannot use mod_wsgi compiled for one Python version with a Python virtual environment for a different version. The mod_wsgi must be compiled for the same version.

**Comment by ankhbayarb** [comment]
I can't understand it clearly. So what should I do now? What you mean by reinstall mod_wsgi compiled against Python 3.X?

**Comment by GrahamDumpleton** [comment]
The mod_wsgi package you have installed is not Python code but C code using the Python C API. It must be compiled against the Python library for the Python version you want to use. You can verify what Python version it was compiled for using test in:

* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-installation-in-use

and also:

* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-shared-library

Presuming you used a system package for mod_wsgi, you would need to uninstall it using ``yum`` or ``rpm`` and then find a newer package for it compiled for Python 3.X that you want to use. This may mean you have to compile it from source code yourself, especially since you want to use Python 3.X and going to be no system package for mod_wsgi and Python 3.X on such an old CentOS version.

One way to easily compile it is to use the ``pip install`` method:

* https://pypi.python.org/pypi/mod_wsgi

Then using ``mod_wsgi-express start-server`` on command line if just using for development, or use ``mod_wsgi-express module-config`` to generate config to integrate with your system Apache. See that PyPi page for details.
