### ISSUE TITLE
Looking for stale socket file

### ISSUE THREAD

**Issue by EliezerIsrael** [GrahamDumpleton/mod_wsgi#255]
We're seeing WSGI looking for a non-existent socket file. 
I don't think it's the known issue dealing with graceful restart.
We've specified the WSGISocketPrefix explicitly.

With `WSGISocketPrefix /var/run/wsgi/wsgi` in the conf, the socket directory looks like this:

```
root@prod:/var/run/wsgi# ls -latr
total 0
srwx------  1 www-data root   0 Jan  4 08:02 wsgi.31813.1.2.sock
srwx------  1 www-data root   0 Jan  4 08:02 wsgi.31813.1.1.sock
drwxr-xr-x  2 root     root  80 Jan  4 08:02 .
drwxr-xr-x 16 root     root 660 Jan  4 15:52 ..
```

Most requests complete, but we're seeing logs like this:
```
[Thu Jan 04 16:29:54.838011 2018] [wsgi:error] [pid 4547:tid 139913626367744] (2)No such file or directory: [client 127.0.0.1:46598] mod_wsgi (pid=4547): Unable to connect to WSGI daemon process 'sefaria.org' on '/var/run/wsgi/wsgi.31813.0.1.sock' as user with uid=33., referer: http://www.sefaria.org/data.js
```

Note that it's looking for `wsgi.31813.0.1.sock`, instead of `wsgi.31813.1.1.sock`

Apache version is 2.4.29, running on Ubuntu
WSGI version 4.5.24

**Comment by EliezerIsrael** [comment]
I found that my server was running an old apache process that somehow seemed to have gone renegade.  Don't ask me to explain it, I really don't know.  But it was writing to old `.1` logfiles, serving old mod pagespeed references, and had a much earlier PID than the rest of apache.  I killed that process, and so far, these errors have left the logs...

**Comment by GrahamDumpleton** [comment]
Assuming this is good now.

**Comment by EliezerIsrael** [comment]
@GrahamDumpleton I have more information now, that makes me wonder if mod_wsgi is involved in this.  When a graceful restart is issued, the Apache thread running mod_wsgi fails to exit.  A new one starts, and that's what is causing the reference to a stale socket and the holding of a pointer to log.1.  

Any ideas?

**Comment by GrahamDumpleton** [comment]
There are two types of child processes of the Apache parent process. Apache's own worker processes, and other managed processes. The mod_wsgi daemon process fall into the latter category.

When an Apache restart occurs, there is no way the managed processes can survive as Apache will force kill them (SIGKILL) if they don't shutdown after 5 seconds. Nothing should be able to prevent that.

Apache's own worker processes are a different matter. If it is a normal Apache restart, they too will be killed off after 5 seconds if they don't shutdown just like other managed processes. In the case of a graceful restart though, Apache will not kill them off after 5 seconds and instead the processes themselves will survive and kill themselves when they have finished handling all keep alive connections and no more requests come in via those connections.

If you are using daemon mode as you should, then you shouldn't have any Python code running in the Apache worker processes. Hopefully you are also preventing the startup of the Python interpreter in those processes by using:

```
WSGIRestrictEmbedded On
```

Either way, it is Apache that controls the worker processes and not mod_wsgi, and so mod_wsgi shouldn't be able to interfere in any way. There shouldn't be a way for mod_wsgi to stop Apache killing off the other managed processes either since you can't block SIGKILL.

What you need to work out is whether the process which is hanging around is a worker process or a daemon process. You also need to work out whether it was really a daemon process, or perhaps the problem is that your web application is running sub processes which then disassociate themselves from the process it was forked. This could be an issue because the sub processes will inherit the stdout/stderr from Apache, which would map to the Apache error log, but may not be killed when the daemon process they were a child of was killed.

General rule is that it is a bad idea to run complicated sub processes out of a multiple process web server because you inherit various open files and sockets from the web server supervisor process, including the log file. That open files are inherited means the sub process could interfere with things such as by holding open files beyond when they had been closed by the Apache parent process.

**Comment by EliezerIsrael** [comment]
Thanks for writing this out.  It gives me a good bit of context that I was missing.
