### ISSUE TITLE
any precompiled mod_wsgi for python 3.6 and apache 2.4 

### ISSUE THREAD

**Issue by am2222** [GrahamDumpleton/mod_wsgi#325]
Hi,
I could use mode_wsgi for python 3.4 and apache 2.4 on windows but Is there any precompiled version for windows which is compiled against python 3.6?

**Comment by GrahamDumpleton** [comment]
I have nothing to do with the creation of them, but there is:

* https://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

Download the ``whl`` file and I believe you should be able to run:

```
pip install ./mod_wsgi‑4.6.4+ap24vc10‑cp34‑cp34m‑win32.whl
```

You might then be able to run:

```
mod_wsgi-express module-config
```

to get what you need to add to Apache to load the module.

This is a guess though, because as I said I don't create those and am just assuming what is in them.

**Comment by am2222** [comment]
@GrahamDumpleton wow thanks very much it worked
