### ISSUE TITLE
Python 2: (DLL) initialization routine failed for mod_wsgi.pyd

### ISSUE THREAD

**Issue by jyn514** [GrahamDumpleton/mod_wsgi#326]
## Problem

The following line of code is breaking Apache on startup: `LoadModule wsgi c:\python27\lib\site-packages\mod_wsgi\server\mod_wsgi.pyd`. The error:

```
C:\Apache24\conf>..\bin\httpd.exe -t
httpd.exe: Syntax error on line 536 of C:/Apache24/conf/httpd.conf: Cannot load c:\\python27\\lib\\site-packages\\mod_wsgi\\server\\mod_wsgi.pyd into server: A dynamic link library (DLL) initialization routine failed.
```
## Things I tried

I used Dependency Walker on `mod_wsgi.pyd` and it says the following libraries are missing:

- API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
- API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
- API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
- API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
- EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL
- IESHIMS.DLL

According to [this post](https://stackoverflow.com/a/36426675/7669110), however, those are false positives.

I was looking at [this](https://serverfault.com/questions/692651) result on serverfault, linking to [this page](https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/win32/README.rst) which appears to be outdated (before `pip install mod_wsgi` was available). Should I still use the versions of mod_wsgi from [the site linked](http://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi)?

## Version
Apache version: `2.4.33`
Python version: `2.7.15`
mod_wsgi version: `4.6.4`

Thanks for your time, I know this is a solo project.

Update: if it makes a difference, `mod_wsgi-express module-config` is giving bad output, `LoadModule wsgi_module "c:/python27/lib/site-packages/mod_wsgi/server/mod_wsgiNone"`. I have the correct file name in my apache config, though.

**Comment by GrahamDumpleton** [comment]
Can you use Python 3.6?

I don't know what the issue is, but a lot of the time people can't get Python 2.7 working anymore.

It is very important to have all 64 bit or all 32 bit for everything, and the correct VC9 compiler. Even then it may fail as Apache is built using VC14 these days which isn't strictly compatible with VC9. You may get lucky, you might not.

I don't think the binaries on the gohike site would make a difference, but you can try.

I don't personally know anything about Windows and can't debug what is going on, and no one has offered up any suggestions or solution unfortunately. Using Python 3.6 always seems to be okay, again as long as have all 64 bit (avoid 32 bit if can).

**Comment by jyn514** [comment]
At least part of this was me using a version of Apache compiled with VS15 (oops). Switching to python3 and VS14 now, I'll let you know if it fixes anything.

**Comment by jyn514** [comment]
Yup, that fixed it. Thanks for the help.
