### ISSUE TITLE
Can't start app with mod_wsgi-express start-server

### ISSUE THREAD

**Issue by matthewmav** [GrahamDumpleton/mod_wsgi#343]
Hello Graham,

I'm on Fedora28 Digital Ocean droplet.
The default Python is 3.6.5.
I try to deploy Flask app.
As If I install mod_wsgi with dnf/yum, I got Python 2.7 env embedded, I didn't see much other reasonable options, so I installed mod_wsgi-express.
When I started `mod_wsgi-express start-server` I get the "My web site runs on Malt Whiskey" screen.
But I couldn't figure out, how can I start my own wsgi script.
I tried a ton of thing, but no success.

For example when type `mod_wsgi-express start-server flaskapp.wsgi` (this is my testapp) I got the following error message:

```
Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:8000:1001/htdocs/'.
[wsgi:error] [pid 16657:tid 140049656882944] [remote 80.99.154.171:56656] TypeError: sequence of byte string values expected, value of type str found
[wsgi:error] [pid 16657:tid 140049690453760] [remote 80.99.154.171:56658] mod_wsgi (pid=16657): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:8000:1001/htdocs/favicon.ico'.
[wsgi:error] [pid 16657:tid 140049690453760] [remote 80.99.154.171:56658] TypeError: sequence of byte string values expected, value of type str found
```

Though flaskapp.wsgi worked with with dnf provided mod_swgi, but couldn't catch up flask.

I guess I misinterpreted something, can you help me, please: 

1. How can I start my code?
2. For config the only option is with CLI command arguments? 
3. .conf in etc in httpd section it is ignored?
4. There is something special instruction for Flask deploy?

Thank you,

George

**Comment by GrahamDumpleton** [comment]
The Apache/mod_wsgi configuration/instance started using ``mod_wsgi-express`` is separate from your system Apache configuration/instance. They run separately and need to be on different ports. If you using system Apache, you need to manually configure it. If you use ``mod_wsgi-express``, it generates a configuration for you for its separate Apache instance.

The only time you would use ``mod_wsgi-express`` if you are using the system Apache, is to run:

```
mod_wsgi-express module-config
```

to generate the Apache configuration snippet you would use to load the mod_wsgi module installed using ``pip install mod_wsgi``. You would use this if you weren't using the system mod_wsgi package (which is usually very old). You still in that case then need to manually configure the system Apache to host your WSGI application.

For more details on using ``mod_wsgi-express`` make sure you read:

* https://pypi.org/project/mod_wsgi/
* http://blog.dscpl.com.au/2015/04/introducing-modwsgi-express.html

Also consider watching:

* https://www.youtube.com/watch?v=CPz0s1CQsTE

As to how you are trying to run your your Flask application with ``start-server``, that can work if your Flask application code is setup appropriately.

As to the error:

```
TypeError: sequence of byte string values expected, value of type str found
```

that usually indicates that your WSGI application is implemented in a way that will perform very badly.

A WSGI application is meant to return a sequence/iterable of byte strings (str in 2.7, bytes in 3.X). The message says that you are return a string, instead of a sequence/iterable of strings. Now technically a string is still a sequence/iterable, but it works as being interpreted as a sequence/iterable over each individual character. Because a WSGI server is required to flush out data between each item yielded from the sequence/iterable, that means a flush is being done between each character. This will cause performance to be abysmal.
