### ISSUE TITLE
pip install mod_wsgi error!!!

### ISSUE THREAD

**Issue by ztlovemst11** [GrahamDumpleton/mod_wsgi#359]
/usr/bin/ld: /usr/local/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
    /usr/local/lib/libpython3.5m.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8yd2lrwn/mod-wsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fow21ljs/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-8yd2lrwn/mod-wsgi/

I have a lot of examples, but I still can't find a solution, it is very crashing.

**Comment by GrahamDumpleton** [comment]
See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#mixing-32-bit-and-64-bit-packages

Your Python installation must have been built with ``--enable-shared`` when running ``configure``.

**Comment by ztlovemst11** [comment]
@GrahamDumpleton ./configure --prefix=/usr/local/Python-3.5.3 --enable-shared
I have already done this, but it is useless.

**Comment by GrahamDumpleton** [comment]
You are not using a Python installation under ``/usr/local/Python-3.5.3``, but one under ``/usr/local``.

Also, if you had previously built out of the Python source code, you must run ``make distclean``, else it will use the pre-built files from the original build.

**Comment by GrahamDumpleton** [comment]
I also suggest you read:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Ignore that it talks about Docker. You potentially need other options besides just ``--enable-shared`` to match conventions for the operating system you use.

**Comment by ztlovemst11** [comment]
ok，I try it now

**Comment by ztlovemst11** [comment]
By the why,I install python3.5.3 by wget. It seems "sudo apt-get remove --purge python3.5" that this uninstall method is not suitable for me. So I can't successfully reinstall python.How should I do?

**Comment by GrahamDumpleton** [comment]
When you say installed by ``wget``, you mean you pulled down original source code and compiled yourself right. The ``apt-get`` tool is only for system packages, not one you compiled yourself.

If you issue now is that you installed things yourself from source code, and did it under ``/usr/local``, rather than its own directory, and wanted to uninstall it, then it can get tricky.

Since you aren't familiar with installing Python, I would suggest installing Python again from fresh source under ``/usr/local/python-X.Y`` (with appropriate version number), and look at what gets installed. You will then need to find same under ``/usr/local`` and remove manually.

The following are easy enough:

    /usr/local/lib/pythonX.Y
    /usr/local/include/pythonX.Y

What is harder is things put in ``/usr/local/bin`` an ``/usr/local/lib``. That is where need to compare what gets installed for separate install to know what to remove.
