### ISSUE TITLE
mod_wsgi error and 500 upon upgrade of apache 2.4.34 to 2.4.37

### ISSUE THREAD

**Issue by msapiro** [GrahamDumpleton/mod_wsgi#370]
I am running mod_wsgi in a Python 3.6 virtualenv on Ubuntu 14.04 using the system Apache.

Last night, automatic updates did

2018-11-09 03:58:53 upgrade apache2:amd64 2.4.34-1+ubuntu14.04.1+deb.sury.org+7 2.4.37-1+ubuntu14.04.1+deb.sury.org+1

Since that time any attempts to access the Mailman 3 web ui at https://mail.python.org/mm3/ return a 500 error and the apache error log (/var/log/apache2/mail.python.org-ssl_error.log) contains only

[Fri Nov 09 13:14:11.636289 2018] [wsgi:error] [pid 24946] [client 207.46.13.53:2874] Truncated or oversized response headers received from daemon process 'mailman-web': /opt/mailman/mm/bin/mailman-web.wsgi.

This is apparently due to an incompatibility between mod_wsgi and apache 2.4.37. I tried downgrading apache with

apt-get install apache2=2.4.34

but I get

E: Version '2.4.34' for 'apache2' was not found

I also tried 'apache2=2.4.34-1' and 'apache2=2.4.34-1+ubuntu14.04.1+deb.sury.org+7' which also were not found.

I upgraded mod_wsgi from 4.6.4 to 4.6.5 (the latest in pypi) in Mailman's virtualenv with pip and restarted apache2 and that didn't help.

Any advice?

**Comment by msapiro** [comment]
This is probably related to Django - installed version is 2.0.5.

when the mailman-web.wsgi file contains
```
#!/opt/mailman/mm/venv/bin/python

import sys
sys.path[0:0] = [
  '/opt/mailman/mm',
  ]

import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'mailman_web.production'

from mailman_web.wsgi import application
```
the error occurs. Note that the imported application is
```
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```
When the mailman-web.wsgi file contains
```
def application(environ, start_response):
    # emit status / headers
    status = "200 OK"
    headers = [('Content-Type', 'text/plain'), ]
    start_response(status, headers)

    content = b"""The Mailman 3 web UI is down for maintenance.

Please come back later.
"""

    return [content]
```
there is no error.

**Comment by msapiro** [comment]
I'm sorry to say that I've given up on trying to find a solution for this issue and have worked around it by switching from mod_wsgi to proxying to gunicorn.

I'll leave this open for now in case anyone has suggestions for making mod_wsgi work.

**Comment by GrahamDumpleton** [comment]
This sort of issue is usually due to one of a few reasons.

The first is that you are using a third party package for Python which has a C extension that will not work properly or crashes when used in a sub interpreter, and you have not configured mod_wsgi to use the main interpreter context in the daemon process group.

The second is that you have PHP loaded into Apache and it is linked to a different version of some shared library than what Python or some third party package for Python is linked against, and those versions of the library incompatible. Image libraries are one common type of library, but also SSL and crypto libraries.

The third is that Apache mod_ssl library has been compiled with different SSL libraries than what Python has been compiled for.

Anyway, if you have given up investigating it, not much I can do and so I will close this issue.

**Comment by msapiro** [comment]
@GrahamDumpleton thank you for your comments. I suspect the issue was the mod_ssl library, as everything was working fine for some time and the only thing that changed coincident with it breaking was the upgrade of apache2:amd64 2.4.34-1+ubuntu14.04.1+deb.sury.org+7 to 2.4.37-1+ubuntu14.04.1+deb.sury.org+1, and that included an updated /usr/lib/apache2/modules/mod_ssl.so.

Possibly recompiling the Python in the virtualenv would have solved the issue, but at this point everything is working well with Apache proxying to gunicorn, so I'm reluctant to tinker.
