### ISSUE TITLE
how to remove wsgi.py from the url?

### ISSUE THREAD

**Issue by mostafa8026** [GrahamDumpleton/mod_wsgi#380]
how to remove the wsgi.py from the URL?
![image](https://user-images.githubusercontent.com/1726531/50206943-4af96180-0382-11e9-9aaf-2c26d0091253.png)

**Comment by GrahamDumpleton** [comment]
Show your current config.

You shouldn't be setting both ``WSGIScriptAlias``, and ``AddHandler`` for ``'.py`` extension or a ``SetHandler`` either.

You should only have ``WSGIScriptAlias`` and use a URL path which matches the URL prefix that specifies.

That you are needing to use ``/wsgi.py/home`` is going to be because it is falling back to use ``AddHandler``.

**Comment by mostafa8026** [comment]
With changing the directory root to the precious folder, problem solved.
