### ISSUE TITLE
Use of GLib within mod_wsgi application causes process hanging

### ISSUE THREAD

**Issue by BrianSipos** [GrahamDumpleton/mod_wsgi#416]
This is a farther upstream report from <https://bugzilla.redhat.com/show_bug.cgi?id=1701026> because CentOS is on an older major version of `mod_wsgi`.

I am using mod_wsgi for a WSGI application which itself uses GLib for socket event handling and for D-Bus handling. Whenever a GLib worker thread is started from the GLib.MainLoop class (with the thread labeled as "gmain") the mod_wsgi cleanup activities (such as daemon-process inactivity restarting) do not properly respond to SIGINT because the GLib worker thread adds a handler for SIGINT to interrupt GLib.MainLoop running.

In the RedHat ticket, I've attached a patch to 3.4 version of `mod_wsgi` and I think a similar change could be made in the latest 4.x version to address the same issue. This patch simply uses SIGTERM instead of SIGINT for shutting down the daemon process cleanly. In current behavior sometimes SIGINT is used and sometimes SIGTERM; I'm not sure if there is a distinction between these uses or if it was significant. SIGTERM seems to do the right job in all circumstances.

**Comment by GrahamDumpleton** [comment]
`SIGTERM` is always used by the Apache parent when managing the daemon processes.

* https://apr.apache.org/docs/apr/1.6/group__apr__thread__proc.html#ga3eaec78633742e7e0cb9480a21477aff

`SIGINT` was used internally within the daemon processes, most likely originally in order to distinguish the source trigger. That difference was probably never utilised in any way.

So switching from `SIGINT` to `SIGTERM` may work in this very specific, but it concerns me that it is a band aid solution for the fact that GLib doesn't seem to play nice where it is being embedded and where something else needs to control signal handling in order to shutdown processes properly.

If GLib was more friendly to it being embedded, it would provide a way of telling it to not register a signal handler, but at the same time provide a function that can be called to perform any shutdown actions of GLib, so that can be triggered manually in some way by the shutdown of the system it is embedded in. In the case of Python, that shutdown might be triggered by a Python `atexit` callback (on the main Python interpreter context only).

Alternatively, the code using GLib should ensure that no thread created when used in an embedded system should have label "gmain". What is special about the thread with label "gmain"? That there is such a special thread and it tries to register signal handlers, means GLib probably can't be used with Python sub interpreters anyway.

I am therefore not inclined to make a change which simply changes `SIGINT` to `SIGTERM`. I might entertain a more general solution of allowing a configuration directive to be set which specifies what signal should be used for internal daemon process shutdown, with it default to existing behaviour of using `SIGINT` but which could be overridden by a user if necessary. I would need to think though about it and overall implications of whether switching to `SIGTERM`, even at the option of the user, could cause other unforeseen circumstances.

**Comment by BSipos-RKF** [comment]
I agree with your sentiment. GLib does have issues with subinterpreters because its python binding (the pygobject library) uses the `PyGILState_...` functions to synchronize some behavior.

I'm going to look up the actual GLib function which adds the signal listener, I remember seeing it when debugging earlier. It's certainly done purposefully and could potentially be patched to be optional.

**Comment by BSipos-RKF** [comment]
On my CentOS 7.4 host, with python-gobject-base-3.22.0 the culpret is the `MainLoop` object constructed with:

    # Retain classic pygobject behaviour of quitting main loops on SIGINT                                                                                                    
    def __init__(self, context=None):
        def _handler(loop):
            loop.quit()
            loop._quit_by_sigint = True
            # We handle signal deletion in __del__, return True so GLib                                                                                                      
            # doesn't do the deletion for us.                                                                                                                                
            return True

        if sys.platform != 'win32':
            # compatibility shim, keep around until we depend on glib 2.36                                                                                                   
            if hasattr(GLib, 'unix_signal_add'):
                fn = GLib.unix_signal_add
            else:
                fn = GLib.unix_signal_add_full
            self._signal_source = fn(GLib.PRIORITY_DEFAULT, signal.SIGINT, _handler, self)

So it looks like it may be possible for my application to patch-out the `__init__` function behavior on the `MainLoop` class to not add a signal handler. I haven't yet tried such a thing.

**Comment by GrahamDumpleton** [comment]
Closing as believe this is an issue that needs to be solved in GLib.
