### ISSUE TITLE
How to launch flask application from Apache

### ISSUE THREAD

**Issue by lealea401** [GrahamDumpleton/mod_wsgi#438]
I am not able to make the flask application start from Apache. The OS is SUSE SLES 11. Native python is 2.6 but I installed python 3.5 in /opt/miniconda3/bin/python3.5. With python 3 I created my venv inside the application. This is the setup. I really do not know what to do to configure correctly my application with Apache and mod_wsgi...Thanks a lot
<img width="1129" alt="Schermata 2019-06-14 alle 23 31 07" src="https://user-images.githubusercontent.com/51837829/59539194-9be6ae80-8efc-11e9-876f-f12d8815a1c8.png">

**Comment by GrahamDumpleton** [comment]
For a start, don't use IP address in `VirtualHost`. Use '*:5000'.

Also, how did you build mod_wsgi? What steps? And what config did you add into Apache to load the mod_wsgi module, you don't show that? Did you uninstall system mod_wsgi package first?

**Comment by lealea401** [comment]
Hi Graham, thanks for feedback.
This is a virtual machine trying reproducing the customer's environment SLES 11 SP2.
I installed with command "zypper install apache2-mod_wsgi-4.2.5-1.1.x86_64.rpm". There was no md_wsgi before. Once the rpm installed I used "sudo /etc/init.d/apache2 restart" and with command "apache2ctl -M" I saw that the module was loaded.

**Comment by lealea401** [comment]
Might be that I do not have installed apache2-devel and python-devel? 
I checked the availability of the packages in SUSE repo and I have them both but when I try to install apache2-devel I get error...
![Graham](https://user-images.githubusercontent.com/51837829/59555653-2c34fa00-8fb6-11e9-9069-676194193e43.PNG)

**Comment by lealea401** [comment]
Maybe the version of apache2-devel is not ok? I found the rpm apache2-devel-2.2.12-1.28.1.x86_64.rpm (http://repos.op5.com/head/sles11.3/op5-sle11-sp2-sdk-core/base/x86_64/) and I tried to install it. But in the end again I have dependencies issues...I don't know what to do...I do not trust to choose 1 or 4...
![Graham](https://user-images.githubusercontent.com/51837829/59556316-9eaad780-8fc0-11e9-9bc2-529b80f9449b.PNG)

**Comment by GrahamDumpleton** [comment]
The short answer is you cannot use system package for mod_wsgi if you want to use Anaconda Python. You must build mod_wsgi from source code yourself and configure it to use Anaconda Python. You cannot make mod_wsgi compiled for one Python version or distribution work with in a different Python version or distribution. It must be compiled for and linked with that you want to use.

So uninstall system package for mod_wsgi. Then look at:

* https://pypi.org/project/mod-wsgi/

Do a ``pip install`` of mod_wsgi and then follow instructions in "Connecting into Apache installation" of the PyPi page to work out how to have your Apache use that compiled version.

Do be aware though, you cannot use Anaconda Python if you want to use Apache ``mod_ssl`` for handling secure connections. This is because Anaconda Python is incompatible with system libraries for SSL and crypto that Apache uses. You also can't use PHP in the same Apache, because Anaconda Python provides libraries for image work that conflict with system libraries that PHP uses.

BTW, don't use screen shots to show logs and configuration. Paste in the actual test. See GitHub Markdown docs for how to do that and have it formatted properly.

**Comment by lealea401** [comment]
Thanks again, can you confirm that I do need apache2-dev installed in the system even if I use Anaconda Python? My problem is that the apache2-dev that I found in the SUSE repository is not the correct one and as I showed above, installing from rpm is complicated because of lots of dependencies missing

**Comment by GrahamDumpleton** [comment]
The requirements are started on the PyPi page.

* https://pypi.org/project/mod-wsgi/

It says that Apache dev package is required. The name of the package varies by system.

**Comment by lealea401** [comment]
Thank you!
