### ISSUE TITLE
SIGUSR1 handling when maximum-requests is set

### ISSUE THREAD

**Issue by tterrace** [GrahamDumpleton/mod_wsgi#442]
Hi Graham, quick question about a mod_wsgi process in daemon mode: Is it the expected behavior for a daemon process to continue to wait for the maximum-requests threshold even after receiving SIGUSR1?

For background, my processes are set up with a high maximum-requests because of some unfortunate memory issues that are out of my control. I was looking into using SIGUSR1 to signal a specific process to restart as soon as it reaches an idle state, but it looks like SIGUSR1 has no effect as long as the process is under its maximum-requests threshold:

https://github.com/GrahamDumpleton/mod_wsgi/blob/7f8fce232f98173e356aef83d674f321557473f8/src/server/mod_wsgi.c#L9050-L9087

I think I expected the `else if` on L9076 to just be an `if`, so the check on wsgi_daemon_graceful is independent from the maximum-requests setting, but this is my first dive into the codebase so I may be missing some other cases.

Thanks!

**Comment by GrahamDumpleton** [comment]
I'll do some checks, but that particular code isn't related to handling of `SIGUSR1`. First point of interaction for `SIGUSR1` is the signal handler:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/7f8fce232f98173e356aef83d674f321557473f8/src/server/mod_wsgi.c#L8108

This puts a marker on a socket pair which is read and dealt with at:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/7f8fce232f98173e356aef83d674f321557473f8/src/server/mod_wsgi.c#L9768

That causes immediate shutdown if not active requests, else flags that graceful shutdown (or eviction) is required.

The picking up then that shutdown should be forced is done at:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/7f8fce232f98173e356aef83d674f321557473f8/src/server/mod_wsgi.c#L9388
* https://github.com/GrahamDumpleton/mod_wsgi/blob/7f8fce232f98173e356aef83d674f321557473f8/src/server/mod_wsgi.c#L9411

There shouldn't be a connection between `SIGUSR1` and maximum requests.

One thing I would highlight, don't use the mod_wsgi package from system packages for your Linux distribution. These are quite old. It is possible that you are relying on behaviour that didn't exist in an old version, or had an issue.

When I get a chance I'll do some checks, but not sure when I will get to it.

BTW, I don't recommend ``maximum-requests`` in production systems because people often set it too low, which means that it triggers more often when the server is under high load. The forced restarts can have a detrimental affect on the server as it is causing higher load and interruptions to handling when you least want it. Perhaps look at ``restart-interval`` instead, which allows you to trigger based on time interval.

**Comment by GrahamDumpleton** [comment]
Cleaning up old issues and found this one got overlooked and never returned to it.

Reiterating what was said at the time, when sending ``SIGUSR1``, it should not wait until maximum requests had been reached but there are some messy corner cases I must not have considered at the time because I probably only considered what happened if using ``mod_wsgi-express`` where ``graceful-timeout`` has a default of 15 seconds. Even then I still missed the problem. I was probably in too much of a hurry at the time as I think I may have been on a trip away overseas at the time.

Considering the case where ``graceful-timeout`` is set to a non zero value, the issue with the code you pointed out meant that although the process would get shutdown (without needing to wait until maximum requests had been reached), it would only get shutdown when the graceful timeout had expired, and the opportunity to exit the process as soon as all active requests had completed was missed.

This meant that with ``mod_wsgi-express`` default for ``graceful-timeout``, even though all active requests may have completed in the interim, the process would still only shutdown after 15 seconds. Further, if new requests had arrived in the interim and were still running when the timeout finally occurred they would get interrupted, so you wouldn't have had a clean shutdown.

So first up I missed that there would be a delay in the process shutdown where ``graceful-timeout`` was non zero.

Next, I didn't even consider what would happen if ``graceful-timeout`` is 0, which is actually the default when you are not using ``mod_wsgi-express`` and are instead manually configuring Apache. I figured I must have assumed that graceful timeout inherited the default value for shutdown timeout if it wasn't set, but that isn't the case.

Behaviour in this case where ``graceful-timeout`` is 0, should have been that once all active requests are completed, then the process should have been shutdown. Note that there is actually no fail safe in this case, and if you had a very long running request, stuck request, or even if requests were short in duration but there was no period of inactivity when no requests were running, the process might not shutdown at all.

So actually a couple of issues here.

The first is that the problem code you pointed out meant that the expected behaviour of shutting down when any active requests had completed didn't occur if ``maximum-requests`` was set. This is why you probably saw it only shutting down the process when maximum requests was reached. In other words, you hadn't also set ``graceful-timeout`` when manually configuring Apache and it was zero, which if it was non zero would at least have resulted in a shutdown after the graceful timeout had expired.

The second is why there is no non zero graceful timeout as a default anyway.

At the time of writing the code I probably figured no graceful timeout was okay as would just mean process would be shutdown straight away, interrupting any requests. Somewhere along the line when have added maximum requests, or added the graceful timeout, I haven't considered the interaction of them all together properly and we got the behaviour you saw because of the problem code you highlighted.

End result, although much delayed from when you reported it, in mod_wsgi 4.9.0, the problem code you reported is fixed and it will correctly shutdown as soon as any active requests are completed. This still leaves problem of it never shutting down, if there is never any idle point.

For this I am going to make the default for ``graceful-timeout`` be 15 seconds, like with ``mod_wsgi-express``, since the latter has served well over time and not presented any problems. I will still allow this to be forcibly set to 0 to restore the old functionality, but since that results in the problem where process may not shutdown if never idle, that is not probably something you want anyway.

Apologies for taking so long to get back to this issue.

**Comment by t0m** [comment]
Thank you for the fix and the thorough explanation!
