### ISSUE TITLE
what is alternative for WSGIDaemonProcess in Windows?

### ISSUE THREAD

**Issue by tharun-reddy** [GrahamDumpleton/mod_wsgi#461]
I have hosted two django projects and a basic dummy static HTML site on Apache virtualhost. Each on same port but on different server name aliases. Both Django services work fine for first couple of requests and suddenly, both the web services stop. In chrome, the request will hang indefinitely. The static website keeps working even when django services are down. Main problem is, there is nothing logged in Apache logs folder. 
I am starting to think that this is occurring due to unavailability of WSGIDaemonProcess in windows for mod_wsgi. Please help.
I would like to know if anyone has successfully implemented Multiple Django sites on Windows+Apache+mod_wsgi

**Comment by GrahamDumpleton** [comment]
Read:

* http://blog.dscpl.com.au/2012/10/requests-running-in-wrong-django.html

You may if you are lucky be able to change how:

```
os.environ['DJANGO_SETTINGS_MODULE']
```

is setup.

You can have other issues because if you use third party Python modules with C extension components that don't work in sub interpreters, you can get crashes or lock ups. If both applications have such modules, you can't though force both to run in the main interpreter context to avoid it, and you don't have daemon mode which is the normal solution.

For a start read that blog post and ensure doing what it says about `DJANGO_SETTINGS_MODULE`.
