### ISSUE TITLE
No Module File wsgi_module

### ISSUE THREAD

**Issue by JulianaThayil** [GrahamDumpleton/mod_wsgi#471]
Hi. Im trying to deploy flask on WAMP server using mod_wsgi by following these tutorials
https://watchs360.wordpress.com/deploy-python-flask-wampserver/

https://www.storehubs.com/Blog/deploy-python-flask-application-apache-windows-server/

But im getting this error in Apache modules log:  **No Module File wsgi_module**
when i click on it, it says,

Sorry,
There is 'LoadModule wsgi_module modules/mod_wsgi.so' line in httpd.conf file
but there no 'mod_wsgi.so' file in apachex.y.z/modules/ directory.
Press ENTER to continue...

However i have pasted these lines in the httpd.conf file 

**LoadFile "c:/users/juliana thayil/appdata/local/programs/python/python36/python36.dll"
LoadModule wsgi_module "c:/users/juliana
thayil/appdata/local/programs/python/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/users/juliana thayil/appdata/local/programs/python/python36"**

and then Restarted Wamp server but it still shows the same error. 

Im using **WampServer 3.1.9 x64bit
python 3.6.1 x64bit
windows 10 x64bit
latest version of mod_wsgi 
and VC16**

**Comment by GrahamDumpleton** [comment]
Since you are using the `pip install` method, you should not be adding the line:

```
LoadModule wsgi_module modules/mod_wsgi.so
```

Those blog posts are not for that install method.

Include the output from running `mod_wsgi-express module-config` instead of that line.

I suspect you may have problems later anyway since you aren't using the correct Microsoft compiler. See:

* https://wiki.python.org/moin/WindowsCompilers

for what compiler you are mean to use with each Python version.

**Comment by JulianaThayil** [comment]
Its working now. Thank you so much for your help.
