### ISSUE TITLE
[wsgi:error] [pid 27526] Some text here

### ISSUE THREAD

**Issue by Velu-Narasimman** [GrahamDumpleton/mod_wsgi#475]
Our application is a python webapp (Trac - framework based app). We have integrated Django as well. For some reason in our app at some places we have used "print" statements. Which are logged into our apache error.log file.

`[wsgi:error] [pid 27526] LEVEL004`

 In the above log line the text "LEVEL004" is some string value about the logged in user. We have similar such lines not more than 10 lines.  But they are found as "error" statements by apache.

 Why is this? How could this affect our system? we are facing "performance" issues with our app. In what way this is related to  performance?
    For your information, we use python2.7, apache 2.4.39, mod_wsgi 4.5.2

**Comment by GrahamDumpleton** [comment]
If you are logging stuff via the Python logging module at any level, but have configured the logging module to send to `stdout` or `stderr` then it will appear in the Apache error log. In doing that, no matter what the message was logged at with the Python logging module, it will be flagged as `wsgi:error` by Apache. This is because there is no way to map to Apache log levels so it just all go in as `error` whatever it is. This should make no difference to performance.

Any performance issue, even if it can be attributed to the Apache setup, is because you are doing the following:

* Using embedded mode.

* Using a single threaded MPM configuration (eg., prefork).

* Setting way too many threads if using multithreading. Even in daemon mode of mod_wsgi, 3-5 threads is generally best and going higher is a bad idea if a CPU intensive application. Use multiple processes in daemon mode instead.

* Not disabling embedded mode using `WSGIRestrictEmbedded On`.

There can be various other reasons as well, but without knowing how you are setting up Apache and mod_wsgi, it is impossible to tell.

As a start, perhaps at least watch:

* https://www.youtube.com/watch?v=k6Erh7oHvns

* https://www.youtube.com/watch?v=H6Q3l11fjU0
