### ISSUE TITLE
Ubuntu 18.04 Truncated or oversized response headers received from daemon process (ok in CentOS7)

### ISSUE THREAD

**Issue by genghisken** [GrahamDumpleton/mod_wsgi#480]
I realise that this is possibly related to Issue #374, but none of those suggestions work here.

I have an Ubuntu 18.04.2 installation, along with Python 3.7 (Anaconda).

The webserver is setup to serve SSL only.  The site works OK, form submission works, but when we try to do any kind of authentication, we get the "truncated or oversized headers" issue.  Apache drops a core.  Examination of the core seems to indicate a problem with libcrypto (see below) but this might be a red herring.

Relevant config is below.  We have an almost identical configuration (using Anaconda python) on CentOS7 and all works fine (and we didn't need the WSGIApplicationGroup %{GLOBAL} setting).  But for many hours, we've been unable to get this working on Ubuntu.  Tried with and without GLOBAL setting to no avail.  Uninstalled & reinstalled (e.g. with --compile --no-cache-dir) django, numpy, mod_wsgi. Removed numpy altogether.  Still no joy.  Any suggestions are very welcome!  Relevant logs and config are below!

Thanks in advance!

Ken

error.log

```
[Sun Oct 27 16:56:08.319490 2019] [core:notice] [pid 6061] AH00051: child pid 6064 exit signal Segmentation fault (11), possible coredump in /var/cache/apache2
```

myapp-error.log

```
[Sun Oct 27 16:56:07.065283 2019] [wsgi:error] [pid 6065] [client 146.198.222.243:63605] Truncated or oversized response headers received from daemon process 'myapp.roe.ac.uk': /home/ubuntu/lasair/src/lasair-webapp/lasair/lasair/wsgi.py, referer: https://myapp.roe.ac.uk/accounts/login/
```

wsgi.py

```
import os
from django.core.wsgi import get_wsgi_application
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "lasair.settings")
application = get_wsgi_application()
```

/etc/apache2/mods-enabled/wsgi.load

```
LoadModule wsgi_module "/home/ubuntu/anaconda3/envs/lasair/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
WSGIPythonHome "/home/ubuntu/anaconda3/envs/lasair"
```

Apache config

```
<IfModule mod_ssl.c>
<VirtualHost *:443>

        ServerName myapp.roe.ac.uk
        DocumentRoot /home/ubuntu/lasair/

        WSGIScriptAlias / /home/ubuntu/lasair/src/lasair-webapp/lasair/lasair/wsgi.py process-group=myapp.roe.ac.uk
        WSGIDaemonProcess myapp.roe.ac.uk processes=1 threads=1 python-path=/home/ubuntu/lasair/src/lasair-webapp/lasair:/home/ubuntu/lasair/src/alert_stream_ztf:/home/ubuntu/anaconda3/envs/lasair/lib/python3.7/site-packages
        WSGIProcessGroup myapp.roe.ac.uk
        WSGIApplicationGroup %{GLOBAL}

        TimeOut 800

        <Directory /home/ubuntu/lasair/src/lasair-webapp/lasair/lasair>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        Alias /lasair/static /home/ubuntu/lasair/src/lasair-webapp/lasair/lasair/static
        <Directory /home/ubuntu/lasair/src/lasair-webapp/lasair/lasair/static>
                Options FollowSymLinks
                AllowOverride None
                Require all granted
        </Directory>

    #### Error Logs ####
        ErrorLog /var/log/apache2/lasair-error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel debug

        CustomLog /var/log/apache2/lasair-access.log combined
        ServerSignature On
        SSLEngine On

        SSLCertificateFile /etc/letsencrypt/live/myapp.roe.ac.uk/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/myapp.roe.ac.uk/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
 
```

gdb output.

```
Core was generated by `/usr/sbin/apache2 -k start'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7142a16055 in EVP_MD_CTX_clear_flags () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

**Comment by GrahamDumpleton** [comment]
As referenced in one of the comments of the linked issue, Anaconda Python ships with its own crypto libraries. These conflict with the system libraries. This means that if you have `mod_ssl` in Apache enabled and being used, as soon as you do anything in Python which uses SSL or crypto, the process will crash. This is because Apache had preloaded the system crypto libraries and the Anaconda versions can't be loaded and are never used. As a result, the Python modules are expecting a different version of the libraries, and because the version they were compiled for is incompatible, the Python module code in the C extension crashes.

In short, Anaconda Python cannot be used in any embedded system (such as Apache/mod_wsgi), where the application embedding it is compiled against different versions of any shared libraries (such as crypto and image libraries), that Anaconda Python bundles its own copies of.

Your only options are to not use Anaconda Python but system Python package or self built Python using original CPython source code.

The only way you would be able to use Anaconda Python would be to run a separate Apache instance which doesn't have `mod_ssl` enabled, and proxy to it from a front end Apache which handles secure connections in setup. One way of easily doing this is to use `mod_wsgi-express` to run the separate instance to which you would proxy requests.

**Comment by genghisken** [comment]
Hi Graham, Many thanks for your extensive response, but I have two issues with it:
1. We've been using CentOS7/Anaconda/Apache/SSL for years with no issues at all.
2. We actually have another Ubuntu 18.04.2/Anaconda/Apache/SSL instance (which I forgot about) that (infuriatingly) DOES work!

We saw the comments about Anaconda vs system python, but we ruled this out as the source of our problems because we are already running with this combination elsewhere.

All of our code is for various scientific apps (astronomy) and we rely extensively on Anaconda for this. Building from scratch isn't an option for us.  Agreed we could try and operate with mod-wsgi-express, but my main beef is the inconsistency in the above.

**Comment by GrahamDumpleton** [comment]
You would have to look at what the exact versions are of the system crypto libraries packages, the version of Anaconda Python used, and possibly the version of Apache used. Are they different on the various platforms or are you sure they are exactly the same.

Anaconda Python has caused this by starting to bundle their own crypto libraries at some point, with whatever version they are bundling being different to the system one. There isn't a lot I can do about what Anaconda Python is now doing.

Only other thing I can suggest is ensuring that your Python virtual environment, along with any installed Python packages, such as mod_wsgi, are definitely build for the current Apache and Anaconda Python versions, and that you haven't done an upgrade of Apache system package or Anaconda Python packages since the virtual environment was first created.

**Comment by genghisken** [comment]
Many thanks for your message.  Agreed that it's probably cleaner and safer to use mod_wsgi-express.

However, I was able to resolve the Anaconda / SSL issue by specifying the correct version of openssl when creating my Anaconda environment.  In this case it was:

```conda create -n test python=3.7 openssl=1.1.1```

And when installing mod_wsgi again, running:

```pip install mod_wsgi --compile --no-cache-dir```

(which makes sure that it's not picking up a previously compiled shared library)

Then edit wsgi.load in /etc/apache2/mods-enabled to force it to point at the new shared library.  Now I'm able to authenticate because openssl 1.1.1 uses the same version of libcrpto.so.1.1 as the system library.

Feel free to close this issue, unless you have any more comments!

**Comment by GrahamDumpleton** [comment]
Closing this on assumption all is good now.
