### ISSUE TITLE
django python service deploy on Apache2,always occurs this

### ISSUE THREAD

**Issue by iver3on** [GrahamDumpleton/mod_wsgi#485]
![image](https://user-images.githubusercontent.com/12184988/68575552-44e30680-04a7-11ea-9535-ab7cc17cd5bc.png)
IOError failed to write data

**Comment by GrahamDumpleton** [comment]
Always occurs, as in every single request you receive fails, or you just see it occasionally?

This is quite normal, especially when using embedded mode, instead of the recommended daemon mode of mod_wsgi. It can be caused when the HTTP client making the request closes the connection before all of the response has been written back. It can occur especially when dealing with slow or mobile HTTP clients.
