### ISSUE TITLE
by entering command mod_wsgi-express module-config i am getting None in LoadModule

### ISSUE THREAD

**Issue by karthikellur2020** [GrahamDumpleton/mod_wsgi#497]
C:\receiverapp>mod_wsgi-express module-config
LoadModule wsgi_module "C:/Python27/lib/site-packages/mod_wsgi/server/mod_wsgiNone"
WSGIPythonHome "C:/Python27"

Why is this?

**Comment by GrahamDumpleton** [comment]
Because installations of Python 2.7 for some people seem to be mucked up in some way and no one has ever wanted to debug why for me, so it has never been fixed.

Look in that directory and work out whether the `mod_wsgi.???` file has a `.pyd` or `.pyo` extension and change `None` to be what the actual extension is.

It is highly recommended though to use Python 3.6 or later. Python 2.7 is usually very hard to get working any more as not possible to get Apache compiled with the correct MS C compiler.

**Comment by karthikellur2020** [comment]
Hi Graham,

There is one file : mod_wsgi.pyd in the path: C:\Python27\Lib\site-packages\mod_wsgi\server.
So, I can use C:/Python27/lib/site-packages/mod_wsgi/server/mod_wsgi\mod_wsgi.pyd

Is this what you are suggesting?

Regards
Karthik

**Comment by GrahamDumpleton** [comment]
Yes, but don't use backslashes. Use all forward slashes for paths in the Apache config file otherwise it may interpret it wrongly.

**Comment by GrahamDumpleton** [comment]
Actually no, you added an extra path element you shouldn't have. Use:

```
LoadModule wsgi_module "C:/Python27/lib/site-packages/mod_wsgi/server/mod_wsgi.pyd"
```

**Comment by karthikellur2020** [comment]
Hi Graham,

Tried the above suggestion. 
The Apache service named  reported the following error:
>>> httpd.exe: Syntax error on line 547 of C:/Apache24/conf/httpd.conf: Cannot load C:/Python27/lib/site-packages/mod_wsgi/server/mod_wsgi.pyd into server: The specified module could not be found.     .

Apache is unable to load the mod_wsgi.pyd, even though it exists at the location.

**Comment by GrahamDumpleton** [comment]
Which is why I suggested you use Python 3.6 or later.

Various conditions need to be met to make it all work and these days it is basically impossible to do that with Python 2.7.

The conditions that need to be satisfied are:

* You need to use all 32 bit or all 64 bit for Apache, Python and MS C compiler.
* The MS C compiler must be the same version as Python was compiled for. See https://wiki.python.org/moin/WindowsCompilers
* The Apache needs to be compiled with same compiler ABI as Python. This is basically impossible to satisfy now as a suitable Apache binary isn't available. If they don't match, chances are it will not work.

So your chances of getting Python 2.7 to work was very slim to start with. That error message is actually misleading, and the problem is that one of the conditions above is usually not met.

Also be aware that Python 2.7 has reached end of life and is unsupported come the start of next year. You shouldn't be using it for new projects. See https://pythonclock.org/

So would strongly recommend using Python 3.6 or later, not Python 2.7, as highly unlikely you will be able to get Python 2.7 working.

**Comment by karthikellur2020** [comment]
Sure Graham, will use Python 3.6 or later versions.
Thanks for your prompt replies :)
