### ISSUE TITLE
HTTPS website

### ISSUE THREAD

**Issue by jayvdb** [GrahamDumpleton/mod_wsgi#518]
Hi, I noticed that https://www.modwsgi.org (https) times out, while http://www.modwsgi.org redirects to RTD.  Is there something that can be done to make https reject connections or also redirect it to RTD.  IIRC, RTD supported HTTPS redirects.

**Comment by GrahamDumpleton** [comment]
From memory, the ``www.modwsgi.org`` redirection is handled in AWS somehow by an S3 bucket. Unless it somehow supports being automated in some way so that letsencrypt can be used to set a certificate, probably out of luck with the way it is done now.

The other alternative is having ``readthedocs.org`` handle the custom domain name. It looks like it may now provide a way of being able to generate a certificate for you that is valid, but not sure if I am reading it right though.

* https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-ssl

**Comment by GrahamDumpleton** [comment]
I believe this should be sorted now. I am using ReadTheDocs to handle the custom domain and certificate.
