### ISSUE TITLE
mod_wsgi not finding django (No module named 'django') installed via pip3 install --user django

### ISSUE THREAD

**Issue by ajsicek** [GrahamDumpleton/mod_wsgi#536]
Running debian apache, mod wsgi and django (installed via pip3 install --user django )
Apache/2.4.38 (Debian) mod_wsgi/4.6.5 Python/3.7
Django-admin runserver works as expected, but deployment via mod_wsgi shows 500 internal server error and No module named 'django' in error log.
After spending hours to find a solution I finally stumbled on [your post](https://github.com/GrahamDumpleton/mod_wsgi/issues/498#issuecomment-561088328) saying .
Do I get it right, that I can not make it work in this setup?
If yes It would be great to have that written somewhere maybe in Django deployment with mod_wsgi documentation. So people do know from the very start.
What is the proposed solution? different way of deploying (which)? different way of installing django? If I get it right sudo pip install django will not help either? apt-get install django is only version 2.2

**Comment by GrahamDumpleton** [comment]
The first and preferred option is NOT to use the per user site packages option (``pip install --user``). This will not be found when running your application as a different user, such as occurs when running as a system daemon process using Apache/mod_wsgi.

A per user site packages directory also has various problems if using a system Python installation, because the system may want to install its own system packages for Python packages that will conflict with what you want to installed. For details see "http://blog.dscpl.com.au/2016/01/python-virtual-environments-and-docker.html". Ignore that is says docker, all the issues still apply in a normal system.

Instead, follow best practice and use a full Python virtual environment. Because on some systems your home user directory is not readable by others, it is recommended to place the virtual environment and all your project code somewhere outside of the home directory with its restrictive permissions.

If for some reason you don't want to adopt best practice and use a virtual environment, and you are using embedded mode of mod_wsgi then you can use:

```
WSGIPythonPath /home/user/.local/lib/pythonX.Y/site-packages
```

Replace ``X.Y`` with the actual Python version. Adjust the path as necessary per your system setup, as some systems can use a different directory.

If using recommended daemon mode of mod_wsgi, you can use the following option to ``WSGIDaemonProcess`` directive.

```
python-path=/home/user/.local/lib/pythonX.Y/site-packages
```

These will allow packages to be found in the per user site packages directory.

Neither of these will work though if your home directory isn't readable to others. It is not recommended to open up your home directory so it is still preferable to use a virtual environment with it and your project code outside of the home directory.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
