### ISSUE TITLE
Truncated or oversized response headers received from daemon process (Django/Ubuntu/SSL/Python 3.6)

### ISSUE THREAD

**Issue by ialbd** [GrahamDumpleton/mod_wsgi#541]
Hi there,

So I am getting this error ever since I tried putting SSL (Lets Encrypt) on my Django installation. Everything works fine until enabling SSL.

(Pardon my formatting)

Error Log (modified the domain names for client privacy):

Stack:
Python 3.6.9
Ubuntu 18.04 (LTS)
Apache 2.4.29
Django 2.1.10
Mod wsgi 4.7.1

```[wsgi:error] [pid 17955:tid 139807862765312] [client 99.240.134.237:51258] Truncated or oversized response headers received from daemon process 'xyz.com': /home/ubuntu/xyz-web-erp/xyzWebErp/wsgi.py, referer: https://www.xyz.com/```

Here is my Apache SSL config file:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName www.xyz.com
        ServerAlias xyz.com
        ServerAdmin webmaster@localhost

        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        LogLevel debug

        Alias /static /home/ubuntu/xyz-web-erp/static
        <Directory /home/ubuntu/xyz-web-erp/static>
                Require all granted
        </Directory>

        Alias /media /home/ubuntu/xyz-web-erp/media
        <Directory /home/ubuntu/xyz-web-erp/media>
                Require all granted
        </Directory>

        <Directory /home/ubuntu/xyz-web-erp>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        WSGIApplicationGroup %{GLOBAL}
        WSGIDaemonProcess xyz.com python-path=/home/ubuntu/xyz-web-erp python-home=/home/ubuntu/xyz-web-erp/venv
        WSGIProcessGroup xyz.com
        WSGIScriptAlias / /home/ubuntu/xyz-web-erp/xyzWebErp/wsgi.py

        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/www.xyz.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/www.xyz.com/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

After reading several other threads on this, I have removed libapache2-mod-wsgi-py3 and installed mod_wsgi using pip.

So added the following in my apache2.conf to load mod wsgi in Apache:

LoadModule wsgi_module "/home/ubuntu/xyz-web-erp/venv/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/home/ubuntu/xyz-web-erp/venv"

But still the same error. Its perhaps something to do with mod_ssl as @GrahamDumpleton pointed out in some threads.

Any idea how to solve this. Stuck on this for some time now. Can share more info (requirement.txt from Django etc, if needed). Thanks in advance.

**Comment by GrahamDumpleton** [comment]
If you look, you may find in the main Apache error log messages indicating that the daemon process has crashed with a segmentation fault.

If this is the case, it usually indicates one of two things.

The first is that you are using Anaconda Python and not the system Python. Anaconda Python is a problem because it ships SSL and crypto libraries that are not ABI compatible with the system version of those libraries. This causes a process to crash as the system versions of those libraries would have been loaded by Apache mod_ssl first. Thus any Python package using SSL would crash because of the incompatibility.

The second is that you are installing a binary wheel version of a Python package and that wheel was compiled against an incompatible SSL library. One such known package is ``psycopg2-binary``. In this case you should install ``psycopg2`` package instead, which means it is compiled from source code on your system when being installed and so uses the system versions of the SSL library. There are possibly other binary wheels that have this issue, but ``psycopg2-binary`` is the one that seems to cause all the problems.

If neither of these seem to apply, then you will need to work out where the daemon process is crashing. For instructions on how you may be able to do that, see:

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb

Unfortunately this may not help as many packages/libraries are stripped and don't have symbols in them, so you can bet a meaningful stack trace.

**Comment by ialbd** [comment]
Thanks for the tips Graham, it was indeed the psycopg2-binary. Will keep a close eye on any binary packages in the future.

Switched to the non binary psycopg2 package, and also updated to 2.8.4 (latest) as the previous (pre 2.8) version has its own issues compiling. There was also a pg_config error trying to compile the psycopg2 source, that was solved with a `sudo apt-get install libpq-dev`

Also I am back to using `libapache2-mod-wsgi-py3` so dont need to install mod wsgi through pip and load it in Apache manually.

That was one heck of a ride trying to get this to work (especially someone new to the whole wsgi application), but simply amazed by the support you provided !!! closing this issue now... Thank you.

Hope this helps the next person running into this...
