### ISSUE TITLE
WSGIPythonPath not working on Windows 10 + necessity to manually load python dll

### ISSUE THREAD

**Issue by alexorex** [GrahamDumpleton/mod_wsgi#561]
Found out through error log: WSGIPythonHome was exactly how it was set up in httpd.conf, but WSGIPythonPath was 'not set'. The only way was to set the variable with Windows tools.
Can be bypassed with sys.path inside python **only** if WSGIPythonHome is omitted (as then wsgy.py actually starts, missing some libs).
Installed mod_wsgi with pip on Windows 10 x64.

Also not sure if it's a bug, but to load the 'mod_wsgi' (instruction found on some site) first I have to load a dll:
`LoadFile "P:\Python38\python38.dll"`
Otherwise the error is:
`Cannot load .../mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd into server: The specified module could not be found.`
Is it the intended way?

**Comment by GrahamDumpleton** [comment]
The ``LoadFile`` directive can be required when Python is installed in a strange place, such as not the default drive.

As to ``WSGIPythonHome``, this no longer works if using virtual environment and there is no known fix for mod_wsgi itself yet. It has never worked for ``python -m venv``, and has stopped working with ``virtualenv`` 20.0 due to changes the made.

What you will need to do is in the WSGI script file, add at the very start:

```
import site
site.addsitedir('P:/some/path/to/python3.8/Lib/site-packages')
```

You will need to work out what actual path is. Should be what ``sys.prefix`` is for the virtual environment, with sub path added which targets the ``site-packages`` directory within it.

**Comment by alexorex** [comment]
I tried this again on clean system without python installation, just folder + **venv**: `WSGIPythonHome` had to point to main python distribution folder + `wsgi.py` had to contain path or site modificatioins to locate all modules and packages (also those in **venv**). This way allows to avoid setting OS-level environment vars.
Apparently, first **mod_wsgi** itself needs to locate python distro and only **after** that actual python interpreter is started, so using at least `WSGIPythonHome` is necessary and setting anything inside python scripts or **.pth**, **sitecustomize** files or other standard setup for this first stage is meaningless.
