### ISSUE TITLE
Fatal Python error: initfsencoding: unable to load the file system codec ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by Shinsina** [GrahamDumpleton/mod_wsgi#563]
I get the following error when attempting to launch my apache server:
[Mon Apr 20 01:28:35.830988 2020] [mpm_winnt:notice] [pid 15100:tid 576] AH00455: Apache/2.4.43 (Win64) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Mon Apr 20 01:28:35.830988 2020] [mpm_winnt:notice] [pid 15100:tid 576] AH00456: Apache Lounge VS16 Server built: Mar 31 2020 16:01:02
[Mon Apr 20 01:28:35.830988 2020] [core:notice] [pid 15100:tid 576] AH00094: Command line: 'httpd.exe -d C:/Apache24'
[Mon Apr 20 01:28:35.846615 2020] [mpm_winnt:notice] [pid 15100:tid 576] AH00418: Parent: Created child process 3084
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000023ac (most recent call first):
[Mon Apr 20 01:28:37.572564 2020] [mpm_winnt:crit] [pid 15100:tid 576] AH00419: master_main: create child process failed. Exiting.

I have tried the solution of removing the PythonHome line but that only gives me the default Apache "it works!" page. I've attached a screenshot of my folder structure, the contents of my httpd.conf file and settings.py file in hopes that maybe a potential solution may arise. Thank you
[httpd.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/4501597/httpd.txt)
Settings.py:
[settings.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/4501614/settings.txt)

![OnPaste 20200420-013712](https://user-images.githubusercontent.com/46794001/79721307-c2594100-82a7-11ea-9a57-b2e3d7d7bce0.png)

**Comment by GrahamDumpleton** [comment]
For now, replace:

```
WSGIPythonHome "C:/some/path/python/env"
```

with:

```
WSGIPythonPath "C:/some/path/python/env/Lib/site-packages"
```

Change path as necessary such that identifies the ``site-packages`` directory in the virtual environment.

If you were already setting ``WSGIPythonPath``, add that path afterwards.

```
WSGIPythonPath "C:/some/path/python/env/Lib/site-packages;C:/some/other/path"
```

This is all because a problem in Python itself. For some details see:

https://github.com/GrahamDumpleton/mod_wsgi/issues/559

Might have a solution to the problem now, but just need to find time to fix and test it.

**Comment by Shinsina** [comment]
So currently the additions to httd.conf are the following:
<Directory "C:/Users/CollinsJacob/Python Scripts/Personal Projects/Living Log/living_log/">
<Files wsgi.py>
    #AllowOverride none
    Require all granted
    </Files>
</Directory>

(Which is added at the start of the directory blocks before DocumentRoot)

<IfModule wsgi_module>
WSGIScriptAlias living_log "c:/users/collinsjacob/python scripts/personal projects/living log/living_log/wsgi.py" 
WSGIPythonPath "C:/Users/CollinsJacob/Python Scripts/Personal Projects/Living Log/ll_env/Lib/site-packages""C:/Users/CollinsJacob/Python Scripts/Personal Projects/Living Log"
</IfModule>

(At the very end of the file)

Currently with the two pathes on WSGIPythonPath it will not compile however if I remove one of them I get the same result of getting the default Apache webpage ("It works!"), this result is the same if i remove any or all the other WSGI variables (WSGIScriptAlias), is there something additional I am missing or misunderstanding here?

**Comment by GrahamDumpleton** [comment]
In the example I gave you, there was a semi colon between the two paths given as argument to ``WSGIPythonPath``. You can't just put two quoted strings together, nor use spaces between the two paths so there are multiple arguments.

Also, I would high discourage putting stuff in directories with spaces in them, that can cause problems with Python.

**Comment by mojitonoproblem** [comment]
I am getting the same error message in Debian 10, **apache2-bin/stable,stable,now 2.4.38-3+deb10u4 amd64** and **libapache2-mod-wsgi-py3/stable,now 4.6.5-1 amd64**. I tried every tweak I could but still cannot figure out how to get rid of this problem.
Is it valid to report here or should I open a new issue?
In case yes, I cannot even attempt to debug mod_wsgi as stated in the Check your installation chapter, because it cannot start Python itself. However I am working with a conda virtual environment, but setting the wrong paths within de wsgi.py file, obviously it never reaches to that point.

How can I help/do? Thank you!

**Comment by mojitonoproblem** [comment]
From all of the Python installations in the operating system, i can import encodings successfully, btw.

**Comment by mojitonoproblem** [comment]
Nevermind. Sorry. As always, right after posting the issue, I found the solution.
I've re read your manual and installed mod_wsgi from pip. That mod_wsgixxyy.so worked like a charm. Thank you

**Comment by GrahamDumpleton** [comment]
Closing issue as presumed resolved long ago.
