### ISSUE TITLE
Apache + mod_wsgi (Clean Python 2.7.5) = Docker/Container1 --- Python 2.7.5 = Docker/Container2

### ISSUE THREAD

**Issue by gciria** [GrahamDumpleton/mod_wsgi#572]
Hi Graham,

Is this scenario possible?

Apache + mod_wsgi (Clean Python 2.7.5) = Docker/Container1
Python 2.7.5 + virtualenv + application.wsgi = Docker/Container2

The two containers, view the same directory, where is the application: /test/ (virtualenv)

For example Apache .conf (Container1)
WSGIScriptAlias /test "/test/application.wsgi"               < Container2
WSGIPythonHome  /test                                               < Container2
WSGIPythonPath  /test                                                 < Container2

If it doesn't work. I need to find some way to isolate Apache + MOD_WSGI from my Python.
Can you give me a way?

**Comment by GrahamDumpleton** [comment]
This sounds a bit like an unrealistic condition is being enforced on you as a result of someone deciding to run a security threat tool on your applications where the people who created the tool or who are working out how to act on the results don't understand how web servers work and understand Apache security model and how mod_wsgi works with that. :-(

The closest you will get to this arrangement is to use a front end web server which all it does is proxy to a second Apache with mod_wsgi. The second Apache would only listen on 127.0.0.1 so it is only accessible from the container it is a side car too, and not from outside of the container. The containers wouldn't share a file system though as makes no sense to as the front end configuration is quite separate.

So there still is Apache + mod_wsgi + Python code, it just isn't in the container running the front facing web server that accepts requests from the internet.

This sort of arrangement seems like a strange requirement if doing it only for perceived security issues and especially if needing multiple instances because in that case you would already have had a front end web server acting as load balancer across all the instances. So it just adds an unnecessary hop if introduced behind that load balancer that isn't going to add any extra security since the load balancer would be first. It also does nothing to protect you from security problems in your own application code.

What is often silly about these sorts of conversations is that people try and contort themselves by designing such architectures, but still don't address the more significant security issues, such as not running the image as the root user (dropping from root to the Apache user is still running the image as root), disabling ability to do su/sudo, and dropping Linux capabilities so it isn't possible to change uid/gid so could become root.

So really have to ask, why are you trying to architect things this way? What is the real problem you are trying to address? You would be better off explaining the actual problem, rather than asking how to do what you think may be a solution to whatever the problem is. If know what the problem is then can better guide you to what is a good solution or even correct misconceptions of there even being a problem.

That all said, for using ``mod_wsgi-express`` behind Apache as a proxy see:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
