### ISSUE TITLE
Uses python3.6 not python3.8 as in venv

### ISSUE THREAD

**Issue by StefanB123** [GrahamDumpleton/mod_wsgi#588]
I tried it with and without an virtual env but it always goes back to python3.6.9, even if it's not installed in the current virtual environment.
Couldn't find a way to change this. Problematic since pip3 installs modules into the newest python3 instance.

Note: I specified the path to the venv and the python interpreter is there python3.8.0

**Comment by GrahamDumpleton** [comment]
You are missing a lot of context in this so hard to understand what you are saying your problem is.

Do be aware that mod_wsgi is compiled for a specific Python version. If you have a system package for mod_wsgi, it will be installed for the system Python version, which in your case sounds like it may be Python 3.6.9. You cannot then force that to use a Python virtual environment for a different Python version.

You can check what version of Python mod_wsgi is compiled for, by finding the ``mod_wsgi.so`` file in the Apache installations modules directory and running ``ldd`` on it. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-shared-library

What shared library for Python is it linking with.

If the system mod_wsgi package is wrong Python version you need to uninstall the system package for mod_wsgi, install mod_wsgi yourself from source code, see:

* https://pypi.org/project/mod-wsgi/

and then configure Apache to load that version of mod_wsgi.

**Comment by StefanB123** [comment]
It makes sense that it runs on the python version it was compiled with, but it doesn't make sense that it points (via sys.executable) to the file which runs python3.8 not python3.6.9. (Which is very confusing since you find this not clearly written anywhere). 

But anyway woulnd't it be possible to let it run on a different python3 version then it was compiled with?

**Comment by GrahamDumpleton** [comment]
No it is not possible to make it work with a virtual environment created with a different version of Python than mod_wsgi is compiled for. The mod_wsgi module is written in C code and explicitly links the library for the version of Python it is compiled for. It isn't pure Python code that could work with multiple Python versions.

The documentation mentions it must be the same version in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#virtual-environment-and-python-version

As to ``sys.executable``, what are you doing to make the claim it is showing a different version?

The only check you should use to determine which version the compiled mod_wsgi is using is:

* https://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-installation-in-use

**Comment by StefanB123** [comment]
Installed it via pip (previously package for ubuntu (using ubuntu 18.04 as vm)) works now fine.
Only django fails now but that's not the problem with wsgi^^

Nonetheless would it be possible to at least print an Error or an warning if the compiled version is different then the used? (Would have helped me a lot^^)

**Comment by GrahamDumpleton** [comment]
That used to be possible a long time ago, but then the Python C runtime internals made it impossible, as the version of Python runtime can no longer be determined until after the Python interpreter has been initialised, but it can't be initialised because of the mismatch.

**Comment by StefanB123** [comment]
Ohhh okay i understand.
Thanks for the help!
