### ISSUE TITLE
WSGI process and thread flags "wsgi.multiprocess" and "wsgi.multithread" are incorrect

### ISSUE THREAD

**Issue by hoylen** [GrahamDumpleton/mod_wsgi#598]
_wsgi.multithread_ is always true, regardless of whether Apache is using multiple threads or not.

_wsgi.multiprocess_ sometimes produces unexpected values. I haven't worked out how to make it reproducible.

The [documentation](https://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html#wsgi-process-thread-flags) says what those values "should" be. While "should" is not a "must", which gives leeway for the values to be different, it would be better if it always produced the expected values.

## Expected result

`wsgi.multithread` to be True when Apache is configured to allow up to 2 or more threads per process, and False when it is configured to have only one thread per child process.

`wsgi.multiprocess` to be True when Apache is configured to allow up to 2 or more child processes, and False when it is configured to only have one child process.

## Actual results

wsgi.multithread is always true - even when Apache has been configured with `ThreadsPerChild=1`.

wsgi.multithread sometimes produces unexpected values. I haven't 

## Problem and potential solution

I think the problem is here:

https://github.com/GrahamDumpleton/mod_wsgi/blob/0dce98f4613f7a0673e15510d73e583f89a1a5ce/src/server/mod_wsgi.c#L13302-L13303

Since "AP_MPMQ_IS_THREADED" is [defined](https://ci.apache.org/projects/httpd/trunk/doxygen/group__qcodes.html) as "MPM can do threading" - not if it is currently configured to use that capability. That is, while Apache has been compiled with a MPM that allows multiple threads per process, it might not currently be configured to use more than one thread per process.

The code to calculate "wsgi.multiprocess" is on the right track. It checks if the "MPM can do forking" and (if it can) also checks how many it is currently configured to use. Both capability and if that capability is currently in use, determines whether _wsgi.multiprocess_ is true or not.

https://github.com/GrahamDumpleton/mod_wsgi/blob/0dce98f4613f7a0673e15510d73e583f89a1a5ce/src/server/mod_wsgi.c#L13305-L13309

However, this has a bug too. It is checking the value of "AP_MPMQ_MAX_DAEMONS", which is defined as "Max # of daemons used so far" - a number that can change over time as Apache forks and kills off child processes. For example, if Apache has just started up and has forked only one child process, wsgi.multiprocess will be False - even though multiple child process will be forked later on when the load increases; subsequent requests will get True instead.

For _wsgi.multiprocess_, the correct value to be checking is "AP_MPMQ_MAX_DAEMONS" which is defined as "Max # of daemons by config".

For _wsgi.multithread_, (in addition to checking "AP_MPMQ_IS_THREADED") it should also check "AP_MPMQ_MAX_THREADS", which is defined as "# of threads/child by config".

The [ap_mpm_query](https://ci.apache.org/projects/httpd/trunk/doxygen/group__mpmq.html#ga8a659f8ba54765a86186b39b74d60bdb) function can return an error. It would be good to check if it returned APR_SUCCESS before using the result.

_The above is only based on reading the documentation, which might be incorrect, so testing is required._

**Comment by GrahamDumpleton** [comment]
Delayed response, but trying to clear out old issues.

As to ``wsgi.multiprocess``, your observation seems contradictory. You said:

> It is checking the value of "AP_MPMQ_MAX_DAEMONS", which is defined as "Max # of daemons used so far"

and then you said:

> the correct value to be checking is "AP_MPMQ_MAX_DAEMONS" which is defined as "Max # of daemons by config".

You reference the same constant value in both. In the first you probably meant ``AP_MPMQ_MAX_DAEMON_USED``, but that is not what is used anyway.

So ``wsgi.multiprocess`` is correct as far as I can tell.

As to ``wsgi.multithread`` and how it it set, I don't recollect why was always set if MPM supported multiple threads, regardless of number of threads per child per configured. May have been because in practice no one ever set number of threads per child to one anyway with multithreaded MPMs and so didn't see it as important. Anyway, as far as I remember I don't think the issue was was that Apache 2.0 didn't report number threads correctly or that it was otherwise buggy.

With ``mod_wsgi-express`` since 4.8.0 allowing one to provide ``--embedded-mode`` and thus not always use daemon mode, and where it is actually possible to say ``--threads=1` and have it work in a sane way since ``mod_wsgi-express`` overrides all configuration and uses something that will actually work properly for Python applications in embedded mode, it is probably reasonable to have this be accurate now. So have fixed up value of ``wsgi.multithread`` for inclusion in mod_wsgi version 4.9.0.

**Comment by GrahamDumpleton** [comment]
Delayed response, but trying to clear out old issues.

As to ``wsgi.multiprocess``, your observation seems contradictory. You said:

> It is checking the value of "AP_MPMQ_MAX_DAEMONS", which is defined as "Max # of daemons used so far"

and then you said:

> the correct value to be checking is "AP_MPMQ_MAX_DAEMONS" which is defined as "Max # of daemons by config".

You reference the same constant value in both. In the first you probably meant ``AP_MPMQ_MAX_DAEMON_USED``, but that is not what is used anyway.

So ``wsgi.multiprocess`` is correct as far as I can tell.

As to ``wsgi.multithread`` and how it it set, I don't recollect why was always set if MPM supported multiple threads, regardless of number of threads per child per configured. May have been because in practice no one ever set number of threads per child to one anyway with multithreaded MPMs and so didn't see it as important. Anyway, as far as I remember I don't think the issue was was that Apache 2.0 didn't report number threads correctly or that it was otherwise buggy.

With ``mod_wsgi-express`` since 4.8.0 allowing one to provide ``--embedded-mode`` and thus not always use daemon mode, and where it is actually possible to say ``--threads=1` and have it work in a sane way since ``mod_wsgi-express`` overrides all configuration and uses something that will actually work properly for Python applications in embedded mode, it is probably reasonable to have this be accurate now. So have fixed up value of ``wsgi.multithread`` for inclusion in mod_wsgi version 4.9.0.
