### ISSUE TITLE
'django' module not found error

### ISSUE THREAD

**Issue by nlombardi** [GrahamDumpleton/mod_wsgi#602]
Hi Graham,

I imagine you are tired of seeing this but I have read through just about every question on this I could find and have tried to resolve my issues to no avail.

Config file:

```
<VirtualHost *:80>
    ServerAdmin admin@website
    ServerName website
    ServerAlias website
    DocumentRoot /var/www/website
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    Alias /robots.txt /var/www/website/robots.txt
    Alias /favicon.ico /var/www/website/favicon.ico

    Alias /static /var/www/website/static
      <Directory /var/www/website/static>
        Require all granted
    </Directory>

    Alias /media /var/www/website/media
    <Directory /var/www/website/media>
        Require all granted
    </Directory>

    <Directory /var/www/website/django_project>
        <Files wsgi.py>
                Require all granted
        </Files>
    </Directory>

    WSGIScriptAlias / /var/www/website/django_project/wsgi.py
    WSGIDaemonProcess website python-path=/var/www/website python-home=/var/www/website/venv
    WSGIProcessGroup website
</VirtualHost>
```

WSGI.py file:

```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'django_project.settings')

application = get_wsgi_application()
~                                        
```

When I load the virtual environment and run python it seems to load django fine..

**Comment by GrahamDumpleton** [comment]
The two usual problems are as follows.

The first is that the Apache user cannot read into the directories under ``/var/www`` because at some point they were created with restrictive permissions (installed with umask 007 as root). This can apply to any directory in the path, or even just installed Python packages.

A second is that mod_wsgi is compiled for a different Python version that the virtual environment is created for.

There can be other reasons though depending on the platform. Eg. SELinux on RHEL/CentOS.

**Comment by nlombardi** [comment]
> 
> 
> The two usual problems are as follows.
> 
> The first is that the Apache user cannot read into the directories under `/var/www` because at some point they were created with restrictive permissions (installed with umask 007 as root). This can apply to any directory in the path, or even just installed Python packages.
> 
> A second is that mod_wsgi is compiled for a different Python version that the virtual environment is created for.
> 
> There can be other reasons though depending on the platform. Eg. SELinux on RHEL/CentOS.

Hmm okay yeah I tried playing with the permissions a bit because I did install it as root. However, I did not set the whole folder to give Apache user access (www-data) rather the user access. I will try this first. I did check that the versions of python were the same.

**Comment by nlombardi** [comment]
> 
> 
> The two usual problems are as follows.
> 
> The first is that the Apache user cannot read into the directories under `/var/www` because at some point they were created with restrictive permissions (installed with umask 007 as root). This can apply to any directory in the path, or even just installed Python packages.
> 
> A second is that mod_wsgi is compiled for a different Python version that the virtual environment is created for.
> 
> There can be other reasons though depending on the platform. Eg. SELinux on RHEL/CentOS.

This doesn't seem to be the case both Python versions are 3.8.2 and all the permissions are in order for django pytz and the application. Does every folder / file within /var/www/website/ need to have Apache group ownership?

**Comment by GrahamDumpleton** [comment]
They don't need to be owned or have group of the Apache user, the directories and files usually would instead be set to be readable/accessible to other.

So directories would have permissions of ``drwxr-xr-x`` and files would be ``-rw--r--r--`` or ``-rwxr-xr-x``.

Note that for directories, all directories from the root of the filesystem down into the web site directory, Python code etc, need to be readable/accessible. If there are any directories in the path some where which have something like ``drwx------`` it will not be access to the Apache user if was owned by a different user.

BTW, add outside of the ``VirtualHost`` the directive:

```
WSGIRestrictEmbedded On
```

This will turn off Python interpreter support in Apache child worker processes, which will result in an error if for some reason there was an issue and code was actually being run in embedded mode rather than daemon mode.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
