### ISSUE TITLE
Using `WSGIScriptAlias` with a trailing slash on the URL-path breaks deep linking

### ISSUE THREAD

**Issue by Helveg** [GrahamDumpleton/mod_wsgi#603]
When using the `WSGIScriptAlias` like this:

```
WSGIScriptAlias /myapp/ /path/to/my/app
```

Then `mydomain.com/myapp/` will be passed to the WSGI app but deeper links like `mydomain.com/myapp/hello` will cause Apache to raise a 404 error. Quite confusing behavior, I think it should either cause a configuration error or work identical to the case without a trailing slash.

```
WSGIScriptAlias /myapp /path/to/my/app
```

**Comment by GrahamDumpleton** [comment]
This is not mod_wsgi, it is Apache and how Apache has always worked.

Apache matches URLs to file system paths and in the process allows for rewriting/modification of the path.

In the case of ``WSGIScriptAlias``, and the same for ``ScriptAlias`` and ``Alias`` directives in Apache, when it matches the first argument, the matched portion is dropped off the front of the URL and the remain part of the URL is appended to the second argument. That combined path is then what is attempted to be matched against a directory/file in the file system.

Thus both arguments should always have trailing slashes, or both not have trailing slashes unless you are attempting to do some sort of rewriting. That is the rule.

So those are the base rules around how it works, but it is how Apache does it, not mod_wsgi.

The only exception to that rule is where the first argument is "/", in which case the full URL path is appended to the second argument. This is because having a first argument of an empty string would itself be confusing, so "/" is treated as if there was an empty string and the full URL path appended to the second argument when doing the match.

**Comment by Helveg** [comment]
Alright, thanks for the explanation! Nothing to do here then :)
