### ISSUE TITLE
testing django project with newly released OS X 11 and modwsgi - getting a warning error msg: no code signing authority for mod_wsgi-py38.cpython-38-dwwin.so

### ISSUE THREAD

**Issue by judithdboonstra** [GrahamDumpleton/mod_wsgi#629]
mod_wsgi is currently working with OS X 11 and django app tested, but warning msg states module will not be made available in future release of OS X if code signing certificate is not made available.  I understand this situation has occurred for other previous releases of mod_wsgi and signing certificate was made eventually made available for them.  Please advise when the required signing authority might be made available for OS X 11.

**Comment by GrahamDumpleton** [comment]
A signing certificate for mod_wsgi was never available for older macOS releases, so not sure what you are talking about in respect of that. Also, as far as I know, this will only arise if you try and use Apple's version of Apache httpd, if you install Apache httpd yourself, or by using ``mod_wsgi-standalone`` package, it shouldn't arise.

Anyway, the direction for a while has been that it may well be that it will not be possible to use mod_wsgi with Apple supplied httpd in the future when this is a requirement, unless someone can explain how an ad-hoc signing certificate might be used. If they don't allow an ad-hoc signing certificate, then that isn't going to work either.

For this to be solved, I need someone to explain to me what needs to be done as I know nothing about application signing on macOS.

**Comment by GrahamDumpleton** [comment]
Current situation with this is still that you will not be able to use Apple supplied Apache instance in future, you will instead have to use Apache supplied with HomeBrew. Further, as it stands right now you cannot build Apache from source code yourself if you intend to also build apr and apr-utils from source code as apr 1.7.0 cannot be configured on latest macOS versions. The apr problems are due to incompatibilities between apr autoconf scripts and macOS header file definitions. Have not been able to find any simple fix for the apr issue and the apr project hasn't released a new version even though they are aware of the issue. Because of the issue with building apr from source code, it also isn't possible to use ``mod_wsgi-standalone`` package on macOS.
