### ISSUE TITLE
 error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by talhaanwarch** [GrahamDumpleton/mod_wsgi#639]
I am trying to install mod-wsgi on Linux 2. But I am getting this error

    error: command 'gcc' failed with exit status 1
    ERROR: Command errored out with exit status 1: /home/ec2-user/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jzcb7l6h/mod-wsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jzcb7l6h/mod-wsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zrs06wit/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/venv/include/site/python3.7/mod-wsgi Check the logs for full command output.

This is what I have tried

    yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel
    cd /usr/src
    sudo wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
    sudo tar zxvf Python-3.7.9.tgz 
    ./configure --enable-shared
    ./configure --enable-optimizations
    #sudo make
    sudo make altinstall
    python3.7 --version
    cd ~
    python3.7 -m venv venv
    source venv/bin/activate
    sudo yum update httpd
    sudo yum install httpd
    sudo yum install httpd-devel
    pip install mod-wsgi

**Comment by GrahamDumpleton** [comment]
You didn't provide the important part of the error message where it shows what went wrong.

Your steps are wrong though, you cannot run:

```
./configure --enable-shared
./configure --enable-optimizations
```

as two separate steps. You should only run ``configure`` once will all options.

As is, ``--enable-shared`` wouldn't be getting applied and so mod_wsgi would fail to build due to a lack of Python shared library.

For installing Python from source code properly see:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Ignore that talks about docker as is still relevant.

The lack of a Python shared library would result in a variant of the following error:

* https://modwsgi.readthedocs.io/en/master/user-guides/installation-issues.html#mixing-32-bit-and-64-bit-packages

**Comment by talhaanwarch** [comment]
Thanks. It resolved the issue. The final solution is as follow
```
sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel httpd httpd-devel

cd /usr/src
sudo wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
sudo tar zxvf Python-3.7.9.tgz 
sudo ./configure --enable-shared --enable-optimizations
sudo make
sudo make altinstall
sudo ldconfig /usr/local/lib 

python3.7 --version
cd ~
python3.7 -m venv venv
source venv/bin/activate

pip install mod_wsgi
```
