### ISSUE TITLE
WSGILazyInitialization fails with fatal error in PyOS_AfterFork_Parent

### ISSUE THREAD

**Issue by tiran** [GrahamDumpleton/mod_wsgi#642]
I wanted to experiment with WSGILazyInitialization in order to test if the option could reduce memory usage of FreeIPA's wsgi server endpoint. The daemon processes consume about 100 MB memory right from the start. Because we use Kerberos/GSSAPI with constraint delegation we have to run in process mode and cannot threads. This ensures that credentials don't leak from one request to another request. I hope that lazy initialization would allow us to make use of CoW and run more daemon processes.

``WSGILazyInitialization Off` is failing with a fatal error in ``PyOS_AfterFork_Parent``. It looks like ``_PyImport_ReleaseLock`` is failing.

https://github.com/python/cpython/blob/ea97ebab3578a6e0bb505da96819ac44d422a6cb/Modules/posixmodule.c#L571-L578

## Apache ``ipa.conf``

```
WSGIDaemonProcess ipa processes=4 threads=1 maximum-requests=500 \
  user=ipaapi group=ipaapi display-name=%{GROUP} socket-timeout=2147483647 \
  lang=C.UTF-8 locale=C.UTF-8
WSGIImportScript /usr/share/ipa/wsgi.py process-group=ipa application-group=ipa
WSGIScriptAlias /ipa /usr/share/ipa/wsgi.py
WSGIScriptReloading Off
WSGIRestrictEmbedded On
WSGILazyInitialization Off
```

## coredump

```
           PID: 430806 (httpd)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Tue 2020-12-22 10:00:48 CET (14s ago)
  Command Line: /usr/sbin/httpd -DFOREGROUND
    Executable: /usr/sbin/httpd
 Control Group: /system.slice/httpd.service
          Unit: httpd.service
         Slice: system.slice
       Boot ID: 23b1b9a7bd41463e920567b3d6cd8a7f
    Machine ID: 3ad60f02c7119152b108a0d17e1bbd4b
      Hostname: server.ipa.test
       Storage: /var/lib/systemd/coredump/core.httpd.0.23b1b9a7bd41463e920567b3d6cd8a7f.430806.1608627648000000.lz4
       Message: Process 430806 (httpd) of user 0 dumped core.
                
                Stack trace of thread 430806:
                #0  0x00007f30a5b369e5 raise (libc.so.6 + 0x3c9e5)
                #1  0x00007f30a5b1f895 abort (libc.so.6 + 0x25895)
                #2  0x00007f30a4cc2892 fatal_error (libpython3.8.so.1.0 + 0xc8892)
                #3  0x00007f30a4cc28ab Py_FatalError (libpython3.8.so.1.0 + 0xc88ab)
                #4  0x00007f30a4c93119 PyOS_AfterFork_Parent (libpython3.8.so.1.0 + 0x99119)
                #5  0x00007f30a4f62305 wsgi_start_process (mod_wsgi_python3.so + 0x21305)
                #6  0x00007f30a4f64a1f wsgi_start_daemons (mod_wsgi_python3.so + 0x23a1f)
                #7  0x0000561c8e3f1a2d ap_run_pre_mpm (httpd + 0x35a2d)
                #8  0x00007f30a546c992 event_run (mod_mpm_event.so + 0x8992)
                #9  0x0000561c8e3eacd8 ap_run_mpm (httpd + 0x2ecd8)
                #10 0x0000561c8e3d4344 main (httpd + 0x18344)
                #11 0x00007f30a5b21042 __libc_start_main (libc.so.6 + 0x27042)
                #12 0x0000561c8e3d449e _start (httpd + 0x1849e)

```

## Packages
```
python3-mod_wsgi-4.6.8-2.fc32.x86_64
python3-3.8.6-1.fc32.x86_64
httpd-2.4.46-1.fc32.x86_64
```

**Comment by GrahamDumpleton** [comment]
```WSGILazyInitialization Off``` is a huge security risk and by rights should have been removed long ago. Having that on means Python runs as root when first loaded, meaning that if someone can sneak in a Python package with a ``.pth`` file which runs code, they can run code as root when the Python interpreter is initialised. It only exists as an option because of very old compatibility with how mod_wsgi once worked due to trying to be consistent with mod_python. Lazy initialisation became the default due to the security risks of how the old mod_python way of doing things worked.

It was pointed out to me that it failed a while back, but forgot about removing the code for it, or at least removing the configuration directive.

So have no desire to fix it, but instead need to remove the option.

**Comment by GrahamDumpleton** [comment]
I should also point out that that option wouldn't have helped anyway. It only allowed for the initialisation of the Python interpreter to be done in the Apache parent process, no application preloading would have been done. Also, the reinitialisation of the Python interpreter in the Apache parent process on Apache configuration reloads would cause memory leaks as Python doesn't do a very good job of cleaning up everything on shutdown (or it hasn't in the past, so wouldn't trust it still). As a consequence, the more that Apache gets reloaded, the more the Apache parent process grows in size, which in turn gets inherited by all child processes.

So my question is what you think is consuming the 100MB. It just sounds like your application code and whatever initialisation it does when loaded causes it. The only other cause if not your application code would be a Python shared library which isn't actually a proper shared library and which has static code linked, which causes address relocations on loaded, causing actual memory to be used rather than the shared library memory being shared.

Finally, unless you missed something from your configuration, it is actually wrong and you are running your WSGI application in embedded mode and not daemon mode. At the same time you are still loading a copy of your application in the daemon processes even though they aren't being used. This would cause more memory usage, plus your application isn't actually running single threaded if you are using event or worker MPM for Apache. I think it is likely a mistake in issue though since you have ``WSGIRestrictEmbedded On`` which meant you should get a 500 error with that configuration.

What you have is:

```
WSGIDaemonProcess ipa processes=4 threads=1 maximum-requests=500 \
  user=ipaapi group=ipaapi display-name=%{GROUP} socket-timeout=2147483647 \
  lang=C.UTF-8 locale=C.UTF-8
WSGIImportScript /usr/share/ipa/wsgi.py process-group=ipa application-group=ipa
WSGIScriptAlias /ipa /usr/share/ipa/wsgi.py
```

What I would expect to also see is:

```
WSGIProcessGroup ipa
WSGIApplicationGroup ipa
```

Either way, what you should instead use rather than all of the above is:

```
WSGIDaemonProcess ipa processes=4 threads=1 maximum-requests=500 \
  user=ipaapi group=ipaapi display-name=%{GROUP} socket-timeout=2147483647 \
  lang=C.UTF-8 locale=C.UTF-8
WSGIScriptAlias /ipa /usr/share/ipa/wsgi.py process-group=ipa application-group=%{GLOBAL}
```

That is, don't use ``WSGIImportScript``, pass the ``process-group`` and ``application-group`` options to ``WSGIScriptAlias`` instead. Both being supplied to ``WSGIScriptAlias`` causes preloading in the process the same as what ``WSGIImportScript`` does. At the same time, having it on ``WSGIScriptAlias`` ensures it is running in the daemon process group and not elsewhere because you forgot ``WSGIProcessGroup`` or ``WSGIApplicationGroup``, or they weren't set in the correct place.

You also should use ``%{GLOBAL}`` with ``application-group`` instead of ``ipa``. Use of ``%{GLOBAL}`` ensures it is run in Python main interpreter context and not a sub interpreter. Use of a sub interpreter context can fail or have strange problems when using third party Python packages with a C extension which don't work properly in sub interpreters.

The value you use for ``socket-timeout`` is also dodgy. There is no good reason for having an effective infinite timeout on that.

**Comment by tiran** [comment]
Thanks Graham!

I only included a small part of our Apache config. You can find the full config file at https://github.com/freeipa/freeipa/blob/master/install/share/ipa.conf.template. We indeed use ``WSGIProcessGroup`` and ``WSGIApplicationGroup``.

```
<Location "/ipa">
  ...
  WSGIProcessGroup ipa
  WSGIApplicationGroup ipa
</Location>
```

The application server is large and complex. We also pre-initialize a lot of data like i18n strings, LDAP server schema, and more. A new server process has a ``len(gc.get_objects())`` of nearly 100,000 objects. According to htop, each server process has about 100 MB RSS and 30 MB shared. I assume that a lot of Python objects could be shared across forks. ``gc.freeze`` might help, too.

**Comment by GrahamDumpleton** [comment]
Unless the code/data is never actually touched, COW doesn't actually work very well for Python. This is because even when notionally read only, references counts on code/data is incremented/decremented when run/accessed, thus breaking COW for the whole page a single object may be in. You also have to design your application so it can defer certain actions until after a fork for some stuff using resources external to the process. So it may get you a little, but the benefit of COW in Python is actually overrated.

Do ensure you change the config so using application group of ``%{GLOBAL}``. That may save you a couple MB at least.

**Comment by GrahamDumpleton** [comment]
If you care to still try out your experiment, you can use the ``develop`` branch of GitHub repository for mod_wsgi. Have removed the call to ``PyOS_AfterFork_Parent()`` as I don't think in the context of how mod_wsgi works to call it at that point makes any sense. Not sure why it didn't cause a failure in Python 3.7 and only in Python 3.8+.

As already said, none of your application code gets run in the Apache parent process so no option for preloading anyway. The Python main interpreter takes up 5MB and using the option would see it initialized in the parent so not gaining much really.

Also as mentioned, because of memory/reference count/garbage collector leaks by Python, the reinitialization of Python in parent process in Apache parent process on configuration reloads will result in an effective memory leak will process size growing over time as more reloads done.
