### ISSUE TITLE
mod_wsgi-express - ServerAdmin

### ISSUE THREAD

**Issue by matzek92** [GrahamDumpleton/mod_wsgi#643]
Is there a way to provide a String/Email to display in Apaches default Internal Error Page?

![grafik](https://user-images.githubusercontent.com/8626626/103554252-e0ef7e80-4eae-11eb-911c-3613c0aeef35.png)

In Apaches VirtualHost configuration there is the ServerAdmin option which seems to be missing in mod_wsgi-express CLI.

**Comment by GrahamDumpleton** [comment]
You can use the ``--include-file`` option to include additional Apache configuration at the end of the generated configuration. You could then set ``ServerAdmin`` .

Another option is to use ``--error-document`` to override the complete error page. Eg:

```
--error-document 500 /500.html
```

This is the same as using the ``ErrorDocument`` directive to Apache.

Do be aware though that complications can arise if using the Python application, rather than static file, to create the error page. The issue is that if the error also affects the error page, it will not be able to render it and so you get even stranger error responses. There is a ``--error-override`` option that somehow relates to that, but to be honest I can't quite remember what that is meant to do right now.

**Comment by matzek92** [comment]
Thank you very much I'll use one of these options.

Is there a special reason why ServerAdmin is not provided by the mod_wsgi-express CLI?

**Comment by GrahamDumpleton** [comment]
Usually the Apache error pages wouldn't get used since the Python web application would usually be generating them if an error occurs in the application. So people probably wouldn't even bother to customize the generic error pages. So no one has ever asked before.

**Comment by matzek92** [comment]
"So no one has ever asked before." - Woohoo, first one :D Thank you again.
