### ISSUE TITLE
Running mod_wsgi with anaconda on CentOs

### ISSUE THREAD

**Issue by ellevset** [GrahamDumpleton/mod_wsgi#646]
Gents
I am having some troubles here.

I am trying to deploy a django project using an anaconda environment, with apache and mod_wsgi. I have managed to install mod_wsgi (using pip) and configure django (mod_wsgi-express module-config). But I am not able to get it started. The critcal error message is:

OSError: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by [path to my anaconda environments folder]/django37/lib/./libpng16.so.16)

I am able to do the failing import when starting a django-shell, so I am wondering if I need to tell apache/mod_wsgi something special to get it to import the correct libraries (I can find the correct zlib files in my environ/lib folder).

Any help is appreciated.

**Comment by GrahamDumpleton** [comment]
Confirm the file exists by running:

```
ls -als /lib64/libz.so.1
```

What do you get?

Ensure you don't have a system package for mod_wsgi still installed, with it being used in preference to Anaconda compiled version of mod_wsgi.

Show me the output of running ``mod_wsgi-express module-config`` that you included in the Apache configuration.

Use the WSGI test script at:

* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use

to verify what Python installation is being used.

One possible problem is that you are still using system package for mod_wsgi with Anaconda Python virtual environment. When C extensions from the Anaconda Python virtual environment are imported they could fail because Anaconda Python provides its own versions of system libraries which may be different to system versions which are going to be found in preference to Anaconda versions.

This can all be made worse if you are loading PHP into Apache as it will load versions of system libraries which directly conflict with Anaconda versions.

**Comment by ellevset** [comment]
ls -al /lib64/libz.so.1
lrwxrwxrwx 1 root root 13 Aug  4  2017 /lib64/libz.so.1 -> libz.so.1.2.7

I can't find any system package for mod_wsgi. Note that I did have one when I started to implement conda/django/apache. Previously was just django/apache. I uninstalled after some googling.

mod_wsgi-express module-config:
LoadModule wsgi_module "[path to my conda envs dirs]/django37/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
WSGIPythonHome "[path to my conda envs dirs]/django37"

Result from test-script:
sys.version = '3.7.7 (default, Mar 23 2020, 22:39:38) \n[GCC 7.3.0]'
sys.prefix = '[path to my conda envs dirs]/django37'

**Comment by GrahamDumpleton** [comment]
All I can suggest is not to use Anaconda Python.

As I mentioned, Anaconda Python comes with its own versions of various system libraries and these can cause conflicts when talking about embedded systems where Python is embedded in an application which already uses the system versions of the libraries.

The problem you are seeing is that Apache or a key Apache module already links version 1.2.7 of the libz, but something in Anaconda is compiled against 1.2.9 and they aren't ABI compatible. As a result when that module with Anaconda Python loads it fails.

In the past these library incompatibilities occurred from SSL, crypto and image libraries. Seems Anaconda Python has now made things worse by shipping its own incompatible compression library. This is likely going to make it impossible to use Anaconda Python with mod_wsgi now.

**Comment by ellevset** [comment]
Thats bad news then. I'll have to try something else then. Thank you for the assistance.
