### ISSUE TITLE
mod_wsgi-metrics should be an optional dependency

### ISSUE THREAD

**Issue by pombredanne** [GrahamDumpleton/mod_wsgi#65]
It brings itself plus psutils
I am not sure I grok the rationale for making this a hard requirement: it should be optional

**Comment by GrahamDumpleton** [comment]
Because determining memory usage in a portable way across various Linux flavours and versions is a lot of work. The psutil package abstracts that all away so I don't need to support determining memory usage myself. As was mod_wsgi-metrics does increases, it will come to rely on psutil for a range of other things which it does in a portable way.

**Comment by pombredanne** [comment]
@GrahamDumpleton thanks for the quick reply...
I do not dispute the need to use psutils for the metrics parts... I am just saying that the metrics part should be optional not required as a setup.py requirement

**Comment by GrahamDumpleton** [comment]
Sorry, thought you were taking issue with psutil being dragged in by mod_wsgi-metrics and not mod_wsgi-metrics by mod_wsgi.

It comes down to convenience and when someone tries to enable metrics support that it simply works without them having to realise they have to go install yet more packages.

Right now the metrics package may rely on a specific vendor for visualisations but that will change and in time there will be a bundled solution within the package for viewing recent data straight out of mod_wsgi.

Given that so many people set up mod_wsgi poorly due to not configuring it based on the requirements of their application, I want to make it as easy as possible for people to be able to run tools that allow them to monitor the performance and so set things up right, including capabilities within an internal system that can even perhaps analyse performance and give you suggestions of what to change.

Overall, since you need a compiler for mod_wsgi to be able to be installed in the first place, I don't see an issue with it ultimately dragging in psutil as it should be able to be installed of mod_wsgi could be installed.

What is the specific problem you are having with the dependency? Python package installation tools should be able to deal with it okay.

**Comment by pombredanne** [comment]
IMHO metrics being an add on it should express a dependency on modwsgi, not the other around: modwsgi does not depends on metrics per se. 
I have no problem with dependencies but in general I am trying to limit these when possible. and modwsgi is one of a few hundreds that I carry around. Fewer un-needed moving parts are always best....
and I was surprised when upgrading modwsgi to see these new dependencies pulled in.
For tehse that want metrics by installing only metrics it would pull mod_wsgi if you set the dependencies right. For those that do not want metrics, they can pull only mod_wsgi and be happy with it.

**Comment by pombredanne** [comment]
What I mean really is that metrics is not essential to mod_wsgi, so it should not depend on it.

**Comment by GrahamDumpleton** [comment]
Fine I will get rid of it, but also likely abandon the whole mod_wsgi-metrics project. I really can't understand all the negative push back I have been getting over the metrics capabilities. So many people run with crappy configurations which don't result in the best performance they can get but they simply don't care, even when you try and give them a system which will help then to tune their Apache/mod_wsgi setup properly they are not interested and adamantly say they will never run it. Shakes head and finally gives up.

**Comment by pombredanne** [comment]
@GrahamDumpleton do not take this wrong my Lord! Your efforts are super appreciated!
I was just making a comment on the dependency which looked as inverted to me....
My 2 cents is that when you introduce new dependencies on such a widely used component as this fine piece of code, it makes sense to make these optional...

In my case I have large scale apps that have 100's of dependencies and each one is a liability in some ways... the fewer the better in my book :) and I like to be able to control them and limit them whenever possible.

Do not give up!

**Comment by GrahamDumpleton** [comment]
I should be just grateful you are even using the pip installable version of mod_wsgi and so potentially mod_wsgi-express. The PyPi stats aren't showing many downloads at this point. :-)

Having the dependency the other way will not work as mod_wsgi-metrics needs to be able to be installed independent of whether you have pip installable mod_wsgi package. You could actually be using mod_wsgi (without mod_wsgi-express) installed from a Linux binary package. In that case don't want to force the installation of 'mod_wsgi' package.
