### ISSUE TITLE
mod_wsgi can not be statically built into Apache

### ISSUE THREAD

**Issue by pinaraf** [GrahamDumpleton/mod_wsgi#66]
Hi

For security reasons, we have to build our Apache statically, without dynamically loading the modules.
When we try to build in our Apache, the compilation fails because Apache does not find the required files.

I'll submit a fix for that.

**Comment by pinaraf** [comment]
When linking statically mod_wsgi in Apache that way, enabling the daemon mode crashes apache on startup (segfault) and strace does not show any meaningfull error.
Do you have any idea what could go wrong that way ?

**Comment by GrahamDumpleton** [comment]
The changes to the configure/Makefile break the normal build case. That can be workaround in other ways though, perhaps by configure taking an option to say you want to perform a static build. Am also not sure they changes were even required anyway, as you can simply link the path of the mod_wsgi.so directly. You do not need to turn it into a library.

The bigger problem is that that there are a range of changes in the mod_wsgi source code that would be required to allow static linking and for daemon mode in particular to work.

This is because parts of the configuration currently rely on the fact that Apache would unload the mod_wsgi.so module from memory between two internal configuration passes Apache does. This has the effect of resetting various global variables back to defaults for the second pass. The code would need to be changed to move certain global variables into per pass data structures, or detect when second pass is done and reset them manually.

That mod_wsgi behaved this way was a known issue, but no one has specifically asked to be able to statically link it in the past.

**Comment by GrahamDumpleton** [comment]
I am going to close this issue. The work involved to make mod_wsgi work when statically linked is too great for such a rare requirement. It wouldn't even be practical to do this as paid work due to the significant amount of work that would probably be involved. That even presumes that could make it work.
