### ISSUE TITLE
Truncated or oversized response headers received from daemon process on timeout

### ISSUE THREAD

**Issue by ancc** [GrahamDumpleton/mod_wsgi#666]
Here's shortest reproducible example with no C extensions. Tried on Centos 7, Centos 8, Oracle Linux 8,
Example:
cat Dockerfile
```
FROM centos:8 as builder
RUN yum install -y gcc make httpd-devel tar wget redhat-rpm-config python36 python36-devel
RUN cd /tmp && \
    wget https://files.pythonhosted.org/packages/74/98/812e68f5a1d51e9fe760c26fa2aef32147262a5985c4317329b6580e1ea9/mod_wsgi-4.7.1.tar.gz && \
    tar zxf mod_wsgi-4.7.1.tar.gz && cd mod_wsgi-4.7.1 && \
    ./configure --with-python=/usr/bin/python3.6 && make && make install
RUN pip3 install bottle
COPY test.wsgi /var/www/
COPY test.conf /etc/httpd/conf.d/
ENTRYPOINT exec httpd -DFOREGROUND
```

cat test.wsgi
```
#!/usr/local/bin/python3
import bottle
import time

@bottle.route('/', ['POST', 'GET'])
def test():
    time.sleep(31)
    return 'hi'
application = bottle.default_app()
```

cat test.conf
```
LoadModule wsgi_module modules/mod_wsgi.so
WSGISocketPrefix /var/run/wsgi
WSGIDaemonProcess test processes=1 threads=1 display-name=test user=apache group=apache request-timeout=10
WSGIProcessGroup test
WSGIScriptAlias / /var/www/test.wsgi process-group=test application-group=%{GLOBAL}
```

building image
`docker build . -t test`
Running it
`docker run -d --name test test`
Making request to localhost (waiting timeout)
`docker exec -t test curl localhost`
Output is 500 Internal Server Error

and in logs
`[Wed Mar 24 07:18:43.728772 2021] [wsgi:error] [pid 9:tid 139902578517760] [client 127.0.0.1:51352] Truncated or oversized response headers received from daemon process 'test': /var/www/test.wsgi`

**Comment by GrahamDumpleton** [comment]
I would suggest trying to use ``mod_wsgi-express`` instead.

* https://pypi.org/project/mod-wsgi/
* http://blog.dscpl.com.au/2015/04/introducing-modwsgi-express.html

For use in a container it is much better than trying to configure Apache yourself.

Also try with the ``develop`` version of mod_wsgi from GitHub. It has a fix for an obscure issue that can arise when preloading the WSGI application (both process-group and application-group used on WSGIScriptAlias). The issue was only really showing itself on Alpine Linux, but wouldn't rule out that could affect other distros if you have heavily cut back what is in the Apache configuration.

**Comment by ancc** [comment]
develop version didn't help, same error.
Will try express. Does express support multiple entrypoints? Currently I have mutliple WSGIDaemonProcess and WSGIScriptAlias directives. Does mod_wsgi-express generated apache configuration is like appended to apache own httpd.conf ? Existing apache configuration containes lot of proxy and other configurations also.

**Comment by GrahamDumpleton** [comment]
Have you tried with a WSGI hello world application rather than your full application. Since it only occurs on a request, it is quite possible the problem is actually a third party Python package with C extension. Testing with a hello world application will confirm whether mod_wsgi is working okay. You would then need to work out which third party package is the problem.

**Comment by ancc** [comment]
That's why I created the simple Docker example which containes only Bottle (pure python) and nothing else. It means no thirdparty packages can affect it. This is the shortest example to reproduce the issue.

**Comment by ancc** [comment]
Tried now also without Bottle, same result
Dockerfile
```
FROM centos:8 as builder
RUN yum install -y gcc make httpd-devel tar wget redhat-rpm-config python36 python36-devel
COPY mod_wsgi /tmp
RUN cd /tmp && \
    ./configure --with-python=/usr/bin/python3.6 && make && make install
COPY test.wsgi /var/www/
COPY test.conf /etc/httpd/conf.d/
ENTRYPOINT exec httpd -DFOREGROUND
```

test.wsgi
```
#!/usr/local/bin/python3
import time
def application(environ, start_response):
    time.sleep(30)
    status = '200 OK'
    output = b'Hello World!'
    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)
    return [output]
```
it works if I remove time.sleep

**Comment by ancc** [comment]
Any updates?

**Comment by GrahamDumpleton** [comment]
When you have the WSGI application sleep for 30s, it is exceeding the request timeout you set of 10s. The result will be that the daemon process will be shutdown, which will cause the error you see as the connection to the daemon process will be cut off. So the error is expected. The logs even explain what happened:

```
[Thu May 13 11:03:18.549316 2021] [wsgi:info] [pid 10:tid 139919985874688] mod_wsgi (pid=10): Daemon process request time limit exceeded, stopping process 'test'.
[Thu May 13 11:03:18.549412 2021] [wsgi:info] [pid 10:tid 139920266008896] mod_wsgi (pid=10): Shutdown requested 'test'.
```

See details of ``request-timeout`` option in:

* https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGIDaemonProcess.html

**Comment by ancc** [comment]
Clear, I expected that in apache it logs timeout error with own message not "Truncated or over..." message. In production we don't run on "info" level. usually "Truncated or over.." message indicates serious error.

**Comment by GrahamDumpleton** [comment]
Unfortunately there isn't really a way to distinguish from the perspective of the Apache child worker processes doing the proxying between loss of the connection due to a timeout and forced daemon process restart, the daemon process crashing, or the values of response headers being too long.

If I wrote my own implementation of the Apache code which does the parsing of the response headers from the daemon process then technically I may be able to distinguish that case, but I don't know how to distinguish the others since there is no separate side channel whereby could communicate why the daemon process was being forcibly restarted.
