### ISSUE TITLE
Is WSGIRestrictStdout perhaps overstrict? 

### ISSUE THREAD

**Issue by carltongibson** [GrahamDumpleton/mod_wsgi#675]
Hi @GrahamDumpleton — I'm wondering if I can ask your input? 

We have [a report on Django of WSGIRestrictStdout triggering an error](https://code.djangoproject.com/ticket/32740) when `stdout.closed` is checked. 

(The `colorama` library does this on initialisation.)

This comes up (at the moment) for us at import-time if `colorama` is installed, but even if we nest that to defer it, the same check would fail for folks using `colorama` if called later.  

The docs say: 

> A well behaved Python WSGI application should never attempt to write any data directly to sys.stdout... 

OK, but that's not happening here. It's just the `stdout.closed` check, which shouldn't cause any harm do you think? If so, could the check around `WSGIRestrictStdout` be loosened some? 

Thanks for your thoughts! 
Kind Regards,

Carlton

**Comment by GrahamDumpleton** [comment]
For now try setting:

```
WSGIRestrictedStdout Off
```

There are various issues here can see which are coming together.

First is that ``colorama`` has:

```
    def isatty(self):
        stream = self.__wrapped
        if 'PYCHARM_HOSTED' in os.environ:
            if stream is not None and (stream is sys.__stdout__ or stream is sys.__stderr__):
                return True
        try:
            stream_isatty = stream.isatty
        except AttributeError:
            return False
        else:
            return stream_isatty()

    @property
    def closed(self):
        stream = self.__wrapped
        try:
            return stream.closed
        except AttributeError:
            return True
```

They try to deal with exceptions, but the restrictions on accessing stdout object in mod_wsgi raise an ``IOError`` not a ``AttributeError``.

I don't remember the history of why mod_wsgi raises ``IOError`, most likely it was because when I looked at definition of how file like objects in Python worked/defined and compared to what other file like objects raised and how they were used then that probably seemed the most appropriate exception type to raise to ensure most packages out there doing these sorts of checks would work. It possibly didn't help that back in the time of Python 2 that the definition of file like objects wasn't very complete.

So can be argued that ``colorama`` should perhaps check for both ``AttributeError`` and ``IOError``. For ``isatty()`` it should perhaps even check for ``ValueError`` since latest docs in Python say:

> Note that calling any method (even inquiries) on a closed stream is undefined. Implementations may raise ValueError in this case.

So check for just ``AttributeError`` is probably not enough for general case in ``colorama``.

That all said, I will need to think about whether the object that applies the restrictions should return some defaults for things like ``closed`` and ``isatty()`` rather than raise an outright ``IOError``.

In this case though I think that will actually just cause more problems though, as will setting ``WSGIRestrictEmbedded`` to ``Off``. This is because you should not be trying to colorize logs when using Apache because Apache will likely convert all the fancy escape sequences and encode them as \x?? making it pointless. Your logs will just fill up with gibberish.

So overall my feeling is that you should have a check for if mod_wsgi is being used and not configure or use ``colorama`` at all. Eg.

```
try:
    from mod_wsgi import version
    # Put code here which should only run when mod_wsgi is being used.
except ImportError, AttributeError:
    # Put code here which should run when mod_wsgi is not being used.
```

**Comment by carltongibson** [comment]
Hi @GrahamDumpleton — thanks for the super response! 

I've passed your comments along to colorama, and in Django we will move the `colorama.init()` out of the inappropriate path, and wrap it to catch the appropriate errors. 

> ...I think that will actually just cause more problems though... 

I suspect that's correct. 😀 Likely any _fix_ here isn't worth the complication. (I'll close on that basis.) 

Thanks again!
