### ISSUE TITLE
Error while installing mod_wsgi-httpd

### ISSUE THREAD

**Issue by MakufonSkifto** [GrahamDumpleton/mod_wsgi#680]
When I try to install mod-wsgi_httpd with pip3 into my Ubuntu 20.04, the loader gets stuck. This is how it looks like: 

![image](https://user-images.githubusercontent.com/63517174/118696967-803a6000-b817-11eb-8c12-be540f42d350.png)

How can I fix this? I know it doesn't install because when I close the program (PuTTY) and then restart it, I can still install it, It doesn't say "Requirement already satisfied"

**Comment by GrahamDumpleton** [comment]
It isn't getting stuck, that specific package takes a long time to install as it is compiling the whole of Apache HTTPD server.

Why are using mod_wsgi-httpd?

The package for mod_wsgi is called ``mod_wsgi``.

You only need ``mod_wsgi-httpd`` if for some reason you have no machine admin privileges and the system doesn't have Apache (both runtime and dev packages) already installed. Even then, you should't use ``mod_wsgi-httpd`` directly and instead you should use ``mod_wsgi-standalone`` which will install both ``mod_wsgi-httpd`` and ``mod_wsgi-httpd`` for you.

Since you seem to have sudo access to the machine you don't need either of them, install the operating system packages for Apache instead and then just use ``pip install mod_wsgi``. Is there are reason you aren't doing that?

**Comment by MakufonSkifto** [comment]
Yes, there is a reason why I tried to install it. I was having problems and my friend opened ([this issue](https://github.com/GrahamDumpleton/mod_wsgi/issues/681)). While looking at solutions online, I found this: 
![image](https://user-images.githubusercontent.com/63517174/118781014-4ad45780-b895-11eb-953a-3ebfae987ebd.png) This is why I tried to install `mod_wsgi-httpd`

**Comment by MakufonSkifto** [comment]
The problem is fixed by the issue I mentioned, thank you so much!
