### ISSUE TITLE
There no mod_wsgi-4.7.1-ap24vc14-cp37-win.whl

### ISSUE THREAD

**Issue by ZhangYupengCHY** [GrahamDumpleton/mod_wsgi#691]
Im wondering why there no mod_wsgi whl for windows python3.7.I search there have been existed.Why cant I download there source right now,or there is another way to solve the problem connect the apache and python3.7.
Im so look forward for your respond.
Much appreciate.

**Comment by GrahamDumpleton** [comment]
Because there are different Apache distributions and different versions, it isn't possible to create a single binary wheel that could be guaranteed to work with all of them. To be properly compatible with the specific version of Apache you are using, you must compile mod_wsgi specifically for it. For that reason I don't supply wheels as the maintenance nightmare which could result in dealing with people when it keeps breaking because their Apache version/distribution is different would be too much.

That said, you can try what you find at:

* https://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

Those have nothing to do with me though and I can't guarantee they work and I don't support them.

**Comment by ZhangYupengCHY** [comment]
Much appricate that your answer so fast.
And I understand the version of apache and python are so different.
I will close the comment.
And thanks again for solve my issue.
