### ISSUE TITLE
SSL certificate info needs to be accessible even when not performing authentication

### ISSUE THREAD

**Issue by pprindeville** [GrahamDumpleton/mod_wsgi#704]
Looking through the source of `mod_wsgi.c` (3.4 since that's what I'm working with on Amazon Linux 2), it seems that only if an `authn_provider` is being invoked (like `wsgi_check_password()`) will `Auth_environ()` get invoked, and populate the SSL state into the dictionary.

There are cases where you might not want/need the certificate to have to be authenticated by the app itself, but only by Apache.

For instance:

- a diagnostic tool that dumps out the client's TLS certificate in human-readable format;
- a self-service portal where users can dispose of their certificate (i.e. have it revoked) if they no longer need it;
- a self-service portal for re-issuing an updated certificate with a new serial # and validity window;
- a script might want to fail authentication explicitly with a `make_response("My detailed message here", 403)` instead;
- _etc_.

Whether the certificate is being used to authenticate is orthogonal to the potential need to have it be exported into `request.environ[]` for use by the script.

One could have a trivial `WSGIAuthUserScript` like:

```
def check_password(environ, user, password):
    err = request.environ['wsgi.errors']
    print('got here!  user="{0s:}"\n'.format(user), file = err)

    return True
```

but even then, the certificate would be exported into the `WSGIAuthUserScript`, and still not be easily available in the `WSGIScriptAlias` script that's being gated by the former.

What would be useful would be a boolean setting that exports the certificate from `mod_ssl` into the WSGI script, even when no script-based authentication is happening.

**Comment by GrahamDumpleton** [comment]
Testing with latest mod_wsgi (4.8+), but using mod_wsgi-express for simplicity, the behaviour is as follows.

If you run it like:

```
mod_wsgi-express start-server tests/environ.wsgi --server-name wsgi.green.advok8s.io --https-port 8443 --port 8080 --ssl-certificate-file green.advok8s.io-tls.crt --ssl-certificate-key green.advok8s.io-tls.key --log-to-terminal --ssl-environment
```

where all ``--ssl-environment`` does is result in:

```
SSLOptions +StdEnvVars
```

being added, then all the default SSL variables are available in the WSGI request handler ``environ`` dictionary. For example:

```
SSL_CIPHER: 'TLS_AES_128_GCM_SHA256'
SSL_CIPHER_ALGKEYSIZE: '128'
SSL_CIPHER_EXPORT: 'false'
SSL_CIPHER_USEKEYSIZE: '128'
SSL_CLIENT_VERIFY: 'NONE'
SSL_COMPRESS_METHOD: 'NULL'
SSL_PROTOCOL: 'TLSv1.3'
SSL_SECURE_RENEG: 'false'
SSL_SERVER_A_KEY: 'rsaEncryption'
SSL_SERVER_A_SIG: 'sha256WithRSAEncryption'
SSL_SERVER_I_DN: "CN=R3,O=Let's Encrypt,C=US"
SSL_SERVER_I_DN_C: 'US'
SSL_SERVER_I_DN_CN: 'R3'
SSL_SERVER_I_DN_O: "Let's Encrypt"
SSL_SERVER_M_SERIAL: '...'
SSL_SERVER_M_VERSION: '3'
SSL_SERVER_SAN_DNS_0: '*.green.advok8s.io'
SSL_SERVER_S_DN: 'CN=*.green.advok8s.io'
SSL_SERVER_S_DN_CN: '*.green.advok8s.io'
SSL_SERVER_V_END: 'Aug 21 04:45:13 2021 GMT'
SSL_SERVER_V_START: 'May 23 04:45:13 2021 GMT'
SSL_SESSION_ID: '...'
SSL_SESSION_RESUMED: 'Resumed'
SSL_TLS_SNI: 'wsgi.green.advok8s.io'
SSL_VERSION_INTERFACE: 'mod_ssl/2.4.48'
SSL_VERSION_LIBRARY: 'OpenSSL/1.1.1k'
```

So is working as would expect.

If instead you run with a WSGI auth user script:

```
mod_wsgi-express start-server tests/environ.wsgi --server-name wsgi.green.advok8s.io --https-port 8443 --port 8080 --ssl-certificate-file green.advok8s.io-tls.crt --ssl-certificate-key green.advok8s.io-tls.key --log-to-terminal --ssl-environment --auth-user-script tests/auth.wsgi
```

the SSL variables are still passed to the WSGI request handler.

If however you attempt to look in the ``environ`` dictionary passed to ``check_password()`` of WSGI auth user script, they are not present.

This is expected behaviour as mod_ssl is responsible for pushing them into the Apache request env from which the WSGI environ dictionary is populated (not mod_wsgi). The mod_ssl module doesn't do this until after auth handler phases and does it just before the content handler is executed.

To cope with this, in mod_wsgi 4.1.0 (but also back ported to mod_wsgi 3.4), the callable ``mod_ssl.is_https`` and ``mod_ssl.var_lookup`` were added to the ``environ`` dictionary passed to ``check_password()``. These map to internal functions of the same name in the Apache mod_ssl function intended to be used by other Apache modules to determine whether a secure connection is used and and lookup special SSL variables known of by mod_ssl.

You could therefore for example in ``check_password()`` do:

```
print('SSL_PROTOCOL', environ['mod_ssl.var_lookup']('SSL_PROTOCOL'))
```

So for latest mod_wsgi, but would even expect for version 3.4, the same as above should happen.

In summary, if use:

```
SSLOptions +StdEnvVars
```

then SSL variables should be visible in WSGI environ dictionary.

If using a WSGI auth user script, they aren't available in environ dictionary passed to that handler, and instead need to use the ``mod_ssl.var_lookup`` callable passed in the environ dictionary to explicitly look up the variable you want.

As to being able to see the certificate data itself, to get access to that from the WSGI application through the environ dictionary, you need to also add the ``ExportCertData`` option:

```
SSLOptions +StdEnvVars +ExportCertData
```

From the WSGI auth user script, you just need to lookup the correct variable name.

The ``mod_ssl.var_lookup`` function is not available in the WSGI request handler environ as that would open up a security problem in that the certificate data would be accessible to code with no gate being possible on that happening. When passed instead as actual variables in the WSGI environ using ``StdEnvVars`` that doesn't occur and needs ``ExportCertData`` to be set so is safer.

Details in variables in:

* https://httpd.apache.org/docs/current/mod/mod_ssl.html

**Comment by GrahamDumpleton** [comment]
Did this information help address the concerns? If yes, please close the issue. Thanks.

**Comment by pprindeville** [comment]
> Did this information help address the concerns? If yes, please close the issue. Thanks.

Yes and no.  I don't think `mod_wsgi-express` existed with 3.4, and I'm not wanting to do proxying through Apache... so Apache needs to run the scripts directly along with all of the existing configuration and load.

The issue, as per your separate email, turned out to be caused by using WSGI settings inside of a `<Directory>` inside a `<VirtualHost>`.  Changing this to `<Location>` inside `<VirtualHost>` instead (and changing the arg to match the first arg of the `WSGIScriptAlias` resolved the problem.
