### ISSUE TITLE
Unable to get Apache server running after adding mod_wsgi-express module-config in apache conf file

### ISSUE THREAD

**Issue by Divya-1019** [GrahamDumpleton/mod_wsgi#710]
Hi,

On my server:
1. I installed apache, https.exe -k start -> started Apache
2. I installed Python3.9 and other python packages
3. Ran 'pip install mod_wsgi'
4. After this tried running, 'mod_wsgi-express module-config', got error ->'failed to create process.'
5. Tried this 'C:\Python39\Scripts>mod_wsgi-express module-config', and it worked.
6. Added these to Apache, httpd.conf.
7. Tried to start the apache, got following error in error log:
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Apache24\\bin\\httpd.exe'
  sys.base_prefix = 'C:\\Python39'
  sys.base_exec_prefix = 'C:\\Python39'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Apache24\\bin\\httpd.exe'
  sys.prefix = 'C:\\Python39'
  sys.exec_prefix = 'C:\\Python39'
  sys.path = [
    'C:\\Python39\\python39.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\Apache24\\bin',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001180 (most recent call first):
<no Python frame>
[Sat Aug 28 13:56:33.869375 2021] [mpm_winnt:crit] [pid 5828:tid 624] AH00419: master_main: create child process failed. Exiting.

Can you please suggest, what is going wrong here.

Thanks in advance.

**Comment by GrahamDumpleton** [comment]
Since you closed this, can you explain what you did to get it working. Occasionally get people having this problem and although some solve the problem not getting enough feedback to nail down what people are doing wrong in their system setup to say for sure what is causing it. Right now assuming issue relates to not having installed Python system wide (and only installed it for single user), that or some other permissions issue since Apache service runs as different user.

**Comment by Divya-1019** [comment]
Setting the PYTHONHOME='C:\Python39' and PYTHONPATH='C:\Python39' in system variable worked for me.
