### ISSUE TITLE
document how to optimally run in embedded mode

### ISSUE THREAD

**Issue by bubenkoff** [GrahamDumpleton/mod_wsgi#72]
From the existing docs and your blog post about it http://blog.dscpl.com.au/2012/10/why-are-you-using-embedded-mode-of.html

would be nice to have a guide how to configure apache to get a better-than-daemon mode experience

**Comment by GrahamDumpleton** [comment]
Have you for a start watched:

* http://lanyrd.com/2013/pycon/scdyzk/

These days I wouldn't actually recommend embedded mode at all even if you can get a slight (likely undetectable) performance gain. The dangers are too great as there is no protections against blocked processes. Get any sort of problem with processes hanging and eventually you will hang your whole Apache.

Daemon mode, especially in more recent versions than ancient versions Linux distros ship, there are lots of things you can control to help detect and recover from blocking applications and backlog and so allow things to keep going rather than your Apache failing spectacularly.

**Comment by bubenkoff** [comment]
thank you very much for the response!
then, this recommendation should be put on docs i guess :)

**Comment by bubenkoff** [comment]
great talk btw!

**Comment by GrahamDumpleton** [comment]
Documentation needs a lot of work, but am having too much fun doing new code after having been burnt out and in a hole for a couple of years over mod_wsgi.

The mod_wsgi-express which you found on PyPi will be a distillation of what I regard as best practice. I am starting to warm up to getting documentation done for it but want to at least finish up some work on metrics related to it first.

**Comment by bubenkoff** [comment]
thank you!

On 11 March 2015 at 01:44, Graham Dumpleton <notifications@github.com>
wrote:

> Documentation needs a lot of work, but am having too much fun doing new
> code after having been burnt out and in a hole for a couple of years over
> mod_wsgi.
>
> The mod_wsgi-express which you found on PyPi will be a distillation of
> what I regard as best practice. I am starting to warm up to getting
> documentation done for it but want to at least finish up some work on
> metrics related to it first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GrahamDumpleton/mod_wsgi/issues/72#issuecomment-78179584>
> .
>



-- 
Anatoly Bubenkov
