### ISSUE TITLE
error with sudo make install LIBEXECDIR=/usr/local/etc/httpd/modules

### ISSUE THREAD

**Issue by interzone2** [GrahamDumpleton/mod_wsgi#720]
I'm getting error:

`make: *** No rule to make target `install'.  Stop.`

when using following command on BigSur:

sudo make install LIBEXECDIR=/usr/local/etc/httpd/modules

I've changed to /local/etc/ as that's where httpd is on my Mac. 

Any ideas?

**Comment by GrahamDumpleton** [comment]
Did you run `configure` first?

You should be using:

```
./configure
make install
```

Only the `make` command would need `sudo` if indeed root access was need to copy Apache module into place, which if using `brew` for installing Apache shouldn't be required anyway.

Note that this assumes that `apxs` can be found in your `PATH`. If it isn't, you would need to tell `configure` where it is:

```
./configure --with-apxs=/usr/local/bin/apxs
```

Also, just to be clear, you cannot use macOS Apache. Thus need to use `brew` installed Apache since that is likely only way to even get Apache on macOS now as building Apache from source code yourself on macOS will not work as official packages haven't been updated to work on recent macOS versions where as `brew` version they make changes so it can be installed.

If config/make/make install method is working, then can also try `pip install` method. See:

* https://pypi.org/project/mod-wsgi/

You need `brew` installed Apache either way.
