### ISSUE TITLE
mod_wsgi-standalone not working with latest httpd version

### ISSUE THREAD

**Issue by shishir-22** [GrahamDumpleton/mod_wsgi#748]
Hi,

I am running multiple flask applications using mod_wsgi-standalone. After the apache/httpd update to version > 2.4.46, I am getting this error while starting the mod_apache service after setting up the mod_wsgi-express server.

**Command giving me error:** /etc/mod_apache/{app-name}/apachectl restart
**Error Message:** httpd (mod_wsgi-express)   : Syntax error on line 52 of /etc/mod_apache/RAS11.4_DEV_11004/httpd.conf: Cannot load /usr/lib64/httpd/modules/mod_mpm_event.so into server: /usr/lib64/httpd/modules/mod_mpm_event.so: undefined symbol: ap_run_child_stopping

My setup is working fine with older httpd version:
Apache/httpd version: 2.4.46
mod-wsgi-httpd: 2.4.48.1
mod-wsgi-standalone: 4.9.0

But with latest httpd version I am getting above error:
Apache/httpd version: 2.4.51
mod-wsgi-httpd: 2.4.48.1
mod-wsgi-standalone: 4.9.0

Apart from httpd version nothing else is change from my side and mod-wsgi-standalone version is also latest. As per my understanding, this looks like some package dependency issue with latest httpd and mod-wsgi-standalone package. Can you please help me understand what might be going wrong here. 

Thanks

**Comment by GrahamDumpleton** [comment]
If you already have an installed system Apache and are trying to use compiled mod_wsgi.so with it, you should not be using `mod_wsgi-standalone` package. You should only be installing the `mod_wsgi` package.

So do this:

```
pip uninstall mod_wsgi-standalone
pip uninstall mod_wsgi-httpd
pip uninstall mod_wsgi
```

The first should be sufficient, but do all three to be safe.

Whichever works, keep running it again until it says nothing to remove. This will ensure all installed versions are removed.

Then do only:

```
pip install --no-cache-dir mod_wsgi
```

Make sure you use `--no-cache-dir` option so it ignores any prebuilt cashed binaries.

The problem you are having likely is because you are mixing a mod_wsgi.so built against Apache 2.4.48 with system Apache which is older 2.4.46 or 2.4.51.

Also explain better how you are integrating mod_wsgi with the system Apache. In other words, whether installing mod_wsgi.so from Python installation into Apache installation and how you are configuring Apache for mod_wsgi.

**Comment by shishir-22** [comment]
Thanks @GrahamDumpleton using mod_wsgi instead of mod_wsgi-standalone fixed the issue.
