### ISSUE TITLE
Import Error: cannot import name 'encodings' from 'psycopg2._psycopg'

### ISSUE THREAD

**Issue by rhl-it** [GrahamDumpleton/mod_wsgi#753]
Import Error: cannot import name 'encodings' from 'psycopg2._psycopg' ... file path ... /psycopg2/_psycopg.cpython-39-x86_64-linux-gnu.so

I am experiencing this error on:
Debian 11 Bullseye with apache2 (2.4.52), mod_wsgi (4.9.0) (installed with pip into a virtual environment), psycopg2-binary (2.9.2 & 2.9.3) (installed with pip into a virtual environment), python 3.9, Django 4.0
This only causes an error while hosting 2 sites; each site loads correctly and behaves correctly independently, when I try to access the other site, this error shows up in the logs and the website has the 500 internal server error returned.

I have temporarily avoided this error by commenting out the code requiring the encodings import in the extensions.py file. I haven't tested this "solution" with 2.9.3 as it's not really preferable.

NOTE: submitted to psycopg2 as #1414 - resolution is 'Not my problem' they suggested I post here.

**Comment by GrahamDumpleton** [comment]
Sorry for slow reply, I've been on holidays. :-)

This can possibly be caused by trying to use mod_wsgi compiled for one Python version, with a Python virtual environment or Python package binary packages intended for a different Python version.

So double check what the exact version of Python mod_wsgi was compiled for and ensure what you want to use for your code is the same. If using system Apache, ensure that system mod_wsgi package is not installed and accidentally being used.

There have also been problems with psycopg2 binary wheels at times where they do not work properly when not the exact Python version. In this case it is necessary to force psycopg2 to be installed from Python source package and not a binary wheel or system psycopg2 package.

Beyond that I would need to see your Apache configuration where you configure mod_wsgi.

Also ensure that you are using mod_wsgi daemon mode with each application delegated to a separate daemon process group where the main interpreter context is used in each. The latter could be important as psycopg2 could have broken again its ability to run in sub interpreters.

**Comment by rhl-it** [comment]
I am using the mod_wsgi from python in the python environment by editing the LoadModule directive in the apache configuration to load <path to virtual environment>/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-x86_64-linux-gnu.so

the site configuration for the WSGI directives are as follows:
WSGIScriptAlias /<project_home_url> <project wsgi.py>
WSGIDaemonProcess projectname.local python-home=<path to virtual environment> python-path=<path to project wsgi.py>
WSGIProcessGroup  projectname.local

Both websites are hosted on the same server, using the root url to map requests to the separate processes.

I will try building the psycopg2 package from source.  I am currently using the psycopg2-binary version 2.9.2; 2.9.3 is also exhibiting the same issues.

Just want to ensure it isn't an issue with the way I have apache setup.  I haven't changed it for quite a while so there may be a better way to invoke and manage the requests.

**Comment by rhl-it** [comment]
I just tried installing the psycopg2 package (build from source) in my virtual environment and it seemed to install properly.  Still getting the same error.  pip3 install psycopg2 

NOTE: The same edit (removing all reference to 'encodings' in the extentions.py file in the psycopg2 package) has allowed the websites to function normally.

**Comment by GrahamDumpleton** [comment]
As I said before, I would need to see the specific mod_wsgi configuration you are using in the Apache configuration. Your snippet is not everything and not enough to comment on whether you have things set up correctly.

I need to see configuration for both sites, including how they sit relative to each other. That is, are they inside of the same `VirtualHost` etc? Are you using multiple `WSGIDaemonProcess` directives? Are any of the directives inside of any `Location` or `Directory` directives etc. It is better to show actual URL path, Python home and path etc.

**Comment by rhl-it** [comment]
I didn't think the formatting would turn out like that. This is the wsgi.load file hopefully?

`# LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
LoadModule wsgi_module /var/www/py3env/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-x86_64-linux-gnu.so`

**Comment by GrahamDumpleton** [comment]
You should use:

```
### Project 1 Website ###
<Directory /var/www/project1_v3/project1>
	<Files wsgi.py>
		Require all granted
	</Files>
</Directory>

WSGIDaemonProcess project1.local python-home=/var/www/py3env python-path=/var/www/project1_v3/project1/wsgi.py
WSGIScriptAlias /project1 /var/www/project1_v3/project1/wsgi.py process-group=project1.local application-group=%{GLOBAL}

### Project 2 Website ###
<Directory /var/www/project2_v3/project2>
	<Files wsgi.py>
		Require all granted
	</Files>
</Directory>

WSGIDaemonProcess project2.local python-home=/var/www/py3env/ python-path=/var/www/project2_v3/project2/wsgi.py
WSGIScriptAlias /project2 /var/www/project2_v3/project2/wsgi.py process-group=project2.local application-group=%{GLOBAL}
```

In what you had, because `WSGIProcessGroup` wasn't scoped by appropriate `Directory` context, both WSGI applications were running in daemon process group `project2.local` as that was the last `WSGIProcessGroup` seen.

The `psycopg2` package looks to be broken for use in sub interpreters again, whereby it will fail if used in two different interpreter contexts at the same time.

The configuration I show you uses a different method to delegate WSGI applications to the respective daemon process groups using options to `WSGIScriptAlias`, so is harder to make a mistake. The `application-group=%{GLOBAL}` indicates that main interpreter context should be used, which avoids problems with packages that don't work in sub interpreters.

**Comment by rhl-it** [comment]
Thanks Graham, looks like that did the trick!!
