### ISSUE TITLE
DiskCache issue

### ISSUE THREAD

**Issue by aminshah1** [GrahamDumpleton/mod_wsgi#761]
Hi, when there are multiple threads, the process crashes with this logs related to DiskCache. I don't think it's directly related to request timeout as each thread takes <1 sec when run individually. I also checked and it's not related to any cpu/memory limitation.

```
Daemon process request time limit exceeded, stopping process 'localhost:8080'.
Shutdown requested 'localhost:8080'.
Dumping stack trace for active Python threads.
Thread 140691446998784 executing file "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 663, in _execute_with_retry
called from file "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 2412, in reset,
called from file "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 499, in __init__,
...
called from file "/opt/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__,
called from file "/opt/venv/lib/python3.8/site-packages/mod_wsgi/server/__init__.py", line 1514, in handle_request.
```
Storage is a persistent volume on K82 cluster with ReadWriteMany access. 

Any suggestions how to fix it? Thanks.

**Comment by GrahamDumpleton** [comment]
You only need one request to go over the request timeout threshold to be an issue and have the process be forcibly restarted. Although, if multithreaded there is leeway in that the average running time all request threads needs to be above the request timeout threshold for the process to be restarted. Thus if have 5 threads and only 1 got stuck, the process would only get restarted when that 1 request had been stuck for 5 times the request timeout value.

Either way, if that was the only stack trace given, it indicates that the process was restarted because that request got stuck in that function call. What bounds are there on `_execute_with_retry()` as to how many times it will try and what period of time it will run for before giving up?
