### ISSUE TITLE
Breaking out to PDB breaks Django runmodwsgi server since 4.8.0

### ISSUE THREAD

**Issue by MrkGrgsn** [GrahamDumpleton/mod_wsgi#767]
Since mod_wsgi 4.8.0, breaking out to PDB while using the Django `runmodwsgi` command causes the server to become unresponsive. 4.7.1 works okay - I can do normal interactive PDB things - but using the `--isatty` option in 4.7.1 causes the same problem as 4.8.0+.

I am using a simple method of breaking out to PDB: inserting `__import__("pdb").set_trace()` at the desired point in the code.

mod_wsgi>=4.8.0
Python 3.8

**Comment by GrahamDumpleton** [comment]
Will be because of `isatty` change in:

* https://modwsgi.readthedocs.io/en/master/release-notes/version-4.8.0.html#features-changed

This was done to stop Apache being shutdown when the terminal window that `mod_wsgi-express` was running in was resized.

Not sure whether the issue will be use of the sub process, or whether it is because stdin isn't connected to the sub process.

If you want to have a play with trying to get it to work then fiddle around with how the sub process is created.

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/__init__.py#L3696

I'll have a think about it and see whether I can make some time to look at it. One option may be to not do the sub process trick, and do it the old way, if using the ``--enable-debugger`` option. What were the options you were using to ``runmodwsgi``?

FWIW, am surprised anyone was using that feature. :-)

**Comment by MrkGrgsn** [comment]
I suspected it was that `isatty` change, thanks for confirming.  I'll have a look at the sub process creation.

I typically start `runmodwsgi` like this:
```sh
python -Wa manage.py runmodwsgi --reload-on-changes --log-to-terminal --error-log-format '%M'
```
> FWIW, am surprised anyone was using that feature. :-)

I'm embarrassed now 😄 Are you referring to `runmodwsgi` or my debugging tactics?

**Comment by GrahamDumpleton** [comment]
Using pdb inside of Apache/mod_wsgi.

Am actually surprised that pdb worked with those options. I would have expected you to need to use ``--debug-mode`` at least.

Can you try with:

```
pip install -U --no-cache-dir https://github.com/GrahamDumpleton/mod_wsgi/archive/refs/heads/develop.zip
```

When you run it, add the ``--debug-mode`` option.

I have changed it so if using debug mode the sub process is not used.

**Comment by MrkGrgsn** [comment]
That works.  I tested with `runmodwsgi` so I needed to replicate your change to https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/management/commands/runmodwsgi.py#L143.  Thanks for looking into this so promptly! 👍

**Comment by GrahamDumpleton** [comment]
Oh, forgot there was a separate place for runmodwsgi. I will change that as well.

**Comment by GrahamDumpleton** [comment]
Try again with using latest and:

```
pip install -U --no-cache-dir https://github.com/GrahamDumpleton/mod_wsgi/archive/refs/heads/develop.zip
```

**Comment by MrkGrgsn** [comment]
That works for me.

**Comment by GrahamDumpleton** [comment]
Version 4.9.1 of mod_wsgi was release with this change.
