### ISSUE TITLE
 Timeout when reading response headers from daemon process 

### ISSUE THREAD

**Issue by khalilahmed-dev** [GrahamDumpleton/mod_wsgi#769]
Hi there,

I'm using `Django 3.2`, `Python 3.10`, `CentOS 7` stack.

I was able to run mod_wsgi-express and setup my server. The problem occurred when my team cloned the VM assigned a separate IP to it to have two VMs available to setup High Availability there. I logged into my new VM and tried to run mod_wsgi-express server into it but I'm getting the following error:
```

Timeout when reading response headers from daemon process 'localhost:8000': MY_PATH_OF_DEPLOYMENT/htdocs/
```

I used the following command to setup my server:

`mod_wsgi-express setup-server django_wsgi.py --server-root ROOT_PATH_HERE --user apache --group apache --https-port 443  --https-only --server-name MACHINE_IP_HERE --ssl-certificate CERTIFICATE_PATH_HERE --ssl-certificate-key-file KEY_PATH_HERE --include-file DEPLOYMENT_PATH_HERE/ssl.conf`

where ssl.conf includes a simple SSL settings that I want. I've even tried without using SSL and the --include-file parameter but still getting the same error. 

Any help would be appreciated. Thanks !

**Comment by GrahamDumpleton** [comment]
This is more likely pointing at an issue in your WSGI application rather than the mod_wsgi setup. Does this happen for every request, or just sporadically?

As possible means to work out what is wrong, suggesting adding option:

```
--request-timeout=30
```

This will enforce a timeout on requests, which since you are using default of one daemon process with five threads, that once the average running time of all current active requests reaches 30 seconds, the daemon process will be forcibly restarted, unblocking the process (albeit interrupting running requests).

If only one occasional request is blocking (and not every request), because of how the average works, this means it would take 150 seconds for the one request before the forced process restart occurs.

Anyway, the reason for doing it is that when the daemon process is forcibly restarted, mod_wsgi will attempt to dump out to the logs the Python stack traces for each running request. If the issue is that your WSGI application is deadlocking, or is blocked on a backend service, this will give you a clue as to where in the code that is occurring.

**Comment by khalilahmed-dev** [comment]
Thanks, seemed it fixed my issue.
