### ISSUE TITLE
mod_wsgi-express segmentation fault

### ISSUE THREAD

**Issue by hrpatel** [GrahamDumpleton/mod_wsgi#775]
Hi, 

We're seeing a segmentation fault when certain unique URLs are browsed (by a scanner tool). The example below is a boilerplate Django app that we used without modification to reproduce the issue:

`run_wsgi.sh'

```
app_dir="/home/user/work/mymodwsgi3/mysite"

wsgi_command="mod_wsgi-express start-server \
    ${app_dir}/mysite/wsgi.py \
    --port 8080 \
    --enable-gdb \
    --debug-mode \
    --debugger-startup \
    --enable-debugger \
    --python-path /home/user/work/mymodwsgi3/venv/lib/python3.8/site-packages:${app_dir}"

exec ${wsgi_command}
```

URL
```
curl -I localhost:8080/%c0
```

mod_wsgi-express start up and error:

```
 GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/apache2...
(No debugging symbols found in /usr/sbin/apache2)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 14098]
--Return--
> /home/user/work/mymodwsgi3/venv/lib/python3.8/site-packages/mod_wsgi/server/__init__.py(1309)__init__()->None
-> self.activate_console()
(Pdb) 
(Pdb) c
[New Thread 0x7ffff54a9700 (LWP 14101)]
[New Thread 0x7ffff5468700 (LWP 14102)]
[New Thread 0x7ffff5427700 (LWP 14103)]

Thread 3 "apache2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5468700 (LWP 14102)]
wsgi_reload_required (pool=<optimized out>, r=r@entry=0x7ffff6dac0a0, 
    filename=filename@entry=0x7ffff746e0a0 "/tmp/mod_wsgi-localhost:8080:1000/handler.wsgi", module=module@entry=0x7ffff6ee8220, 
    resource=<optimized out>) at src/server/mod_wsgi.c:3859
3859	src/server/mod_wsgi.c: No such file or directory.
```

**Comment by GrahamDumpleton** [comment]
Thanks for the report. I can actually replicate it with a simpler setup. I'll dig into what is going on.

**Comment by GrahamDumpleton** [comment]
So the reason is that a value that gets passed through by Apache looks like:

```
/var/tmp/mod_wsgi-localhost:8000:501/htdocs/�
```

IOW, the last character is that magic encoded character value.

Unfortunately mod_wsgi is passing that as is to Python C API function:

```
args = Py_BuildValue("(s)", resource)
```

which fails with:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 44: invalid start byte
```

Thus the `args` result is `NULL`.

That is okay for the subsequent call to:

```
result = PyObject_CallObject(object, args)
```

as `args` is actually allowed to be `NULL` for that function and indicates no values.

The next line however is:

```
Py_DECREF(args)
```

which crashes as trying to dereference a `NULL` pointer.

I am going to have to think about how to handle this because it is one of those horrible corner cases in WSGI where may have to do a strange bytes/unicode conversion dance. I need to dig through existing mod_wsgi code to find other places where have had similar issues and see what was done.

Also, it perhaps look like the `mod_wsgi-express` wrapper for `reload_required` function is expecting a different argument based on naming, although it may not use it, so something not matching up there either, but that itself is not causing an issue.

As to what situations this occurs, they are:

* Must be using mod_wsgi daemon mode (embedded mode not affected).
* Must be using `mod_wsgi-express` or have supplied a custom `reload_required()` script in a WSGI script file. The latter is extremely unlikely as no one would probably be doing that, so safe to say only affects `mod_wsgi-express`.
* Must be using automatic code reloading (which is the default for `mod_wsgi-express`).
* Decoded URL path must include a byte sequence that cannot be interpreted as a UTF-8 byte sequence.

This can only cause a process crash and there is no way that it could be exploited remotely to do anything else.

Immediate thing to do if concerned about this in a public facing system is to use the `--disable-reloading` with `mod_wsgi-express`. If was a production public facing system you probably don't want reloading enabled anyway.

**Comment by GrahamDumpleton** [comment]
If you want to test with:

```
pip install -U https://github.com/GrahamDumpleton/mod_wsgi/archive/refs/heads/develop.zip
```

you can check out the fix.

I will make a release after I can work out what GitHub actions has changed which has resulted in all my automated compilation checks failing.

**Comment by hrpatel** [comment]
Thanks for the prompt response @GrahamDumpleton!

- Can confirm that the `develop` build fixes the issue _and_ disabling reloading also works around the issue on 4.9.1.

**Comment by GrahamDumpleton** [comment]
Version 4.9.2 was finally released. Been side tracked with work.
