### ISSUE TITLE
apache (with wsgi enabled) restart yields AH00045: child process xxxxx still did not exit, sending a SIGTERM

### ISSUE THREAD

**Issue by TaylanAkdogan** [GrahamDumpleton/mod_wsgi#799]
[with Apache 2.4.52, mod_wsgi 1.94, python 3.10, mod_mpm_event]

Hi,

I am not sure if this is mod_wsgi problem; however, I exhausted almost all possible potential problem points. The problem is as follows:

After starting apache2, if I do not get any request that needs wsgi, I can restart/reload apache2 without any issue.
However, after the first wsgi response (thus a thread is created for it), a reload/restart yields AH00045: child process xxxxx still did not exit, sending a SIGTERM. If it is a restart, the threads are eventually killed by SIGKILL.

However, when MPM decides to terminate spare threads, threads with mod_wsgi won't terminate, and all the DB connections remain open, as new threads are created using WSGI, thus causing lots of problems for resource management.
I stripped down the application to a kind of "hello world" app to ensure it was not due to my application code. Yet, I still can see AH00045 warnings in the log.

Could you please point me to a solution?

Thanks!

**Comment by GrahamDumpleton** [comment]
Can you provide the mod_wsgi configuration you are using? I need to be able to see whether you are using mod_wsgi daemon mode of embedded mode.

Also, does your own Python code create background threads directly, or as a side effect of using third party Python packages?

**Comment by TaylanAkdogan** [comment]
Asking me the configuration file to determine the mode of operation (embedded/daemon) was sufficiently helpful.

I was using the the default wsgi.conf: All lines were commented out. Thus it was effectively blank. My site configuration files (two of them for a single apache, both are using wsgi) were including only WSGIScriptAlias settings pointing the python/wsgi sources. I am using flask (2.2.2) and mysql.connector (8.0.30). I am not sure if they internally use threads. I am NOT using threading in my code. On the other hand, I was facing the same problem even if I do not use any code (to test), but a simple "hello world" response with a few lines of `def application(environ, start_response):` function. Thus, it is not related to the code I am using. mpn-event.conf is as follows:

`<IfModule mpm_event_module>`
`	StartServers            4`
`	ServerLimit		4`
`	MinSpareThreads         20`
`	MaxSpareThreads         40`
`	ThreadLimit             20`
`	ThreadsPerChild         20`
`	MaxRequestWorkers       60`
`	MaxConnectionsPerChild  0`
`</IfModule>`


**Then, after your message above**, I enabled daemon mode with `WSGIRestrictEmbedded On` in wsgi.conf, and added 

                `WSGIScriptAlias /v2 /var/www/api.site/wsgi/api_v2.wsgi`
                `WSGIDaemonProcess test processes=3 threads=20`
                `WSGIApplicationGroup %{GLOBAL}`
                `WSGIProcessGroup test`

lines into my site configuration. It worked. Now, I can restart/reload without any SIGTERM warning. Threads quit without any issue, and open sql connections are closed gracefully.

However, I noticed that all the processes and threads are created immediately with apache start, unlike mpn-event concept. Am I right? Is it something similar to prefork? I tried to measure the performance. Although I noticed a drop in performance, the result is inconclusive at this point.

Does it still make sense to use mpm-event with daemon mode of wsgi? What is the recommended mode for a high frequency flask requests, each requiring lots of SQL using pools of SQL connections: Embedded or Daemon mode?

**Comment by GrahamDumpleton** [comment]
I think you misunderstand a bit how processes/threads are used and how the different Apache MPM types work. It doesn't matter what Apache MPM you are using, but threads in Apache child processes are never created one at a time on demand, nor are individual threads shutdown while the process is still running. What does happen is that Apache will start a number of child processes and `ThreadsPerChild` number of threads are all created at the same time for that process.

If using mod_wsgi embedded mode, then mod_wsgi is running requests handlers in the context of the same Apache child process thread uses by Apache to accept the request. For daemon mode, the Apache child process is proxying the request to the separate mod_wsgi daemon process where it actually gets handled. For mod_wsgi daemon processes, threads are used just like in Apache child processes, that is, a thread pool with required number of threads is created at the time the process is started and are never shutdown, with them kept until the process is shutdown.

I would suggest you read:

* https://modwsgi.readthedocs.io/en/master/user-guides/processes-and-threading.html

and watch:

* https://www.youtube.com/watch?v=H6Q3l11fjU0
* https://www.youtube.com/watch?v=k6Erh7oHvns
* https://www.youtube.com/watch?v=SGleKfigMsk

They may give you a better understanding of what is happening.

Only other thing I can suggest is to try setting directive (at global scope outside of VirtualHost):

```
WSGIDestroyInterpreter Off
```

There are some versions of Python, or could also be due to Python modules used and how threading is used, that causes threading shutdown to not function properly because of ordering issues with how things are cleaned up for Python sub interpreters. That option disables any attempt to try and cleanup the Python interpreter on process shutdown. For more information see changed features in:

* https://modwsgi.readthedocs.io/en/master/release-notes/version-4.9.1.html

**Comment by TaylanAkdogan** [comment]
I think that's it!

>  `WSGIDestroyInterpreter Off`

solved the non-exiting workers at reload/restart in embedded-mode. Now, I can use embedded mode, and reload/restart happens (when requested) without any hitch.

Thank you for clarification of the embedded/daemon modes. Now it makes more sense. I knew that threads were not created one-by-one but some number of threads per process were created at once. However, I didn't know (or was not sure) that daemon mode creates its own processes for each sites the apache is configured for. That explains the difference between the number of processes I see at each mode (4 [1+3] vs 9 [1+3*3] ).

I will try to benchmark the performance for each mode (for my application) to choose the mode of operation. However, that is secondary to the reload/restart issue. I consider that the issue is solved for me!

Thank you for your support, and thank you for wsgi!

Kind regards.
