### ISSUE TITLE
Deploying multiple Flask API in production using WSGI

### ISSUE THREAD

**Issue by alexgg94** [GrahamDumpleton/mod_wsgi#803]
Some months ago I deployed my first Flask API using WSGI, now I'm trying to deploy my second one pretty much using the same configuration as the first one. Both of them would use the same virtualenv (invoicenet 3.8), but for the second API I had to install some more packages, one of them being python-docx.

Here are my configuration files:

**app.conf** My first API, still working as expected:
```
Define PROJECT_PATH /var/www/Ebisu/Standalone/

Listen 5000
#WSGISocketPrefix /var/run/wsgi
<virtualhost *:5000>
    TimeOut 300
    # wsgi settings
    WSGIDaemonProcess apache user=apache socket-user=apache python-path=${PROJECT_PATH}:/var/www/Ebisu/Standalone/invoicenet3.8/lib/python3.8/site-packages
    WSGIProcessGroup apache
    WSGIScriptAlias / ${PROJECT_PATH}/app.wsgi
    WSGIApplicationGroup %{GLOBAL}
    # map server side static directory to {ip or domain_name}/static
    Alias /static  ${PROJECT_PATH}/static

    # allow all requests to access this project file
    <Directory ${PROJECT_PATH}/app.wsgi/>
        Require all granted
    </Directory>
    # set log saved path
    ErrorLog /var/www/Ebisu/log/error.log
    CustomLog /var/www/Ebisu/log/access.log combined
</virtualhost>

```

**pamo.conf** My second API. While they seem to share virutalenv, I keep on getting (ModuleNotFoundError: No module named 'docx'). Just to clarify, running this api using invoicenet3.8 virtualenv from command line, works as expected:
```
# variable which is your project path
Define PROJECT_PATH /var/www/Pamo/WordToTablesAPI/

Listen 5020
#WSGISocketPrefix /var/run/wsgi
<virtualhost *:5020>
    TimeOut 300
    # wsgi settings
     WSGIDaemonProcess pamo user=apache socket-user=apache python-path=${PROJECT_PATH}:/var/www/Ebisu/Standalone/invoicenet3.8/lib/python3.8/site-packages
    WSGIProcessGroup pamo
    WSGIScriptAlias / ${PROJECT_PATH}/app.wsgi
    WSGIApplicationGroup %{GLOBAL}
    # map server side static directory to {ip or domain_name}/static
    Alias /static  ${PROJECT_PATH}/static

    # allow all requests to access this project file
    <Directory ${PROJECT_PATH}/app.wsgi/>
        Require all granted
    </Directory>
    # set log saved path
    ErrorLog /var/www/Pamo/log/error.log
    CustomLog /var/www/Pamo/log/access.log combined
</virtualhost>
```

I have been also playing with python-path without site-packages and adding python-home but it is not working for me.
My guess is there has to be something wrong with python-path on the second api. But I was not able to get it working.

**Comment by GrahamDumpleton** [comment]
You should never reference `site-packages` directly in the way you are doing it. You should use `python-home` for location of the virtual environment instead so try it again. For how to setup use of a virtual environment correctly, see:

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

Am also a bit worried that how you are using `Define` directive will not work. Apache doesn't always process things sequentially and only the last instance of a directive will apply. So all uses of `${PROJECT_PATH}` may use only the last set value for that. Try using the explicit path rather than a variable. That or use instead:

* https://httpd.apache.org/docs/2.4/mod/mod_macro.html

**Comment by GrahamDumpleton** [comment]
It is quite possible the problem is that your mod_wsgi is compiled for a different version of Python than the virtual environment was created using. You can't mix Python versions like that. Verify what version of Python mod_wsgi was compiled for.

* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use

**Comment by alexgg94** [comment]
Thanks Graham, I'm going to test it during this weekend. 

In case I have multiple python virtualenvs versions (3.8 and 2.7 for instance) for my already deployed flask APIs, what would be the best python version for mod_wsgi compilation?

**Comment by GrahamDumpleton** [comment]
If you have applications that will only work under Python 2.7 then you would need to run those under a separate server instance as the one Apache instance would only be able to host Python 3.8.

Where needing to support multiple Python versions and you can't use different machines to host them, one option is to run `mod_wsgi-express` for the application requiring one Python version and put that behind the main Apache (setup for other Python version) with it serving as a proxy to the `mod_wsgi-express` instance.

**Comment by alexgg94** [comment]
Thanks for the help Graham. Got sidetracked by some other issues. I'll be right back at it once I'm done. Closing the issue for the moment.
