### ISSUE TITLE
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding

### ISSUE THREAD

**Issue by Retooled** [GrahamDumpleton/mod_wsgi#809]
Hi Graham,

Greetings!

I'm trying to learn python and have successfully created an application based on the Django tutorial available in MDN.  Next step in my learning is to be able to run the application using Apache and mod_wsgi.  Have successfully installed Apache and 'It works".  However, two things happen when I added the python-related information to httpd.conf file.  These are

1.  Apache service won't start/restart and is always in stopped status
2. If I run httpd.exe interactively, the django application doesn't load

Hope it's not too much to ask for assistance in checking what is lacking in my code.  Attached is my settings.py, wsgi.py and httpd.conf files.

[httpd.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/10154576/httpd.conf.txt)
[settings.py.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/10154591/settings.py.txt)
[wsgi.py.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/10154592/wsgi.py.txt)
[error.log](https://github.com/GrahamDumpleton/mod_wsgi/files/10154594/error.log)

Thanks in advance for the help.  Appreciate.

**Comment by GrahamDumpleton** [comment]
What happens if instead of setting the following:

```
WSGIPythonHome "C:/Users/Anton/AppData/Local/Programs/Python/Python310/"
WSGIPythonPath "C:/Users/Anton/Documents/Dad/PythonVirtual/lib/site-packages/"
```

you use:

```
WSGIPythonHome "C:/Users/Anton/Documents/Dad/PythonVirtual"
```

The `WSGIPythonHome` directive should refer to the root of the Python virtual environment if one is used. The `WSGIPythonPath` directive is only needed if needing to refer to Python modules/packages as part of a project directory. One should never use `WSGIPythonPath` to refer to a `site-packages` directory and doing so indicates you are something wrong.

Sorry for slow reply, have been travelling the last couple of weeks.

**Comment by Retooled** [comment]
Hello Graham,

First of all, thank you very much for responding to my request.  Appreciate.

Have done as instructed above and, unfortunately, still not able to start the Apache service successfully with the related python codes included.  Attached is the latest error log and the latest httpd.conf file.

[errorlogv2.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/10223995/errorlogv2.txt)
[httpd.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/10224013/httpd.conf.txt)

**Comment by GrahamDumpleton** [comment]
Ensure Apache log level is set to "info" and not just "error" so that more information from mod_wsgi can be logged so can validate what is occurring.

```
LogLevel info
```

FWIW, Python virtual environments on Windows have been broken for embedded systems for quite a long time and has as far as I know never been fixed. As a result mod_wsgi has to use some hacks to try and get them to work. It is quite possible they have made further changes which break things even more such that the workaround no longer works, or they may have fixed things, causing the workaround to not work.

The extra logging may help to work out what is happening. Otherwise we can try and disable the workaround code and see if what should be the correct code now works again.

What is the exact patch level version of Python you have installed?

**Comment by Retooled** [comment]
Hello Graham,

Thanks again for the assistance.  Found a resource with the same problem (https://stackoverflow.com/questions/38132755/importerror-no-module-named-encodings) and was able to solve the Apache error I encountered.  Added PYTHONHOME" and "PYTHONPATH" as part of my environment variables and it worked.  Was able to see the python _The install work successfully screen_  with the apache webserver active.  Am reviewing my application setup as it seems it hangs whenever I try launching application.

Thank you very much for the assistance.  Hope you don't mind me reaching out again should I get stuck with python/django.  By the way, Django version I'm using is 4.0.6

Merry Christmas to you and our family.
