### ISSUE TITLE
pip3.9 install -v mod_wsgi-httpd fails

### ISSUE THREAD

**Issue by netops97** [GrahamDumpleton/mod_wsgi#811]
Mr. Dumpleton,

I'm working with RHEL 8.4 and I really want to use mod_wsgi-express so I can use your version of apache configured for production, so I'm trying to pip install mod_wsgi-httpd first in a private virtual environment before installing mod_wsgi. This fails complaining that "setuptools" is not in the environment when pip3.9 list confirms setuptools 50.3.2 is present. Do you know why the install can't see "setuptools"?

```
pip3.9 install -v mod_wsgi-httpd

  Running command python setup.py egg_info
  apr-1.7.0/
  apr-1.7.0/emacs-mode
  apr-1.7.0/passwd/
  apr-1.7.0/passwd/apr_getpass.c
         |
         |
  apr-1.7.0/apr.dsw
  apr-1.7.0/libapr.dep
  sh: ./configure: Permission denied
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/tmp/pip-install-n_gw8gzp/mod-wsgi-httpd_9584b66f1200497cbec22a5db676a                        507/setup.py", line 75, in <module>
      raise RuntimeError('Failed to build APR.')
  RuntimeError: Failed to build APR.
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem wit                        h pip.
  full command: /var/www/env_netops/bin/python3.9 -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that di                        rectly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.p                        y` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following                         warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available i                        n "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-n_gw8gzp/mod-wsgi-httpd_9584b66f12004                        97cbec22a5db676a507/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_in                        fo --egg-base /tmp/pip-pip-egg-info-uvoxphrd
  cwd: /tmp/pip-install-n_gw8gzp/mod-wsgi-httpd_9584b66f1200497cbec22a5db676a507                        /
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by GrahamDumpleton** [comment]
If you want to use `mod_wsgi-express` then use:

```
pip3.9 install -v mod_wsgi
```

You should not use the `mod_wsgi-httpd` package unless you absolutely have no other choice and can't install the system Apache httpd package from some strange reason.

Why can't you install the system package for Apache httpd and use it? Even with the system Apache `mod_wsgi-express` will work and using system Apache httpd is the preferred approach.

That said, my guess is that the error:

```
sh: ./configure: Permission denied
```

may be due to SELinux restrictions on executing programs located in system `/tmp` or `/var/tmp` directories. From memory that is where `pip` unpacks stuff and believe I have seen before one person who had really restrictive SELinux permissions that prevented execution of programs out of tmp directories.

I think the `setuptools` error is a furphy and the real issue is inability to execute the generated `configure` script.

**Comment by netops97** [comment]
I do have the system version: Apache/2.4.37 httpd package installed. I've had no luck serving a Django application so I decided to pip install mod_wsgi-http to see if I could breakthrough that way. As root with mod-wsgi 4.9.3
 installed in a private virtual environment, running mod_wsgi-express start-server now fails as follows:
 PermissionError: [Errno 13] Permission denied: '/tmp/mod_wsgi-localhost:8000:0/apachectl'

Note the following:
SELinux status:                 disabled

drwxr-xr-x.  4 root    root     170 Dec 27 00:10 mod_wsgi-localhost:8000:0

ls -atl mod_wsgi-localhost\:8000\:0/
total 44
drwxrwxrwt. 98 root root  4096 Dec 27 19:18 ..
-rwxr-xr-x   1 root root  2579 Dec 27 19:12 apachectl

I'm guessing here, is an "apache' user id running mod_wsgi-express blocked from accessing tmp because everything is owned by root?

Thank you for your prompt response to this issue.

**Comment by GrahamDumpleton** [comment]
It is probably because you ran some things as root and then switched to no root user.

Remove the directory `/tmp/mod_wsgi-localhost:8000:0` as root and then run as the non root user.

If you had mod_wsgi-httpd installed in any way, make sure you pip uninstall it before attempt to install just mod_wsgi else it can cause problems.
