### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by Erispoe974** [GrahamDumpleton/mod_wsgi#844]
Hi,
 I'm trying to install mod_wsgi for running with Apache server V2.4.54.
After the pip installation, i try to check if it works with _mod_wsgi-express start-server_  but i got an error : 

Server URL         : http://localhost:8000/
Server Root        : C:/Users/ADMINI~1/AppData/Local/Temp/2/mod_wsgi-localhost-8000-Administrateur
Server Conf        : C:/Users/ADMINI~1/AppData/Local/Temp/2/mod_wsgi-localhost-8000-Administrateur/httpd.conf
Error Log File     : C:/Users/ADMINI~1/AppData/Local/Temp/2/mod_wsgi-localhost-8000-Administrateur/error_log (warn)
Operating Mode     : daemon
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : fr_FR.cp1252

WARNING: The ability to use the start-server option on Windows
WARNING: is highly experimental and various things don't quite
WARNING: work properly. If you understand a lot about using
WARNING: Python on Windows and Windows programming in general,
WARNING: and would like to help to get it working properly, then
WARNING: you can ask about Windows support for the start-server
WARNING: option on the mod_wsgi mailing list.

Traceback (most recent call last):
  File "C:\Program Files\Python311\Scripts\mod_wsgi-express-script.py", line 33,
 in <module>
    sys.exit(load_entry_point('mod-wsgi==4.9.4', 'console_scripts', 'mod_wsgi-express')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\mod_wsgi\server\__init__.py", line 3839, in main
    cmd_start_server(args)
  File "C:\Program Files\Python311\Lib\site-packages\mod_wsgi\server\__init__.py", line 3672, in cmd_start_server
    subprocess.call([executable]+httpd_arguments)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

Could you help me ?
My root apache directory : C:\wamp64\bin\apache\apache2.4.54.2

Thx for your help.
Regards,
Alexandre

**Comment by GrahamDumpleton** [comment]
As the message which is displayed indicates when it is started, `mod_wsgi-express start-server` on Windows isn't really supported and doesn't necessarily work. You need to manually configure Apache httpd on Windows to use the mod_wsgi module.

**Comment by Erispoe974** [comment]
Hi, Thanks for your ansswer.
It's what i'have done. And since it didn't work, I tried running this command to understand.
Because, when i restart apache with mod_wsgi, none of my websites are working anymore, I have a 500 error

**Comment by GrahamDumpleton** [comment]
What are the error messages in the Apache error log?

**Comment by Erispoe974** [comment]
Here is my configuration in httpd.conf : 
_# Django Project
LoadFile "C:/Program Files/Python311/python311.dll"
LoadModule wsgi_module "C:/Program Files/Python311/Lib/site-packages/mod_wsgi/server/mod_wsgi.cp311-win_amd64.pyd"
WSGIPythonHome "C:/Program Files/Python311"
WSGIScriptAlias / "C:/wamp64/www/BioSite_33/src/wsgi.py"
WSGIPythonPath "C:/wamp64/www/BioSite_33/"_

I have no really errors : 
_[Wed Jun 28 13:52:02.043268 2023] [mpm_winnt:notice] [pid 2136:tid 252] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Wed Jun 28 13:52:04.090160 2023] [mpm_winnt:notice] [pid 4104:tid 268] AH00364: Child: All worker threads have exited.
[Wed Jun 28 13:52:09.558961 2023] [mpm_winnt:notice] [pid 2136:tid 252] AH00430: Parent: Child process 4104 exited successfully.
[Wed Jun 28 13:52:58.005595 2023] [mpm_winnt:notice] [pid 4640:tid 252] AH00455: Apache/2.4.54 (Win64) PHP/8.0.26 mod_fcgid/2.3.10-dev mod_wsgi/4.9.4 Python/3.11 configured -- resuming normal operations
[Wed Jun 28 13:52:58.005595 2023] [mpm_winnt:notice] [pid 4640:tid 252] AH00456: Apache Lounge VS16 Server built: Nov  2 2022 10:09:33
[Wed Jun 28 13:52:58.005595 2023] [core:notice] [pid 4640:tid 252] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.54.2\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.54.2'
[Wed Jun 28 13:52:58.005595 2023] [mpm_winnt:notice] [pid 4640:tid 252] AH00418: Parent: Created child process 2596
[Wed Jun 28 13:52:58.552476 2023] [mpm_winnt:notice] [pid 2596:tid 268] AH00354: Child: Starting 64 worker threads._

**Comment by GrahamDumpleton** [comment]
Ensure `LogLevel` in Apache is set to at least `info` and not `err` or `warn`. This will give extra information about what mod_wsgi is doing and whether it is even attempting to load your WSGI application. Because you have mod_fcgid loaded, it could be highjacking the request, as could mod_cgi depending on what other config you have.

**Comment by GrahamDumpleton** [comment]
The WSGI application is at least being loaded. The fact that there is no trace back though indicates that if the 500 error is being generated as a result of the WSGI application, that the web framework you are using is internally capturing the error and turning it into a HTTP 500 response itself, without logging the details.

This lack of logging for internal code errors and return a HTTP 500 response is what some Python web frameworks will do unless you specifically configure them to log details of the exceptions. What Python web framework are you using?

**Comment by Erispoe974** [comment]
Thanks for your answers.
My framework : Django

Regards,
Alexandre

**Comment by GrahamDumpleton** [comment]
Have a read of:

* https://www.agiliq.com/blog/2017/12/configure-django-log-exceptions-production/

At the minimum, set Django DEBUG mode on to work out what the error is.

**Comment by PantaneiroCG** [comment]
I'm in a real SAGA when finishing a registration using Django and trying to put it on a local Windows server (Intranet). I followed a tutorial and went through some problems along the way and managed to get to Apache's httpd.conf file configuration.

I informed all the paths (path) requested, on the first attempt it gave a syntax error and the Apache server did not start, I commented the line where the error occurred and it passed, and the server started, but all the applications that ran on apache stopped working and even my django didn't work either.

Lines included at the end of the httpd.conf file:

Alias /robots.txt C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/static/robots.txt Alias /favicon.ico C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/static/favicon.ico

Alias /media/ C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/media/media Alias /static/ C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/static/

<Directory C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/static> Require all granted

<Directory C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/media/media> Require all granted

LoadFile "C:/Python311/python311.dll" LoadModule wsgi_module "C:/xampp/htdocs/Cadastro/env/Lib/site-packages/mod_wsgi-4.9.5.dev1-py3.11-win-amd64.egg/mod_wsgi /server/mod_wsgi.cp311-win_amd64.pyd" WSGIPythonHome "C:/xampp/htdocs/Cadastro/env" WSGIScriptAlias / C:/xampp/htdocs/Cadastro/cad_project_users/cad_project_users/wsgi.py

WSGIPythonPath / C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/projeto_cad_usuarios/ <Directory C:/xampp/htdocs/Cadastro/projeto_cad_usuarios/projeto_cad_usuarios> Require all granted

If you can help me out, I would greatly appreciate it. I have no idea what to do from now on, because it doesn't give an error, Apache simply starts, but no longer runs any page with these lines included, but if I comment them out, it goes back to working as before, minus my registration in django.
