### ISSUE TITLE
mod_wsgi.Log proxy for sys.stderr fails on call to fileno()

### ISSUE THREAD

**Issue by powderflask** [GrahamDumpleton/mod_wsgi#85]
Struggling a bit to comprehend the issue here, so please bear with me.  I've boiled this down to a simple test case using the wsgi "hello world" script:

    import sys

    def application(environ, start_response):
        status = '200 OK'
        output = 'Hello World!'

        output += "\nsys.stderr type:" + str(type(sys.stderr))

        if hasattr(sys.stderr, 'fileno'):
            if callable(sys.stderr.fileno):
                output += "\nabout to call fileno()"
                i = sys.stderr.fileno()

        response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
        start_response(status, response_headers)

        return [output]

The call to sys.stderr.fileno() raises an AttributeError:
> [Tue Jul 28 15:54:11.587280 2015] [:error] [pid 28953] [remote 172.16.200.139:50149] mod_wsgi (pid=28953): Exception occurred processing WSGI script '/.../Projects/wsgitest/test.wsgi'.
> [Tue Jul 28 15:54:11.604766 2015] [:error] [pid 28953] [remote 172.16.200.139:50149] Traceback (most recent call last):
> [Tue Jul 28 15:54:11.605343 2015] [:error] [pid 28953] [remote 172.16.200.139:50149]   File "/.../Projects/wsgitest/test.wsgi", line 19, in application
> [Tue Jul 28 15:54:11.605368 2015] [:error] [pid 28953] [remote 172.16.200.139:50149]     i = sys.stderr.fileno()
> [Tue Jul 28 15:54:11.605424 2015] [:error] [pid 28953] [remote 172.16.200.139:50149] AttributeError: 'mod_wsgi.Log' object has no attribute 'fileno'
 
This issue arose in a package I was using (django-wkhtml-pdf) that needs to do some file i/o - not sure why they need to access stderr.fileno(), but they do.    It seems like the proxy for the TextIOWrapper object is broken in some way, but now I'm in way over my head...

**Comment by powderflask** [comment]
Oops - no running most recent mod_wsgi.  I will upgrade to latest release and report back.  Sorry for raising alarm too early.

**Comment by powderflask** [comment]
OK - built and installed latest mod_wsgi release (4.4.13) - everything else working fine, but test case still failing.  Here is the server error.log that shows Apache resuming and then the failed test...

[Tue Jul 28 16:41:59.023379 2015] [mpm_prefork:notice] [pid 40022] AH00163: Apache/2.4.7 (Ubuntu) mod_jk/1.2.37 OpenSSL/1.0.1f mod_wsgi/4.4.13 Python/3.4.0 configured -- resuming normal operations
[Tue Jul 28 16:41:59.023424 2015] [core:notice] [pid 40022] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 28 16:42:03.130217 2015] [wsgi:error] [pid 40026] [remote 172.16.200.139:10553] mod_wsgi (pid=40026): Exception occurred processing WSGI script '/.../Projects/wsgitest/test.wsgi'.
[Tue Jul 28 16:42:03.130397 2015] [wsgi:error] [pid 40026] [remote 172.16.200.139:10553] Traceback (most recent call last):
[Tue Jul 28 16:42:03.130753 2015] [wsgi:error] [pid 40026] [remote 172.16.200.139:10553]   File "/.../Projects/wsgitest/test.wsgi", line 19, in application
[Tue Jul 28 16:42:03.130777 2015] [wsgi:error] [pid 40026] [remote 172.16.200.139:10553]     i = sys.stderr.fileno()
[Tue Jul 28 16:42:03.130833 2015] [wsgi:error] [pid 40026] [remote 172.16.200.139:10553] AttributeError: 'mod_wsgi.Log' object has no attribute 'fileno'

**Comment by GrahamDumpleton** [comment]
My tests were with Python 2.7.So maybe it is a Python 3.4 issue.

**Comment by GrahamDumpleton** [comment]
Yep. Confirmed for 3.4.

```
(py34) grumpy-old-man:tmp graham$ mod_wsgi-express start-server fileno.wsgi --log-to-terminal
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:502
Server Conf        : /tmp/mod_wsgi-localhost:8000:502/httpd.conf
Error Log File     : /dev/stderr (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_AU.UTF-8
[Wed Jul 29 09:56:46.808530 2015] [core:warn] [pid 80913] AH00098: pid file /tmp/mod_wsgi-localhost:8000:502/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Wed Jul 29 09:56:46.809519 2015] [mpm_prefork:notice] [pid 80913] AH00163: Apache/2.4.10 (Unix) mod_wsgi/4.4.13 Python/3.4.1 configured -- resuming normal operations
[Wed Jul 29 09:56:46.809543 2015] [core:notice] [pid 80913] AH00094: Command line: 'httpd (mod_wsgi-express)  -f /tmp/mod_wsgi-localhost:8000:502/httpd.conf -D FOREGROUND'
[Wed Jul 29 09:56:57.913180 2015] [wsgi:error] [pid 80915] [remote ::1:0] mod_wsgi (pid=80915): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:8000:502/htdocs/'.
[Wed Jul 29 09:56:57.913315 2015] [wsgi:error] [pid 80915] [remote ::1:0] Traceback (most recent call last):
[Wed Jul 29 09:56:57.914101 2015] [wsgi:error] [pid 80915] [remote ::1:0]   File "/private/tmp/py34/lib/python3.4/site-packages/mod_wsgi/server/__init__.py", line 1300, in handle_request
[Wed Jul 29 09:56:57.914111 2015] [wsgi:error] [pid 80915] [remote ::1:0]     return self.application(environ, start_response)
[Wed Jul 29 09:56:57.914229 2015] [wsgi:error] [pid 80915] [remote ::1:0]   File "/private/tmp/fileno.wsgi", line 12, in application
[Wed Jul 29 09:56:57.914237 2015] [wsgi:error] [pid 80915] [remote ::1:0]     i = sys.stderr.fileno()
[Wed Jul 29 09:56:57.914259 2015] [wsgi:error] [pid 80915] [remote ::1:0] AttributeError: 'mod_wsgi.Log' object has no attribute 'fileno'
```

**Comment by powderflask** [comment]
Thanks so much Graham - good to know.  I will patch my version of django-wkhtmltopdf for now and carry on (no going back to 2.7 for us now :-)    Sorry, I should have used the developers maillist, to discuss this with you first.  Really appreciate your fast response.

**Comment by GrahamDumpleton** [comment]
No problem. On visual code review I am a bit mystified as to why hasattr() is succeeding. The Python C object for mod_wsgi.Log doesn't define either tp_getattr or tp_getattro slots, nor is fileno listed in method list or attribute list. I will have to do some digging.

**Comment by GrahamDumpleton** [comment]
The problem with Python 3 appears to be because a ``sys.stderr`` object actually needs to be an instance of ``<class '_io.TextIOWrapper'>`` for things to work properly. Thus this actually wraps the mod_wsgi ``Log`` object.

The ``TextIOWrapper`` class has a ``fileno`` attribute and will always pass the ``hasattr()`` check even though the wrapped IO object it uses may not have that attribute. Thus when you access ``fileno`` and it in turn attempts to access the ``fileno`` attribute of the wrapped IO object, as it doesn't exist it will fail.

This is one of those cases where in practice one should not rely on ``hasattr()`` checks. Instead you should follow the 'it is better to ask forgiveness than permission' mantra. That is, don't use ``hasattr()`` and simply access ``fileno`` and if that fails with an ``AttributeError`` then assume that it doesn't exist.

So there is nothing in mod_wsgi that I can do about this. Any code which acts on either ``sys.stdin``, ``sys.stdout`` and ``sys.stderr`` has to be tolerant of this sort of thing.

There used to be a similar issue when people were doing ``sys.stdin`` checks and how they decided you were working with an interactive terminal. After a lot of education of affected packages those third party packages got updated to do things the correct way. That is, even then it wasn't a mod_wsgi issue as in those cases the way the Python documentation read indicated that what mod_wsgi was doing was correct.

I can't recollect if this problem has specifically come up with ``sys.stdout`` and ``sys.stderr`` previously in Python 3 or not.

Actually, now reading the Python 3 documentation for the ``io`` module, it almost looks like ``TextIOWrapper`` isn't even adhering to the documentation, unless it is expecting the wrapped IO object to behave in a certain way. Specifically the documentation says:

```
fileno()
Return the underlying file descriptor (an integer) of the stream if it exists. An IOError is raised if the IO object does not use a file descriptor.
```

In this case the IO object doesn't even have a ``fileno`` attribute, yet it is propagating an ``AttributeError`` rather than catching that and propagating an ``IOError`` as documented that should probably occur.

Anyway, the documentation is clear that ``fileno()`` can raise an exception where the idea of a ``fileno`` isn't value.

I would suggest at this point that any code check for both ``IOError`` and ``AttributeError``, or perhaps even just ``Exception`` to be safe.

I will think about it some more, but this actually looks like a bug in ``TextIOWrapper`` of Python standard library that it is allowing ``AttributeError`` to be propagated and not ensure ``IOError`` is raised instead.

**Comment by GrahamDumpleton** [comment]
I think the easiest, and may even be the correct solution as far as mod_wsgi is concerned, is that under Python 3, the ``LogObject`` provide  ``fileno()`` method, but for it to raise an ``IOError`` to indicate it isn't valid. This will satisfy the documented behaviour of ``TextIOWrapper``.

This may be the ultimate answer as the IO object, ie., ``LogObject`` is actually meant to be an instance of ``IOBufferedBase``, which in turn is derived from ``IOBase``, but it isn't. The ``IOBase`` requires a file ``fileno()`` method and likely that it raise ``IOError`` if there isn't one. So mod_wsgi should emulate that.

This wasn't an issue in Python 2 as ``sys.stderr`` there was a file like object and file like objects weren't required to have a ``fileno`` method. Thus code was meant to be tolerant of that which was what that original ``fileno`` check using ``hasattr()`` was for.

What code should likely no do to be compatible with both Python 2 and 3 is to do:

```
if hasattr(sys.stderr, 'fileno'):
    try:
        fd = sys.stderr.fileno()
    except IOError:
        ...
    else:
        ...
```

The problem right now is that how mod_wsgi is working means that as well as ``IOError`` you are going to have to catch ``AttributeError`` as well.

I will fix up mod_wsgi so that ``IOError`` is raised as seems to be required behaviour in Python 3.

**Comment by GrahamDumpleton** [comment]
Worth noting is that in Python 3.3, ``IOError`` actually went away, or at least as a unique exception type. With that Python version ``IOError`` became an alias for ``OSError``.

```
Changed in version 3.3: EnvironmentError, IOError, WindowsError, VMSError, socket.error, select.error and mmap.error have been merged into OSError.
```

One should still check for ``IOError`` though rather than ``OSError`` as for Python older than 3.3, ``IOError`` has no inheritance relationship with ``OSError``.

**Comment by GrahamDumpleton** [comment]
In mod_wsgi 4.4.14, under Python 3, ``fileno()`` has been added, but when called will raise an ``IOError`` as documented is required.
