### ISSUE TITLE
Cannot load Module 'django' 

### ISSUE THREAD

**Issue by unni-louis** [GrahamDumpleton/mod_wsgi#870]
Hi Graham,
I have a issue with my WSGI setup in
Orcale Linux version 8.8
Python version 3.11.5
mod_wsgi built  mod_wsgi-4.9.4.tar with apxs and python3.11.5
Apache error log : AH00489: Apache/2.4.37 (Oracle Linux) mod_wsgi/4.9.4 Python/3.11 configured -- resuming normal operations
10.141.32.60:60026] File "/var/www/html/ib_mig/vysfin/wsgi.py", line 12, in <$
10.141.32.60:60026] from django.core.wsgi import get_wsgi_application
t 10.141.32.60:60026] ModuleNotFoundError: No module named 'django'
[client 10.141.32.60:60028] AH01630: client denied by server configuration: /var/$
[client 10.141.32.60:60283] AH01276: Cannot serve directory /var/www/html/ib mig/:$
nt 10.141.32.60:54240] mod_wsgi (pid=406445): Failed to exec Python script file /$ ent 10.141.32.60:54240] mod wsgi (pid=406445): Exception occurred processing WSGI s$
ent 10.141.32.60:54240] Traceback (most recent call last):
ent
10.141.32.60:54240] File "/var/www/html/ib_mig/vysfin/wsgi.py", line 12, in <$
Lent 10.141.32.60:54240] from django.core.wsgi import get wsgi application
ient 10.141.32.60:54240] ModuleNotFoundError: No module named 'django'

Please help with the configuration.

**Comment by GrahamDumpleton** [comment]
Your configuration is likely wrong, but since you don't provide it, it is hard to guess. Can you provide the Apache/mod_wsgi configuration you used?

Make sure you refer to the following documents as well and make sure you are following what they say:

* https://docs.djangoproject.com/en/4.2/howto/deployment/wsgi/modwsgi/
* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

**Comment by unni-louis** [comment]
Hi Graham
Thanks for the links.
Configuration had a extra 's' in the python path, correcting it has made everything work.
