### ISSUE TITLE
Error in Makefile:22: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by Gnarlodious** [GrahamDumpleton/mod_wsgi#874]
MacOS 14.3, building version 5.0.0 I see:
```
mod_wsgi-5.0.0:make
Makefile:22: *** missing separator.  Stop
```.

**Comment by GrahamDumpleton** [comment]
Note that the configure/make/make install method and configuring the macOS system Apache httpd configuration to load mod_wsgi will not work due to their code signing requirements for Apache modules.

You also can't use upstream Apache httpd source from the ASF as the Apache runtime libraries are still as far as I know broken on last few macOS versions and there has been no release of APR to address the problem that I have seen.

If wanting to use macOS and the configure/make/make install method, you must use Apache httpd from Homebrew.

The alternative is to use pip install method and use mod_wsgi-express instead. This will work with macOS supplied Apache httpd, but you are running your own instance which is distinct from the instance the OS runs.

That all said, to help with the error, I would need to see the generated Makefile created after running configure so I can see what is at that line number in the Makefile.
