### ISSUE TITLE
Allow mod_wsgi to leverage capabilities(7) on Linux and privileges(5) on Solaris

### ISSUE THREAD

**Issue by drewfisher314** [GrahamDumpleton/mod_wsgi#88]
Currently, mod_wsgi, does not allow WSGIDaemonProcess to specify uid/gid if Apache was not started as root.  Running Apache as root is not typically done in today's OSes, so this restriction forces admins to have to resort to tricks with directory permissions, group memberships, etc. in order to get WSGI applications to access filesystem entries not necessarily accessible by the default Apache user.

For Linux, it's the CAP_SETUID permission.  For Solaris it's proc_setuid.

**Comment by GrahamDumpleton** [comment]
My first suggestion would be that you should not be trying to do this within a traditional Apache installation. You would be better off using mod_wsgi-express and run the whole thing as the target user from the outset. If sites need to bind port 80, then use nginx or haproxy and proxy to the mod_wsgi-express instances. This would be a better separation and not require special operating system features.

This sort of scenario is going to be more prevalent as the move to containers happens and when run in a container such special features as you talk about aren't needed at all.

So I will research the topic, but the effort involved may not be worth it if container based deployment is going to win out.

**Comment by GrahamDumpleton** [comment]
A further problem with this is that to enable this sort of functionality, the privilege has to be set on the Apache binary itself. This would be dangerous.

The ability to set the user would only be able to be done for daemon mode, leaving open that a restrictive uid would not be set for the Apache child worker processes themselves as mod_wsgi could not do that for those processes really as those processes are really owned and controlled by Apache and not mod_wsgi. This means that any Python code running under embedded mode could arbitrarily set the uid themselves. Same for any languages loaded by other Apache modules.

In addition to CAP_SETUID, you would also need CAP_NET_BIND_SERVICE, to allow Apache to bind to port 80. Because there is no restrictions on what ports, then arbitrary Python code could bind to other privileged ports as well.

Maybe I don't understand how it all works, but in all, it just seems a dangerous thing to allow, in particular if allowing untrusted code to run under Apache/mod_wsgi.

**Comment by GrahamDumpleton** [comment]
Closing this as don't believe it is practical to implement because of how mod_wsgi is embedded in Apache. Suggest using containerised deployment platform instead.
