### ISSUE TITLE
mod wsgi install from source code

### ISSUE THREAD

**Issue by heenameena** [GrahamDumpleton/mod_wsgi#89]
I have following version installed:
O.S - RHEL 6.x
Python 3.4.3 :: Anaconda 2.3.0 (64-bit)
Apache 2.2.x with devel

After installing mod_wsgi 4.4.3.1 version from source, I am trying to set LD_LIBRARY_PATH but it seems it doesn't show when I say ldd in command line.

Here are the steps I followed:

$LD_LIBRARY_PATH=/home/ec2-user/anaconda3/pkgs/python-3.4.3-1/lib

$sudo ldconfig

$sudo service httpd restart

$ ldd /etc/httpd/modules/mod_wsgi.so
        linux-vdso.so.1 =>  (0x00007ffe0f594000)
        libpython3.4m.so.1.0 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb168c9d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb168a99000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fb168896000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb168611000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb16827d000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003da9600000)

The path for libpython shows as not found.

Please help me if I am missing something here or how I need to set this libpython path? Thanks for your help and time.

**Comment by GrahamDumpleton** [comment]
Hmmm, you must have edited the question after getting further than you first problem.

As you found for your first problem, you needed to install the 'httpd-devel' package on your RHEL operating system.

As to the problem with finding shared library, when you build the source code, set the ``LD_RUN_PATH`` environment variable to the location of the directory where the library is. It only needs to be set when doing the compilation.

So something like:

```
make distclean
./configure --with-python=/home/ec2-user/anaconda3/pkgs/python-3.4.3-1/bin/python
LD_RUN_PATH=/home/ec2-user/anaconda3/pkgs/python-3.4.3-1/lib make
sudo make install
```

This should embed the library directory location in the ``mod_wsgi.so`` binary so that it can be found at run time.

You will know if works as it should show up in ``ldd`` output.

**Comment by GrahamDumpleton** [comment]
Closing at this point as no further response.
