### ISSUE TITLE
-> sys.argv <-

### ISSUE THREAD

**Issue by Charon-x0FF** [GrahamDumpleton/mod_wsgi#916]
Hello world ! 

(I am realy bad in english, so I will try my best not to burn your eyes, but I'm sorry in advance!)

I have the intention to modify the library code to meet certain technical constraints in a personal project. I would like to know if anyone among you could help me get the necessary information:

In fact, I have already made my modifications and compiled several times before coming to bother you here, but I tried to modify the wsgi_interp.c file in order to pass the sys.argv arguments without them being truncated... To do this, I decided to leave 'mod_wsgi' as the first element of the Python list, then I used PySys_GetObject('argv') before creating a loop to reinject into the temporary list and then reinject the list via PySys_SetObject('argv', mynewlist).

Unfortunately, I quickly noticed that a problem, likely due to the nature of the data retrieved by PySys_GetObject, appeared, namely that my arguments seemed corrupted; they appear as ['mod_wsgi', <NULL>, <NULL>, ''].

I would like to share my code, but I am not familiar with GitHub, and I don't know if it is inappropriate to share it here. Thank you to those who will take an interest in my post, and I look forward to hearing from you!"

**Comment by Charon-x0FF** [comment]
Oh, I just saw on the issues of projects similar to mod_wsgi that, according to their developers, the arguments are removed in advance... but I have a hard time understanding how this is the case when I still manage to get the correct number of strings?

I'm sorry if I posted for nothing, but since I'm at it, I would really like to understand the subtleties that have led us to be deprived of a functionality that is, however, included in the Python C API...

Thank you in advance to those who will take the time to respond to me !

**Comment by GrahamDumpleton** [comment]
What is the actual problem you are trying to solve?

If you tell why you need to do this rather than what you think is the solution to whatever issues it is you are trying to solve, I may be able to suggest a better solution.

Fiddling around with `sys.argv` is a red flag that you are doing something you probably shouldn't.

**Comment by Charon-x0FF** [comment]
I see what you mean, I am absolutely not looking to do anything that would violate the law... I am a passionate young developer who has developed my own software. Currently, I have found a client who would like to hire my services and would like me to set up an API for them to use one of my software programs. To bypass an access rights issue regarding www-data, I need to pass my arguments via subprocess after allowing access through visudo with nopasswd for the Python binary. That's all, thank you for your quick response, it's appreciated!

(Edit : By the way, thank you for letting me know that my use could be exploited for illegitimate purposes. I originally wanted to make my modification accessible to everyone on GitHub...)

**Comment by GrahamDumpleton** [comment]
That still isn't really explaining what it is you are trying to do and is still describing a solution you already think is the correct one and just raises more red flags.

Also, the `visudo` program generally requires a proper interactive terminal to work which it will not if being executed from within the context of Apache httpd. Needing to run `visudo` from a web application just sounds like a security issue waiting to happen as any stuff up such that a remote user could hack how `visudo` is run or enter arbitrary input to it might provide a pathway to them then compromising your system through other means.

Stepping back even further to your original problem, if you merely need for code to run as a different user to `www-data`, you should use mod_wsgi daemon mode and set `user` and `group` appropriately on the `WSGIDaemonProcess` directive in the configuration so that your Python code, and any sub processes, can execute as your required user.

Is being able to run code/sub processes as a different use to `www-data` the real issue you are trying to solve?

**Comment by Charon-x0FF** [comment]
I love the superior tone you’re taking; it’s really pleasant. I never said that I was passing an instruction via the web application for visudo... wtf, who does that? I was simply talking about the issue of permissions, which I use to allow www-data to execute a script via subprocess with sudo. Furthermore, I have no doubts regarding the security of my app; I provide my client with a module that allows them to have the exact formatting to query the API, a symmetric key generated at the time of the request based on time, as well as a sequencing that follows a formula I created, along with an asymmetric key and the token, of course, all verified well before any instruction is accessible to the client, who is also banned by IP if the HTTP request is poorly formatted.

As for your last paragraph, indeed, the description you provided seems to address my issue, but given the way you describe it, it is likely part of your work that should be well documented. Otherwise, I will make sure to analyze your code to know exactly how to do what you mentioned. Thank you for your responses, and best of luck.

**Comment by GrahamDumpleton** [comment]
For documentation on changing user/group mod_wsgi daemon mode process runs as see:

* https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGIDaemonProcess.html#user
* https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGIDaemonProcess.html#group
