### ISSUE TITLE
mod_wsgi with Python 2.7 VC11 for Windows

### ISSUE THREAD

**Issue by beltran-rubo** [GrahamDumpleton/mod_wsgi#99]
Apache Lounge does not support Apache VC9 now. Could be possible to download mod_wsgi for Python 2.7 compiled with VC11? Most of Python-based applications continue using Python 2.x

**Comment by GrahamDumpleton** [comment]
As is explained in:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/win32/README.rst

Python 2.7 MUST be compiled with VC9. You cannot compile it with later versions of the Microsoft C/C++ compiler toolchain.

As is also explained in that link, you can still trying using the VC9 compiled object binary with a VC11 Apache, but can't guarantee that it will work and technically not supported.

**Comment by beltran-rubo** [comment]
Thanks. Apache Haus supports Apache 2.4.x with VC9 so that would work.

**Comment by GrahamDumpleton** [comment]
That doesn't mean you can take the binaries provided and use them with it. This is because the binaries were compiled against ApacheLounge Apache.

The safest thing to do would be to compile from source again for that other Apache distribution. That can be a lot of mucking around to get right compilers installed.

**Comment by GrahamDumpleton** [comment]
Closing. On Windows everyone should be using ``pip install mod_wsgi`` method to get started, which means they are compiling from source code themselves. If want to ignore MS compiler requirements, at that point up to them.
